### ISSUE TITLE
Other characters do not show correct Alignment, Origin, or Archetype

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#107]
### Expected behavior
When selecting a character, the client shows you their current information, including Alignment, Origin, Archetype, HP, etc.

### Actual behavior/symptoms
Default values are shown. For example, Origin/Archetype is always Science/Blaster

This information is already saved in the database, so I'm assuming EntityResponse isn't updating other clients when sending this data.

**Comment by nemerle** [comment]
Likely EntityResponse is sending 0s instead of proper values.

**Comment by nemerle** [comment]
Or we don't actually set up those values correctly... which is the case
```m_origin_idx,m_class_idx``` are always 0.

**Comment by nemerle** [comment]
To resolve this, we have to load bin/origins.bin,bin/villain_origins.bin,  bin/classes.bin,bin/villain_classes.bin and lookup indices based on those.

**Comment by nemerle** [comment]
As of fc2b4d55fcd8c92892690494721b3be0933194fa we have support for reading and writing entity class and origin tables from data files.

**Comment by nemerle** [comment]
Alignment is not an issue 0 thing, is it ?
If it is feel free to reopen this Issue.

**Comment by broxen** [comment]
I'll research. Character names show up Orange so I figured it was alignment related.

You're on fire. This is amazing. Thanks Nemerle

**Comment by nemerle** [comment]
Or maybe not, do You think we can find somewhere some screenshots that show player/mob highlight colors ?

**Comment by broxen** [comment]
For mobs: https://paragonwiki.com/wiki/Con_System

Will look into players, as I have a ton of old screenshots

**Comment by nemerle** [comment]
Ok, I think this might be related to the fact that entities are dead to each other :)

The health bar is empty over other player.

**Comment by nemerle** [comment]
Yup, Entity::sendCharacterStats looks pretty bare, and it is responsible for sending the other Entity's stats and other helpful things.

**Comment by broxen** [comment]
Ahh. That's definitely it

**Comment by nemerle** [comment]
Will commit some code to address this today

**Comment by nemerle** [comment]
Seems the last part is done :)
