### ISSUE TITLE
Can't find MapServerData.h

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#112]
Can't find MapServerData.h

Maybe it missed the commit?

https://github.com/Segs/Segs/blob/f53acb95b081f530babe4a93e43661a9cdb74ed5/Projects/CoX/Servers/MapServer/MapServerData.cpp#L1

**Comment by nemerle** [comment]
Resolved by  b7b12e2

**Comment by nemerle** [comment]
The file somehow slipped through the cracks :/
