### ISSUE TITLE
ClientManager.h does not exist

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#118]
ClientManager.h does not exist. This doesn't seem to prevent me from compiling, but did produce this error upon shutdown:
```
ACE_ASSERT: file /Segs/Projects/CoX/Common/Servers/ClientManager.h, line 96 assertion failed for 'getById(id)!=0'.Aborting...
Aborted (core dumped)
```

Included by these two files:
https://github.com/Segs/Segs/blob/9625d5878d3d6bdff0bb94e5258dba5dd86cff60/Projects/CoX/Servers/GameServer/GameHandler.h#L2
https://github.com/Segs/Segs/blob/9625d5878d3d6bdff0bb94e5258dba5dd86cff60/Projects/CoX/Servers/MapServer/MapInstance.h#L14

**Comment by nemerle** [comment]
This one Projects/CoX/Common/Servers/ClientManager.h ? :)

**Comment by nemerle** [comment]
If you're using qtcreator, you can ctrl-click on include file and the IDE will take you there

**Comment by broxen** [comment]
Weird. I have the file. I can open it with CTRL+Click or by navigating to the folder, but it doesn't show up in the QTCreator project tree. I tried to refresh the file tree, and tried to reopen the project up to no avail? Weird... Any idea why it wouldn't show up?

**Comment by nemerle** [comment]
It's missing from the list of files in Projects\CoX\Common\Servers\CMakeLists.txt  just add it there and it should appear in the file list

**Comment by broxen** [comment]
`Segs/Projects/CoX/Common/GameData/CMakeLists.txt` has many files commented out. Not sure why we would exclude them? I left them as-is for now.

Wouldn't you want to include every file for build, unless it's environment specific or only built when a flag is set?

**Comment by nemerle** [comment]
As I've noted in the PR comment, those include files are just biding their time :)
