### ISSUE TITLE
Unhandled command event type 62 - Clickable Objects

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#130]
### Expected behavior
Clicking on the plaque under Atlas results in the follow error
```
Unhandled command event type 62
Debug   : Not all bits were consumed
```

### SEGS version
segs v0.4.0 alpha (The Real Beginning) - the latest from git

### Operating system
Windows 10 or Fedora 26

### C++ compiler and version
g++ 5.3.0

**Comment by nemerle** [comment]
Good find, I'll implement that packet later today.
