### ISSUE TITLE
Versioning database tables

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#133]
If we want to support database upgrades ( and we really should ), we need to store an additional table in the database, that will contain a version number of each table, so we can lookup proper 'upgrade' scripts to run. Something like this:

| ID | Table_Name | Version number |
| ------------- | ------------- | ------------- |
| 1  | "accounts"  | 1 |

Then in database management tool we can query current database for the table list and lookup their versions, and run apropriate update scripts.

**Comment by broxen** [comment]
Perhaps we can utilize SQLite's `PRAGMA user_version` to store our own schema version information. There is also `PRAGMA schema_version` but it seems that SQLite auto increments that for every `CREATE` or `DROP` command, but it's not recommended for manual use as it may be changed by SQLite itself.

http://www.sqlite.org/pragma.html#pragma_user_version

Then, as you said, we could check this version info upon authserver startup to see if it matches the version in our default files under the default_dbs folder. If not, `qFault()` and recommended running dbtool to update the databases.

We can either store the update scripts in a default_dbs subfolder and call them in order until we reach version parity, or hard code those queries within the dbtool. This is similar to how Drupal runs dbase updates in PHP/MySQL.

Or worst case, the dbtool can be used to overwrite the current database completely with a new (updated) one.

I'll start to work on this issue. If you have any specific template or roadmap for the database schema in mind please let me know.

**Comment by broxen** [comment]
So definitely no `schema_version`

> SQLite automatically increments the schema-version whenever the schema changes. As each SQL statement runs, the schema version is checked to ensure that the schema has not changed since the SQL statement was prepared. Subverting this mechanism by using "PRAGMA schema_version" may cause SQL statement to run using an obsolete schema, which can lead to incorrect answers and/or database corruption.

http://www.sqlite.org/pragma.html#pragma_schema_version

**Comment by nemerle** [comment]
My thoughts:
* Add a table_versions table to database
* initialize it with all table names that are already in our database
* set all versions to 0.

Using sqlite-only pragma's is not the way to go, since it will prevent using any other DB engine ( and since we use Qt, we get a few of those 'for free' )

**Comment by nemerle** [comment]
As for storing updates, I'd prefer to store them in tool, since some updates could need to perform some logical operations, for example if we had a table with firstname_lastname column, and the update wanted to split that column into two firstname and lastname, then writing a standalone sql script that would do such a thing could become complicated. We could even go one step further towards the standard way of doing such things, and call them `migrations` :P

**Comment by broxen** [comment]
Ah yes that makes perfect sense.

And tool code makes sense too, I had overlooked the possibility of complex actions that would be overly difficult with queries.

I'll work towards this goal and submit schema changes for review using dbdesigner.net

**Comment by broxen** [comment]
Proposed schema changes for segs_game. GitHub wont let me attach the sqlite script file courtesy http://dbdesigner.net:
![download](https://user-images.githubusercontent.com/10159505/32600023-0fd3c060-c4f3-11e7-8c07-fca12d6d3230.png)

**Comment by nemerle** [comment]
Looks good :+1:

**Comment by broxen** [comment]
This can be closed.

**Comment by nemerle** [comment]
Ayup 👍
