### ISSUE TITLE
Error building MapServer/libmapserver_lib.a on first build

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#134]
### Summary
Make a fresh copy of the git, or `reset --hard HEAD` and build in QTCreator results in the following error during build:
```
:-1: error: [Projects/CoX/Servers/MapServer/CMakeFiles/mapserver_lib.dir/build.make:590: Projects/CoX/Servers/MapServer/libmapserver_lib.a] Error 1
```

Simply building again is successful and all builds thereafter are successful. It's just the initial build. Maybe it's some kind of cmake processing order, or include order?

### SEGS version
latest from git (as of 2017-11-06)

### Operating system
Fedora 26 (does not appear to happen on Windows 10)

### C++ compiler and version
g++ 5.3.0

**Comment by nemerle** [comment]
This looks like a missing dependency link between mapserver and some dependent library

**Comment by broxen** [comment]
I'll research this tonight.

**Comment by broxen** [comment]
During testing this happened again but with a different file in GameServer. 'GameServer.cpp.lib.a'

Same behavior as before: running build a second time completes normally.

**Comment by broxen** [comment]
Still getting this issue =/ this time it was mapserver again.

I'll continue to research possible solutions.

**Comment by broxen** [comment]
This issue appears to be resolved. My last comment must have been a fluke because I can't replicate the issue anymore.

**Comment by broxen** [comment]
Maybe I spoke too soon...

```
/SEGS/Segs/Projects/CoX/Servers/MapServer/MapInstance.cpp:675:55: warning: unused parameter ‘ev’ [-Wunused-parameter]
 void MapInstance::on_client_settings(ClientSettings * ev)
                                                       ^~
[ 83%] Linking CXX static library libmapserver_lib.a
/usr/bin/ar: CMakeFiles/mapserver_lib.dir/DataHelpers.cpp.o: No such file or directory
gmake[2]: *** [Projects/CoX/Servers/MapServer/CMakeFiles/mapserver_lib.dir/build.make:694: Projects/CoX/Servers/MapServer/libmapserver_lib.a] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1318: Projects/CoX/Servers/MapServer/CMakeFiles/mapserver_lib.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
00:20:42: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project SEGS (kit: Desktop)
When executing step "Make"
00:20:42: Elapsed time: 00:07.
```

Same behavior as originally reported. Building a second time resolves the issue.

This test was with latest from git.

**Comment by nemerle** [comment]
I must say I'm a bit stumped,  DataHelpers.cpp is part of mapserver lib, so I have no idea why it wouldn't compile it before trying to link library...

**Comment by broxen** [comment]
I'll continue to research. Maybe it's a QTCreator issue?

It doesn't happen for me on Windows 10

**Comment by broxen** [comment]
This thread: https://github.com/davisking/dlib/issues/109 seems to indicate that it might be a memory issue, but my System Monitor shows me as having plenty of excess memory during compile.

**Comment by broxen** [comment]
This issue appears resolved for me. I haven't been able to replicate for several commits now.
