### ISSUE TITLE
Design some logic for damage floaters

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#149]
Since we now have:
![cohfloatingdamage](https://user-images.githubusercontent.com/96597/32625087-94d7e2c6-c58b-11e7-9a93-6c7ff67e04a8.png)

We should design some sane interface to send those.

**Comment by broxen** [comment]
A (remedial) framework for this now exists in DataHelpers. Closing.

Feel free to reopen if I've overlooked something
