### ISSUE TITLE
Add markup testing code

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#155]
Write a chat command that will cause the server to read a simple markup language X file (smlx for short :wink: ) and send it as a standard dialog command to the client. It's main role is to help with writing markup language files for various game messages.
Steps to implement:
1. Modify ```void MapInstance::on_console_command(ConsoleCommand * ev)``` to handle 'smilex ' console command.
2. While processing 'smilex' request, check if server has a 'test.smlx' file on disk
3. If it's there, send it's contents to the client wrapped in StandardDialogCmd instance.
4. If it's not there, send appropriately mournful message to the client.

**Comment by broxen** [comment]
Hi @nemerle!

I'm looking this over and I have several questions. Forgive me in advance, as I'm sure I'm just overlooking something obvious, but here goes...
- Aren't we somewhat reinventing the wheel with this additional scripting method? We already have XML parsing through QT, and LUA with SOL2, either of which could handle this task.
- Is there some benefit to parsing the text outside of the script file itself? Maybe localization? Speed? I'm probably just overlooking an obvious benefit.
- How is reusability affected? Can I reference the same string multiple times?
- In `misc.pigg` the text strings already contain psuedo HTML, how would we rewrite this? For example in `Contact2_Task_taskset.ms`
```
Things are getting out of control, and I can tell you need to learn all about combat, {HeroName}. First, I want you to <A HREF={ACCEPT}>learn about how tough things can be</A> by talking to Professor Hoffman in front of the deactivated robots to my left, then talk to Lt. MacReady for your combat lesson.
```

Just trying to save you work on another scripting engine, if we can leverage existing tools to complete this same task.

**Comment by broxen** [comment]
This example from the same file is probably better
```
"K3594109411"	"Here we have three deactivated robots. If you left click on them you can target them. This is how you determine which enemy you are attacking.<br><br>You can also Consider (or 'con') your target and note the level difference to your character by the color of the name. <color #ff9900>Orange names</color> mean they are one level stronger than you and <color #0000ff>Blue names</color> mean they are one level weaker than you. There are other colors for even stronger or weaker enemies.<br><br>There are also three different types of enemies at each level, these are <color #ffff00>Minions</color>, <color #ff9900>Lieutenants</color>, and <color #ff0000>Bosses</color>. <color #ffff00>Minions</color> are the weakest and you should be able to defeat these easily. <color #ff9900>Lieutenants</color> are stronger, and have more attacks and can take more damage. Finally <color #ff0000>Bosses</color> are the strongest, and even if a Boss 'cons' green to you, you are in for a tough fight.<br><br>Now Officer Parks asked me to remind you to now go out and defeat two of the contaminated Thugs."
```

**Comment by nemerle** [comment]
Hah, the main task for this functionality is having an 'editor' to help write proper markup files:
1. A contributor tries to write a location/plaque/quest text
2. They select their favourite text editor and edit "test.smlx"
3. While editing that file, they periodically run "/smilex" command on the client to see how the file looks there.
4. ...
5. Profit ? :)

**Comment by nemerle** [comment]
And ".smlx" contents are exactly the same format as the ones in misc.bin, just editable in plain old text editors :)

**Comment by nemerle** [comment]
Of course, the best solution would be to use a html wysiwyg editor, and then transform it's output into a form client 'can' process, but that's a lot of work, for a bit of functionality we can basically get for free :)

**Comment by broxen** [comment]
Looking at adding this to MapInstance.cpp

```
else if(ev->contents.startsWith("smilex ")) {
        int first_space = ev->contents.indexOf(' ');
        int second_space = ev->contents.indexOf(' ',first_space+1);
        QString fileName(ev->contents.mid(second_space+1));
        QFile file("./scripts/"+fileName);
        if(QFileInfo::exists(fileName))
        {
            StandardDialogCmd *dlg = new StandardDialogCmd(file.readAll);
            src->addCommandToSendNextUpdate(std::unique_ptr<StandardDialogCmd>(dlg));
        }
        else {
            QString errormsg = "Failed to load smilex file. File not found.";
            qDebug() << errormsg;
            cl->addCommandToSendNextUpdate(std::unique_ptr<ChatMessage>(ChatMessage::adminMessage(errormsg)));
        }
    }
```

But I'll need to parse the smlx file for the key-value pairs? Or you just want to spit out the entire contents into the dlg?

**Comment by nemerle** [comment]
Contents to dialg, key-value stuff is for later. For now we need a tool that will help with editing/testing dialogs.

**Comment by broxen** [comment]
This can be closed. Thanks Nemerle!
