### ISSUE TITLE
Missing lua.hpp error during build

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#156]
### Issue Summary
Latest commit results in missing lua.hpp error during build.

### Behavior/Symptoms
```
[ 82%] Building CXX object Projects/CoX/Servers/MapServer/CMakeFiles/mapserver_lib.dir/ScriptingEngine.cpp.o
In file included from /SEGS/Segs/Projects/CoX/Servers/MapServer/ScriptingEngine.cpp:10:0:
/SEGS/build/3rd_party/built/include/sol2/sol.hpp:1578:10: fatal error: lua.hpp: No such file or directory
 #include <lua.hpp>
          ^~~~~~~~~
compilation terminated.
gmake[2]: *** [Projects/CoX/Servers/MapServer/CMakeFiles/mapserver_lib.dir/build.make:615: Projects/CoX/Servers/MapServer/CMakeFiles/mapserver_lib.dir/ScriptingEngine.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1318: Projects/CoX/Servers/MapServer/CMakeFiles/mapserver_lib.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
19:26:05: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project SEGS (kit: Desktop)
When executing step "Make"
19:26:05: Elapsed time: 00:01.
```

### Steps to reproduce behavior/symptoms
Clone latest git (540e7bce4d11c5126360c8180af6b39b3aa818a6) and build.

### System Info
Qt 5.9.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.2.1 20170915 (Red Hat 7.2.1-2)) on "xcb" 
OS: Fedora 26 (Workstation Edition) [linux version 4.13.8-200.fc26.x86_64]

**Comment by broxen** [comment]
This is frustrating. I see that lua.hpp is included here prior to loading sol2:
https://github.com/Segs/Segs/blob/540e7bce4d11c5126360c8180af6b39b3aa818a6/Projects/CoX/Servers/MapServer/ScriptingEngine.cpp#L9-L10

Is this a bug upstream with SOL2?

**Comment by nemerle** [comment]
Might be a simple to solve, I think SOL2 expects lua.hpp to be directly accessible.. we might solve it by simply modifying sol.hpp to refer to lua/lua.hpp
