### ISSUE TITLE
Zoom-in camera to First Person View results in `Not all bits were consumed`

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#160]
### Summary
Zooming in camera to First Person View results in `Not all bits were consumed` debug message.

### SEGS version
segs v0.4.0 alpha (The Real Beginning)

### System Info
Qt 5.9.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.2.1 20170915 (Red Hat 7.2.1-2)) on "xcb" 
OS: Fedora 26 (Workstation Edition) [linux version 4.13.8-200.fc26.x86_64]

**Comment by nemerle** [comment]
Should be resolved by a8b0b0d

**Comment by broxen** [comment]
Handled by #161. Can probably close this until we know what to do with `EVENT_DECL(evSwitchViewPoint        ,264)`
