### ISSUE TITLE
Question about client patches.

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#162]
I have a question related to the problems some of our users have with running their I0 client's on intel built-in gfx cards.

I've managed to replicate one of the graphics problems, and I might write a patch that will fix it, but:
1. It will require an exe patch , which will cause the following changes:
    - Make the exe import SEGSclient.dll
    - make the exe export bunch-load of functions/data
2. Would add a SEGSclient dll project to the build on windows platforms (mingw/visual studio ) , which would contain fixed/rewritten client code.

The client exe changes would be distributed as xdiff patch ( with clear instructions how to apply it/ a script that would do it )
And the SEGSclient.dll would be built from source, distributed in binary form with server releases.

Thoughts ?

**Comment by broxen** [comment]
This looks interesting:
> make the exe export bunch-load of functions/data

Would a bump up to I2 resolve this issue? I don't have any computers with intel integrated chips, so I'm unable to test. What other issues would advancing the client version introduce?

My thoughts are that this solution could work, but potentially complicates the setup process. Also, if the long term goal is moving to I2 anyway, and that ALSO resolves this problem, maybe it's a better route as it would consolidate resources towards a common future goal.

**Comment by mobbyg** [comment]
Also, what about Radeon gfx? Would moving to I2 address that as well. I do plan on getting a higher end GeForce card which should make my issue go away.. but for others?

**Comment by broxen** [comment]
I'll have to look through the old patch notes to confirm, but I believe the Radeon X300 was supported and those came out around 2005.

**Comment by nemerle** [comment]
Oh, I don't doubt that moving to I2 would solve the graphics problems, trouble is, the patch would likely take a day or three, while moving the whole server to support I2 would take over a month ( and that's very optimistic estimate )

**Comment by broxen** [comment]
Oh I see. Yes in that case, try the patch first. Are there any ancillary benefits to the patch? I'm referring to
> make the exe export bunch-load of functions/data

**Comment by nemerle** [comment]
Weeeeeelll, we might patch other things ?
Any of them ?  :innocent:

**Comment by nemerle** [comment]
First step is complete at 949acc69bcab9f6ffd5cb2018b757aa96ce5f78b

**Comment by broxen** [comment]
Will the client expect this? I guess I'm asking, do you need to patch, or can you run it without.

**Comment by broxen** [comment]
Also, is it possible to patch the encryption so that we can run any client version without reworking the encryption for each issue? This is similar to what Razor did with UO and UOX back in the day.

**Comment by nemerle** [comment]
The server won't expect this unless we do something very interesting while patching :)

And to the second question, yes, but the server can force non-encrypted connection ( unless things changed in later Issues)

**Comment by broxen** [comment]
Well I suppose we'd still want some form of encryption on the connection, otherwise haxxors :cry: but I was thinking we could maybe force our own encryption that is known?

I'm purely speculating. I don't know enough about the inner workings of the client<-->server relationship to know if that would actually work or not.

**Comment by nemerle** [comment]
With patches it could work, yes :)

**Comment by nemerle** [comment]
Also, since patching the function responsible for setting up the renderer I had to add [GameState.h](https://github.com/nemerle/Segs/blob/client_patching/Projects/CoX/Clients/Client_I0/include/GameState.h)
There are many interesting things we can actually twiddle with in the client's internals now :)

**Comment by broxen** [comment]
I think we've resolved this question?

Proposing we close this.

**Comment by nemerle** [comment]
Agreed
