### ISSUE TITLE
[question] Are you ok with me using bountysource for issues?

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#171]
Are you ok with me using http://bountysource.com for issues? If you're unfamiliar with it, you basically assign a dollar amount to the issue and developers can come along and correct the issue to earn the reward.

It may be a way for me to contribute by drawing in more talented support. Well, more talented than me anyway.

If not, it's ok. I completely understand.

**Comment by nemerle** [comment]
I thought about using bountysource a few times, but fail to see it's utility in our context. Of course I would welcome more contributions to the project, but You are the first 'new' person that stuck with it long enough to provided valuable help. 
And I'd love to have more people like You broxen, but I'm not all that sure we would get them by offering bounties on a troubled platform ( bountysource is currently managed by volunteers ).

Of course I'm willing to be convinced. So if there's anyone out there, considering helping SEGS out and having a moderate bounty as a reward for solving a task would be enough to convince them to help out, please do chime-in.

**Comment by broxen** [comment]
That makes complete sense, and thank you for your kind words.

The inspiration came from seeing it utilized to great effect by TrinityCore (a WoW server forked from Mangos).

My thought is that it's probably an issue of time for some people. Do they choose to work on this or something else in their spare time.  Perhaps a few bucks could persuade them?

I don't know how many lurkers there are here, but I was more thinking that we might get some fresh new eyes on the project as well. Perhaps those that loved CoH, but weren't aware of a private server project.

I was thinking of trying it out on a couple of smaller issues that I can't seem to figure out. Let me know if there's any issues that you'd like focus on.

**Comment by nemerle** [comment]
Well, trinitycore has many issues on bountysource, but they've only had 2 bounties actually resolved in 2017, not that great :smile:

**Comment by broxen** [comment]
Oh, good point. I didn't realize that.

**Comment by broxen** [comment]
I suppose we can close this issue. I'll see if we get any action on the bounty I posted, but so far nothing.
