### ISSUE TITLE
Character Class should inherit from Entity Class?

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#173]
Maybe I'm misunderstanding the intended design, but it seems like the `Character` class should inherit from the `Entity` class, no? This would allow us to reuse variables that either class may want to see. Such as `m_character_description` or `m_origin` etc.

Further, a Character is always an Entity, but an Entity may be many different things.

My intended use, for example: in Character.cpp the method `void Character::sendDescription(BitStream &bs) const` should reuse the `m_character_description` and `m_battle_cry` variables from `Entity`. I don't think we should make these variables static, so if not through inheritance, what's the best way to go about this?

**Comment by nemerle** [comment]
Second issue first: Since cars or doors or npc do not have battle cries, nor character descriptions ( I think ? ) we could just move those 2 fields to Character ?

**Comment by broxen** [comment]
Hrm.. Doing that, and then converting uses from `src.m_battle_cry` to `src.m_char.battle_cry` causes the client to crash when more than one entity enters the world.

**Comment by broxen** [comment]
Can entities have titles? I moved those variables out into Character class as well. Maybe that's why I'm crashing?

Below makes it seem like Entity needs to check for titles. Not sure why that would give the Network Error though.
```
void sendTitles(const Entity &src,BitStream &bs)
{
    Character c = src.m_char;
    bs.StoreBits(1,c.m_has_titles); // Does entity have titles?
    if(!c.m_has_titles)
        return;
    if(src.m_type==Entity::ENT_PLAYER)
    {
        bs.StoreString(c.getName());
        bs.StoreBits(1,c.m_has_the_prefix);       // likely an index to a title prefix ( 0 - None; 1 - The )
        storeStringConditional(bs,c.m_titles[0]); // Title 1 - generic title (first)
        storeStringConditional(bs,c.m_titles[1]); // Title 2 - origin title (second)
        storeStringConditional(bs,c.m_titles[2]); // Title 3 - yellow title (special)
    }
    else // unused
    {
        bs.StoreString("");
        bs.StoreBits(1,0);
        storeStringConditional(bs,"");
        storeStringConditional(bs,"");
        storeStringConditional(bs,"");
    }
}
```

My working branch:
7adf86016d72880cf59833ec1f4d0c31216d02a1

**Comment by broxen** [comment]
I appear to have fixed it by changing `StoreString` here to `storeStringConditional`

```
void Character::sendTitles(BitStream &bs) const
{
    bs.StoreBits(1,m_has_the_prefix);   // likely an index to a title prefix ( 0 - None; 1 - The )
    storeStringConditional(bs, m_titles[0]);        // Title 1 - generic title (first)
    storeStringConditional(bs, m_titles[1]);        // Title 2 - origin title (second)
    storeStringConditional(bs, m_titles[2]);        // Title 3 - yellow title (special)
}
```
