### ISSUE TITLE
Targeting another entity produces `Unhandled command event type 32`

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#174]
### Summary
Targeting another entity produces `Unhandled command event type 32`

### Steps to Replicate
Log in with two entities. Click on another entity to target.

### SEGS version
Commit 8bc8fd3

**Comment by broxen** [comment]
Attempted to resolve with #175, however it's still giving me the error message.

**Comment by broxen** [comment]
#175 addresses this, but outputs `-1` for what I'm calling `entity_idx` when targeting other players and the following when hitting ESC to clear targets:
```
Debug   : Not all bits were consumed
Warning : Unhandled set target request: 1919
Console command received ü
Debug   : Unhandled game command: "Ã¼\u001B"
```

So maybe there is some kind of boolean isTargetingSelf, and then the idx of the target in there? I'm not sure how to parse the bitstream in `class SetTarget`

**Comment by nemerle** [comment]
Will look into it tomorrow ( around 12h from now)

**Comment by broxen** [comment]
Based upon our IRC chat, #175 now resolves this.

**Comment by broxen** [comment]
Closing this as it's now a duplicate of #192
