### ISSUE TITLE
[question] Variable naming convention?

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#177]
Is there a naming convention you prefer for variables?

I've been following your lead with member variables prefixed by `m_` but are there any other conventions we should follow?

I'll add whatever is defined here to the CONTRIBUTING.md and style guide.

**Comment by nemerle** [comment]
I usually use :
m_undersore_separated_words for member variables
s_undersore_separated_words for file scope variables ( basically all variables defined as static in cpp file and all variables contained in anonymous namespaces in cpp file)
g_underscore_separated_words for global variables.

**Comment by broxen** [comment]
Sounds good to me. All lowercase, I assume?

I'll add this to the docs and submit a PR
