### ISSUE TITLE
Move all user settings to a single blob column.

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#183]
We do not need nor actually want to have each and every setting accessible in the database.
So we should just serialize user settings using cereal and store them in per-user ```account``` table, or per-character ```characters``` in an 'options' column.

**Comment by broxen** [comment]
Per original client behavior, this should be per character.

It will need a DB schema change to take a blob for options instead. We might even be able to remove the options table all together.

See:
[Game DB Schema](/Segs/Segs/blob/master/Projects/CoX/Data/segs_game_dbschema.png)

**Comment by nemerle** [comment]
Yup, both options and gui tables should be removed and user/char settings should be serialized from that single column in ```characters``` table
