### ISSUE TITLE
MapInstance::on_location_visited is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#184]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 626 of MapInstance.cpp.
There is code in this function, but it looks purely mechanical.
When called, it gives "Unhandled location visited event: " along with presumably the (x, y, z) position of the location to qWarning().

**Comment by nemerle** [comment]
Discussion in #136 might be useful

**Comment by broxen** [comment]
I'm closing this as the server handles the incoming packets properly and it seems that we utilize this on a per-case basis (for Plaques, for doors etc)
