### ISSUE TITLE
MapInstance::on_plaque_visited is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#185]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 638 of MapInstance.cpp.
There is code in this function, but it looks purely mechanical.
When called, it gives "Unhandled plaque visited event: " along with presumably the (x, y, z) position of the plaque to qWarning().
Discussion in #136 might be useful here.

**Comment by broxen** [comment]
This is now handled. The server looks for a lua script in the zone folder. The remaining logic is specific to each plaque location (of which we know of only 2 in our client version)

Closing. Someone can open a new issue to implement the specific scripts per zone.
