### ISSUE TITLE
MapInstance::on_inspiration_dockmode is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#186]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 648 of MapInstance.cpp.
When called, it gives "Unhandled inspiration dock mode:" along with dock_mode to qWarning().

**Comment by broxen** [comment]
To the best of my knowledge, this now does everything it's supposed to do. Closing.
