### ISSUE TITLE
MapInstance::on_enter_door is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#187]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 653 of MapInstance.cpp.
When called, it gives "Unhandled door entry request:" and name to qWarning().noquote(). It also has logic to deal with unspecified locations, though it only prints debug messages.

**Comment by broxen** [comment]
This is *somewhat* handled in the merged PR #495 

Going to close this for now.
