### ISSUE TITLE
MapInstance::on_change_stance is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#188]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 666 of MapInstance.cpp.
When called, it gives "Unhandled change stance request" to qWarning(). It also has logic to differentiate between entering and exiting a stance, though it only gives debug messages.

**Comment by broxen** [comment]
What is change stance? Do we know?

**Comment by broxen** [comment]
This appears to relate to the stance your character takes when executing certain powers. It's related to the sequence bits and animations systems.
