### ISSUE TITLE
MapInstance::on_set_destination is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#189]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 675 of MapInstance.cpp.
When called, it gives "Unhandled set destination request" along with destination information to qWarning().

**Comment by broxen** [comment]
What causes this to fire? Clicking on a location on the map?

**Comment by broxen** [comment]
Closed by #596
