### ISSUE TITLE
MapInstance::on_description_and_battlecry is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#191]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 686 of MapInstance.cpp.
When called, it gives "Unhandled description and battlecry request" along with description and battlecry to qWarning().
TODO: client expects us to force it to fill description and battlecry fields in UI?

**Comment by broxen** [comment]
Current build saves information entered on the ID (profile) page correctly, but does not load BattleCry or Description on this page properly. Not sure if there's another MapEvent that is supposed to send this information, or if we're sending something incorrect elsewhere, but this is sort of "half" working.

**Comment by broxen** [comment]
To the best of my knowledge, this now does everything it's supposed to do. Closing.
