### ISSUE TITLE
MapInstance::on_switch_viewpoint is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#194]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 704 of MapInstance.cpp.
When called, it gives "Unhandled switch viewpoint to" along with new_viewpoint_is_firstperson to qWarning().

**Comment by broxen** [comment]
To the best of my knowledge, this now does everything it's supposed to do. Closing.
