### ISSUE TITLE
MapInstance::on_chat_reconfigured is unhandled

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#195]
### Summary
This is one of many events in MapInstance.cpp that is unhandled in one way or another.
### Details
Begins on line 709 of MapInstance.cpp.
When called, it gives "Unhandled chat channel mask setting" along with m_chat_top_flags and m_chat_bottom_flags to qWarning().

**Comment by broxen** [comment]
To the best of my knowledge, this now does everything it's supposed to do. Closing.
