### ISSUE TITLE
Build error in RendererUtils

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#196]
### Expected behavior
A working build of the project, I suppose.
### Actual behavior/symptoms
Error Text: C:\SEGS Dev\Segs\Projects\CoX\Clients\Client_I0\renderer\RendererUtils.cpp:112: error: 'void segs_wcw_statemgmt_enableColorMaterial()' was declared 'extern' and later 'static' [-fpermissive]
 static void segs_wcw_statemgmt_enableColorMaterial()

Upon attempting the build again to clean up the warnings, I think I understand what happened. In RendererUtils.h, the segs_wcw_statemgmt_enableColorMaterial() function was declared as an "extern" function, while the corresponding RendererUtils.cpp file has it declared as a "static" function. For whatever reason, the compiler didn't like that.
### Steps to reproduce behavior/symptoms
Open the project in Qt Creator and Build All.
### SEGS version
Current master
### Operating system
Windows 7 64-bit
### C++ compiler and version
Qt Version 5.10.0

**Comment by erpmario** [comment]
Changing "static" to "extern" in RendererUtils.cpp seems to fix the problem. Changing "extern" to "static" in the header file instead also gets rid of the error, but causes several warnings to appear about the function never being defined.

I unfortunately cannot comment on if this truly fixes the problem, as my version of the project still does not build completely. It doesn't seem to be related to this issue here though.

**Comment by erpmario** [comment]
This issue doesn't really matter at the moment, since the entire `Clients` directory has been commented out of the CMakeLists while we wait on nem's client patch. I'm not sure if I should close this issue, because while the error still technically exists, it won't affect the build process.

**Comment by broxen** [comment]
I'd leave it open until after Nem has completed his shader's patch

**Comment by broxen** [comment]
Does this still affect 2033219?

**Comment by nemerle** [comment]
I'm closing this off, the client patch build is disabled by default, and the code has evolved quite a bit since this ticket was posted :)
