### ISSUE TITLE
piggtool: QString fname is never read in from the user

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#197]
### Edit
This was not an actual issue, but rather just my incompetence at operating a Windows Command Prompt. Remember the period kids, remember it.
### Expected behavior
When using piggtool to extract data from a .pigg file, the program should use the file path the user provides in the console to find and use the .pigg in question.
### Actual behavior/symptoms
Due to the way the code for this utility is written (Segs/Projects/CoX/Utilities/piggtool/main.cpp), the file path the user enters is never actually read into the program. The program uses a QString variable fname to serve as the .pigg's file path. It appears on lines 43, 84, 162, and 164. However, it is never written to -  only declared and read from. This results in the program never finding a file to use, and so it will always output:

QFSFileEngine::open: No file name specified
failed to open source file ""
### Steps to reproduce behavior/symptoms
1. Build the most recent version of SEGS and navigate to the "out" folder.
2. In another window, navigate to your Qt installation folder, and then to the version you are currently running. Go to "mingw53_32," and finally "bin."
3. Copy over the following files to the SEGS "out" folder:
libgcc_s_dw2-1.dll
libstdc++-6.dll
libwinpthread-1.dll
Qt5Core.dll
4. Run the command prompt and navigate to the SEGS "out" folder.
5. Input `piggtool -x [anything]` (do not leave it blank).
### SEGS version
My local version
### Operating system
Windows 7 64-bit
### C++ compiler and version
Qt Version 5.10.0

**Comment by nemerle** [comment]
Value PiggFile::fname is written to at line 84 of ```loadPigg```, with argument ```fname``` though ?

**Comment by erpmario** [comment]
So I figured out what my problem was. I forgot to put a period before the .pigg file's directory.

\data\bin.pigg
But what I should have typed was:
.\data\bin.pigg

Not one of my proudest moments. Though I do appreciate the new feedback for invalid input. The program now will accurately reflect to the user that it is reading input. I'll go ahead and close this, since it's pretty much resolved.
