### ISSUE TITLE
Documentation doesn't specify client command line arguments

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#202]
Client must be run with ` -project SEGS` command line argument, otherwise it will output error message about patching using coh_updater.exe.

Docs should be updated to reflect this necessary step.

**Comment by broxen** [comment]
It might be valuable to list a couple of other useful command line args as well.

` -project SEGS -fullscreen 0 -screen 1024 768` for example

https://paragonwiki.com/wiki/Game_Client

**Comment by erpmario** [comment]
I can confirm that those arguments work and are extremely helpful.

**Comment by nemerle** [comment]
I still hope we will have a client launcher utility some day :)

**Comment by erpmario** [comment]
That would be awesome. Would help save so many headaches.
