### ISSUE TITLE
Update Compiling and Connecting Guides on the Forums

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#206]
We should update the connecting and build guides on the forums based upon the new build process and the updated README.md

Relies on #203 and #204

**Comment by erpmario** [comment]
As soon as nem pins my new thread, this issue can be considered closed!

https://segs.nemerle.eu/forumz/viewtopic.php?f=4&t=8807

**Comment by erpmario** [comment]
Seeing as nem has stickied the thread, this issue is good to go!
