### ISSUE TITLE
Implement I0 emotes

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#207]
This will take several steps to accomplish.

- [x] Implement slash commands for all emotes
- [x] Implement emote text using the emote channel (relies on #175)
- [ ] Implement animations to accompany emotes

**Comment by erpmario** [comment]
I have completed task 1 in my local repository. I'm holding off on a PR as it also contains my readme and DLL transfer edits, which are not yet perfected.

**Comment by erpmario** [comment]
Task 1 has been officially completed in master, though it looks like you already took care of that!

**Comment by broxen** [comment]
@nemerle, should I close this issue for now, and reopen a new (broader) one for animations? Or leave it open and reference this issue from a new one for animations?

**Comment by broxen** [comment]
I'm going to close this for now, as animations and FX are a ways away.

Great job on this @erpmario!
