### ISSUE TITLE
Create a CharacterSettings class

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#231]
The struct that contains the settings is currently defined in
`CoX/Servers/MapServer/Events/ClientSettings.h`
This class should be cereal'izable and versioned.

The serialized data should be stored as a single BLOB/bytea column in per-character table.
The serialization format should be json.

http://uscilab.github.io/cereal/serialization_functions.html

**Comment by broxen** [comment]
I think this relies on #183, #193, and #218

**Comment by broxen** [comment]
`ClientOptions` looks to be a part of this, but also contains additional variables such as 
```
    int32_t svr_lag,svr_lag_vary,svr_pl,svr_oo_packets,client_pos_id;
    int32_t atest0,atest1,atest2,atest3,atest4,atest5,atest6,atest7,atest8,atest9;
    int32_t predict,notimeout,selected_ent_server_index;
```
and others.

Should these be separated out, or do we really want to serialize and save all of this information to the database?

Maybe two fields? ClientFlags and ClientSettings?

**Comment by broxen** [comment]
Closed woooooo!
