### ISSUE TITLE
Make client side movement more bearable : set the fly bit on jump

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#241]
When we jump now, the server simply increments the current Y coordinate of the player.

Since the server-side position never 'falls' with gravity, and client firmly believes that what comes up must go down, we could at least prevent 'forever falling' thing, by setting a proper bit in the entity, thus marking it as a flying one.

**Required skills**: c++
**Required knowledge**: ability to find the proper bit in Entity and set it when first 'jump' event arrives for that entity.

Thanks go to: @mobbyg for inspiration 💡

**Comment by miles200** [comment]
(Trying) to look at this one
