### ISSUE TITLE
GameServer should be aware of all active character entities, and provide means of accessing those entities

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#242]
Right now, GameServer doesn't provide any means for polling active entities. It doesn't really know who is connected and on what map instance.

We'll need to hold a container of all active PlayerHandles in GameServer, where the Handle will contain the db_id,map_id,instance_id.  and add methods of looking up PlayerHandles

**Comment by broxen** [comment]
Currently server provides `getEntity()` which relies on MapInstance and thus is limited in utility.

**Comment by nemerle** [comment]
now we have Client sessions that are held in the GameHandler, please consider what api you need, and create InternalEvent Request/Response RequestData/ResponseData for it :smile:

**Comment by broxen** [comment]
Excellent! Will look into this after interp work.

**Comment by broxen** [comment]
Closing this per Nems changes to internal events
