### ISSUE TITLE
No Rule to Make Target on Mac OSX

### ISSUE THREAD

**Issue by mobbyg** [Segs/Segs#252]
### Expected behavior
Should continue compile of ACE

### Actual behavior/symptoms
Halts compile and exits.. 

make[2]: *** No rule to make target `3rd_party/built/lib/libACE.so', needed by `out/AuthExerciser'.  Stop.
make[1]: *** [Projects/CoX/Utilities/AuthExerciser/CMakeFiles/AuthExerciser.dir/all] Error 2
make: *** [all] Error 2
21:45:12: The process "/usr/local/bin/cmake" exited with code 2.

### Steps to reproduce behavior/symptoms
Run Build All in Qt5 on Mac OS X

### SEGS version
0.4.0 alpha

### Operating system
Mac OS Sierra 10.12.6

### C++ compiler and version
cmake version 3.10.2

**Comment by broxen** [comment]
Has this been resolved by #266?

**Comment by nemerle** [comment]
We need someone to test it on the apple-pie machine :)

**Comment by mobbyg** [comment]
I’ll be happy to give this a go tomorrow while the Padawan is sleeping. 😃

**Comment by mobbyg** [comment]
Re puled the code, recompiled and works fine!
