### ISSUE TITLE
Not All MacOS Header files are in the 3rd_party include. 

### ISSUE THREAD

**Issue by mobbyg** [Segs/Segs#253]
### Actual behavior/symptoms
Stops compiling because it can't find one or more of the config-macosx-* header files. 

### Steps to reproduce behavior/symptoms
Ran Cmake:
[ 12%] Building CXX object Components/CMakeFiles/SEGS_Components.dir/ConfigExtension.cpp.o
In file included from /Users/kb2mob/Documents/GitHub/Segs/Components/ConfigExtension.cpp:2:
In file included from /Users/kb2mob/Documents/GitHub/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/INET_Addr.h:15:
In file included from /Users/kb2mob/Documents/GitHub/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/Sock_Connect.h:17:
In file included from /Users/kb2mob/Documents/GitHub/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/ACE_export.h:10:
In file included from /Users/kb2mob/Documents/GitHub/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config-lite.h:22:
In file included from /Users/kb2mob/Documents/GitHub/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config-macros.h:22:
In file included from /Users/kb2mob/Documents/GitHub/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config.h:1:
/Users/kb2mob/Documents/GitHub/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config-macosx.h:6:10: fatal error: 'config-macosx-mavericks.h' file not found
#include "config-macosx-mavericks.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Components/CMakeFiles/SEGS_Components.dir/ConfigExtension.cpp.o] Error 1
make[1]: *** [Components/CMakeFiles/SEGS_Components.dir/all] Error 2
make: *** [all] Error 2
21:25:50: The process "/usr/local/bin/cmake" exited with code 2.
Error while building/deploying project SEGS (kit: Desktop Qt 5.9.3 clang 64bit)
When executing step "CMake Build"
21:25:51: Elapsed time: 01:45.

### SEGS version
0.4.0 alpha

### Operating system
MacOS Sierra 10.12.6

### C++ compiler and version
cmake version 3.10.2

**Comment by mobbyg** [comment]
I looked in the 'naked_ace.tgz' archive and the files are in there. So I manually copied them and started to compile and it continued to compile...

**Comment by broxen** [comment]
This appears to apply to AuthServer as well, and probably anywhere we target ACE.

Looks like it relates to this? http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=4167

**Comment by mobbyg** [comment]
OK, Got another one. But the file it says is missing, is in the directory... 

[  5%] Built target ACE_BUILD
[  6%] Building CXX object Projects/CoX/Servers/AuthServer/CMakeFiles/authserver_lib.dir/AuthClient.cpp.o
In file included from /Users/kb2mob/Segs/Projects/CoX/Servers/AuthServer/AuthClient.cpp:8:
In file included from /Users/kb2mob/Segs/Projects/CoX/Servers/AuthServer/AuthClient.h:10:
In file included from /Users/kb2mob/Segs/Projects/CoX/Common/Servers/Client.h:12:
In file included from /Users/kb2mob/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/INET_Addr.h:15:
In file included from /Users/kb2mob/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/Sock_Connect.h:17:
In file included from /Users/kb2mob/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/ACE_export.h:10:
In file included from /Users/kb2mob/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config-lite.h:22:
In file included from /Users/kb2mob/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config-macros.h:22:
In file included from /Users/kb2mob/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config.h:1:
/Users/kb2mob/build-Segs-Desktop_Qt_5_9_3_clang_64bit-Default/3rd_party/built/include/ace/config-macosx.h:6:10: fatal error: 'config-macosx-mavericks.h' file not found
#include "config-macosx-mavericks.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Projects/CoX/Servers/AuthServer/CMakeFiles/authserver_lib.dir/AuthClient.cpp.o] Error 1
make[1]: *** [Projects/CoX/Servers/AuthServer/CMakeFiles/authserver_lib.dir/all] Error 2
make: *** [all] Error 2
22:48:08: The process "/usr/local/bin/cmake" exited with code 2.
Error while building/deploying project SEGS (kit: Desktop Qt 5.9.3 clang 64bit)
When executing step "CMake Build"
22:48:08: Elapsed time: 00:01.

**Comment by broxen** [comment]
Has this been fixed by #266?

**Comment by mobbyg** [comment]
As of my last comment there.. appears so...
