### ISSUE TITLE
Find free alternatives to fonts used in the original client

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#263]
Some of the tools we make might want to follow the original graphical style, so we need replacements for the following fonts:

- [ ] fonts/mont_hvbold.ttf -> "Montreal-Heavy, Regular"
- [ ] fonts/mont_demibold.ttf -> "Montreal-DemiBold, Regular"
- [ ] fonts/REDCIRCL.ttf -> "Red Circle, Regular"
- [ ] fonts/tahomab.ttf -> "Tahoma, Bold"
- [ ] fonts/verdana*.ttf
- [ ] fons/cour.ttf "Courier New"
- [ ] fonts/digitalb.ttf "Digital-Bold, Thin"

**Comment by mobbyg** [comment]
I can do a little research for this. As I’m kind of a fonts hog. I’ll take a look at Blambot which has a lot of free comic book lettering fonts. As the theme to the original game was comic books (Issue 0-24).

 If I remember correctly, they have a noncommercial use license for those fonts. I think this project fits that description.

**Comment by nemerle** [comment]
The main problem is, we'd want to redistribute the ttf files along the rest of the data, and most font licenses are not very redistribution-friendly :disappointed:

**Comment by mobbyg** [comment]
According To his site, he’s open to talking about situations that he doesn’t list. So, I’ll just ask. What’s the worst he can say? No. So, we ask. 😀

**Comment by nemerle** [comment]
True, if there are any licensing trouble ( we're using BSD ), we might offer to move all data files ( including fonts ) to a slightly stricter licensed, separate SegsData repository.
There we could restrict redistribution-as-not-a-part-of-the-SEGS-project ? 
We might try looking around for other open source projects, and how they deal with such things

**Comment by mobbyg** [comment]
Ok, email sent. We’ll see what Nate says. In the meantime, I’ll also do some googling for other sources. 

I told him we would distribute the fonts in a binary app but still have them available in the source code since there will be folks who will want to compile too. You know... masochists!

**Comment by mobbyg** [comment]
Wow! Fast turn around on that email. 

So it’s $600 per font. Moving on.... 

I’ll start googling for stuff we can use.

**Comment by broxen** [comment]
Correct me if I'm wrong mobby, but I think these are ready? We can package in the client subdirectory and issue a PR.

**Comment by mobbyg** [comment]
We dot have a replacement for Montreal Heavy. The rest are ready. Just need to create a file with all the licenses, and we’re good to go!

**Comment by mobbyg** [comment]
Here is a canidate for replacing Montreal. 
[https://fontlibrary.org/en/font/montreal#Montreal-Bold](https://fontlibrary.org/en/font/montreal#Montreal-Bold)

**Comment by broxen** [comment]
We should probably move this over to https://github.com/Segs/Segs-Data and assign to Mobby 😁

**Comment by broxen** [comment]
Issue opened here:

https://github.com/Segs/Segs-Data/issues/1

I don't have perms to assign to Mobby. Closing this here. Feel free to reopen if I've erred in some way.
