### ISSUE TITLE
Documentation needs to be updated to reflect changes in the latest codebase.

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#272]
The READMEs need to be updated and reviewed for conformity with the latest changes to the server, settings.cfg, and dbtool. 

Also, this is a good opportunity to interface with the community and take feedback for streamlining/improving the docs for clarity and simplified use, especially for those without substantial coding experience.

There are several READMEs that need to be updated (these are complete in #418):
- [x] [./README.md](https://github.com/Segs/Segs/blob/7450f2abffc9effaf0cb7748d0568e746d1cc214/README.md) - the root directory readme and first thing users see when viewing our GitHub. This should be geared towards a developer audience looking to compile, BUT needs to provide quick links and clear instructions on where to find our installation and setup guides (and readme)
- [x] [./Projects/CoX/docs/README.md](https://github.com/Segs/Segs/blob/7450f2abffc9effaf0cb7748d0568e746d1cc214/Projects/CoX/docs/README.md) - This readme will appear in the SEGS program (out) directory. It should be geared towards setting up and running the server. It should be clear and concise, and focus on the most common methods for install (don't need to cover every possible configuration, just the most common ones)
- [x] [./Projects/CoX/Utilities/dbtool/README.md](https://github.com/Segs/Segs/blob/0901a04dd4c05d8d92d78ef43265d4d90da45b51/Projects/CoX/Utilities/dbtool/README.md) - an argument might be made for deleting this, but I think it may be valuable to have. At bare minimum we should leave it, and include a link inside to the setup readme in the program directory.
- [x] [./Projects/CoX/Utilities/piggtool/README.md](https://github.com/Segs/Segs/blob/b68162ac97d3b41aefc8f8dc0ba44484f3798682/Projects/CoX/Utilities/piggtool/README.md) - an argument might be made for deleting this as well, but I think it may be valuable to have, if it's updated with real instructions. At bare minimum we should leave it, and include a link inside to the setup readme in the program directory.

**Comment by broxen** [comment]
As part of this, we should update links to the new segs.io url.

Homepage: https://www.segs.io/ (Under construction! construction)
Forums: https://forum.segs.io/
Twitter: https://www.twitter.com/segscode
Wiki: https://github.com/Segs/Segs/wiki
Discord Server: https://discord.segs.io/
IRC: <irc://irc.segs.io/segs>

**Comment by ldilley** [comment]
An HTTP 301 forwarding rule is in place at the moment for "forum" and "www". If @nemerle can add VirtualHost directives in the webserver's config for "forum" (for the forums), "www" (for the Grav site), and for the base domain (which should just reference "www"/Grav home), then I can remove the forwarding rules and add A records in DNS instead. This would be good for appearance and consistency.

We may also need to regenerate new SSL certificates to add a wilcard (*.segs.io) for proper validation. Additionally, we can optionally make use of Cloudflare caching and protection if desired.

**Comment by broxen** [comment]
Updated the description with more detail

**Comment by broxen** [comment]
I'll jump on this next week as work clears up. Please add any comments or suggestions here otherwise I'll work off my own assumptions.

**Comment by broxen** [comment]
Going to incorporate SEGSAdmin into these documents, which should simplify them significantly.

**Comment by broxen** [comment]
This is nearly ready for merge. Just going to tweak a couple of URLs.
