### ISSUE TITLE
Authserver continues without eligible SQL driver loaded

### ISSUE THREAD

**Issue by ldilley** [Segs/Segs#275]
### Expected behavior
Bail if no eligible database driver is detected during startup.

### Actual behavior/symptoms
If no database driver (SQLite3) is detected on startup, authserver happily continues until connecting clients attempt to authenticate. After several unfruitful authentication attempts, the authserver process crashes and dumps a core.

### Steps to reproduce behavior/symptoms
Build and start authserver without SQL driver support.

### SEGS version
2033219

### Operating system
FreeBSD 11.1-RELEASE 64 bit

### C++ compiler and version
Clang 4.0.0

**Comment by broxen** [comment]
I think I can fix this by adding something like the following:
```
const QString type("QSQLITE");

if(!QSqlDatabase::isDriverAvailable(type))
{
    qCritical() << type << " database module not available.";
    return false;
}
```

**Comment by broxen** [comment]
Closing this as we're now checking for sql driver matching the named type in settings.cfg
