### ISSUE TITLE
Make use of QLoggingCategory to categorize various logging channels

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#277]
Right now we do not differentiate between various log sources, apart from using build-time only macro based selection.
We could make use of QLoggingCategory facilities, to enable a finer grained control over logging messages.
So instead of various qDebug()/qWarning() calls, we would have qCDebug(WorldSimulationCategory) and qCDebug(DatabaseCategory) etc.

**Comment by broxen** [comment]
Oh, so it sounds like they are still toggled during build. I'll look into it more. Maybe they can be toggled at runtime.

**Comment by nemerle** [comment]
Well, environment variables and logging configuration file are both run-time :)
And we can `setFilterRules(QSettings().value("LoggingFilter").toString())`

**Comment by broxen** [comment]
Oh perfect!

**Comment by broxen** [comment]
Implemented in #276, and I went all out, so hopefully it's comprehensive enough for future use cases. Closing this.
