### ISSUE TITLE
Make player fade-in speed configurable.

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#281]
This would require the `World::effectsStep` to read in a value from a configuration file.
If we wanted to change this depending on the map, then it would have to be in the per-map configuration, otherwise a central server config would suffice.

**Comment by broxen** [comment]
Starting with a central configuration in settings.cfg, I think this makes a great first issue.

**Comment by broxen** [comment]
A contributor looking to tackle this will want to reference `MapServer::ReadConfigAndRestart()` to see how we pull values from the settings file.

### Steps to complete
- [ ] Add config option to settings file for fade-in speed.
- [ ] Add defaults to Settings.cpp and Settings.h where appropriate
- [ ] Pull value for fade in speed from settings.cfg in `World::effectsStep(...)` but only if entity is fading.
- [ ] Replace `380.0f` in `animateValue(...)` with variable storing fade in speed.
