### ISSUE TITLE
Create a graphical admin tool for server setup and management.

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#285]
Create a graphical admin tool for server setup and management. (building off #33)

We can leverage QT, since it's already a dependency.

Should be able to:
- [x] Create a default maps folder structure
- [x] Define path to CoX client, and copy/extract PIGG and BIN files to server directory (see piggtool)
- [x] Clean up unused PIGG files
- [x] Display message if there is a newer server **release** available on GitHub.
- [x] Run/shutdown server
- [x] Set setting.cfg options using text fields and checkboxes
- [x] Create new player accounts (new functionality)
- [x]   Add a simple settings.cfg generator, which from local IP builds the proper file.
- [x] Reset databases to default (see: `./dbtool create -f`)

Future features (very low priority) that may require additional infrastructure:
- Provide means for updating server releases
- Show server stats (version, active connections, uptime, etc)
- Update database schemas after changes (new functionality)
- Ban player accounts (new functionality)
- Reset player passwords (how to handle this?)
- Delete Accounts and associated characters
- Rename characters (TheIncredibleHulk needs a new name but is offline)
- Ban based upon IP (for the jerk hackers)
- Maybe a simple MOTD editor to edit scripts/motd.smlx

**Comment by nemerle** [comment]
Maybe not a duplicate, but an extension-of :)

**Comment by broxen** [comment]
Does this overlap with SLAV? Maybe I should take a look at that.

**Comment by miles200** [comment]
I can start looking at the GUI part of this

**Comment by miles200** [comment]
Must this be in C++ or would a Python solution suffice?

**Comment by ldilley** [comment]
Good question, @miles200. This would preferably be a portable language, so Python meets that criteria. The resultant program must also possess all features outlined by broxen (and possibly others in the future.) Python can also leverage the Qt bindings provided by either [PyQt](https://riverbankcomputing.com/software/pyqt/intro) or [PySide](https://wiki.qt.io/PySide) as necessary (for GUI elements and such.)

**Comment by nemerle** [comment]
We want the tool to be distributable, python + Qt is good for the prototype, later on we will have to convert the tool to c++

**Comment by miles200** [comment]
We can probably use PyInstaller or PyEXE tools to distribute but never used before. I'll get on with a prototype for now, cheers all

**Comment by miles200** [comment]
I notice there's a ServerMonitor in the Segs/Utilities directory, could I make use of this for the start and stop auth server?

**Comment by miles200** [comment]
@broxen not sure I have access to tick off the bits that have been done

**Comment by miles200** [comment]
@broxen Hey, would you mind updating the check list to tick off "add a simple settings.cfg generator" and "set settings.cfg options" - these were added as part of PR 400 (don't think I can tick these off myself!) Thank you

**Comment by broxen** [comment]
Cleaned up the description and add some extra thoughts.

**Comment by miles200** [comment]
Looking good @broxen , first three items on the list in progress and will be the next PR

**Comment by miles200** [comment]
@broxen  This should be do-able, a couple of questions: 

Do we want to just display the 'latest' release and a link to the GitHub releases page (which would always be showing) or do we want to somehow do a comparison between current release installed and new release available and flag up that an update is available... I feel the latter may be overkill / too complicated for the time being!

**Comment by broxen** [comment]
Oh. Well, I haven't fully thought it through, but I was thinking that providing a simple "I'm up to date!" check would be a good substitute for automatically updating the server.

I think we definitely want to show what version is running, as it will help with any troubleshooting. Maybe a "Check for Updates" button that pings the atom file for an updated version and provides a link to the GitHub releases page if one is available?

**Comment by miles200** [comment]
Okay cool. Any ideas how I'd check for the existing version? We'd need to check the 'release' version.. do we include anything in the zip file that could provide this to SEGSAdmin?

**Comment by broxen** [comment]
Hrmm.. good question. Not sure there's actually a simple way to do this. Possible routes:
1. Hard code current release version, and update manually with each release.
2. Make AuthServer spit out version (and maybe other stats while you're at it) to some kind of local "log" to be read by SEGSAdmin
3. Use QT sockets to share information between the two apps? Will require more work on both apps, but may provide a framework for future web-apis?

I think option 1 is the best for now.

**Comment by miles200** [comment]
Thanks Broxen. I agree, let's keep it simple for now and go with option 1. (Just need to remember to update on each release 😄 )

Thanks,
Miles

**Comment by broxen** [comment]
No problem. 😁

I had to check QT docs because I thought there was a simple way to query an executable for it's version (which we set in AuthServer).. turns out there's no method for doing this cross platform.

We're manually updating version now, along with the MOTD.smlx too, so we'll just add SEGSAdmin to that mix.

**Comment by mobbyg** [comment]
I think we should change the logo used to the new logo that was created for us to keep it more in step with what we have on the web and have been using. 

[New Logo](https://i.imgur.com/tKJ0dJC.png?1)

**Comment by broxen** [comment]
Good idea Mobby

**Comment by broxen** [comment]
Do we have a version on a transparent background?

**Comment by miles200** [comment]
@mobbyg If you have a transparent version let me know, would look good! If not, I'll change to the one you linked for next PR

**Comment by mobbyg** [comment]
I thought that was the transparent one. I’ll check tonight when I get home.

**Comment by mobbyg** [comment]
![](https://imgur.com/a/ZVNYCtt)

**Comment by mobbyg** [comment]
[https://imgur.com/a/ZVNYCtt]()

**Comment by broxen** [comment]
I cleaned up the alpha and drop shadow a bit. Try this one:

Available here, or attached: http://doxy.segs.io/images/dump/logo/FINAL/segs-medallion.png

![segs-medallion](https://user-images.githubusercontent.com/10159505/39659363-8f615e64-4fdb-11e8-8a53-f67636c17d23.png)

**Comment by broxen** [comment]
Deeper drop shadow: http://doxy.segs.io/images/dump/logo/FINAL/segs-medallion.png

![segs-medallion](https://user-images.githubusercontent.com/10159505/39662185-aa6e9e60-5012-11e8-9fbd-ea136d514f20.png)
