### ISSUE TITLE
Lost Connection to DBserver - Character Creation

### ISSUE THREAD

**Issue by Taygai** [Segs/Segs#286]
### Expected behavior
When finishing creating a character entering the name, then enter paragon city, it should transition you into the game world. Instead this pops up

### Actual behavior/symptoms
Instead of transitioning to the game, it takes you back to the login screen saying Lost connection to DBserver

### Steps to reproduce behavior/symptoms
Attempt to create a character, sit on character creation for about 10-15 minutes, then attempt to enter paragon city.

### SEGS version
v0.4.2

### Operating system
Windows 10 64 bit

### C++ compiler and version
Not familiar with what this is

**Comment by broxen** [comment]
This is a duplicate of issue #71. We need to send idle packets during Character Creation.

**Comment by broxen** [comment]
This appears to be resolved in latest master branch.
