### ISSUE TITLE
Debug/info messages categorized as warnings 

### ISSUE THREAD

**Issue by JamesDW1** [Segs/Segs#292]
Just some lingering messages that still need to be changed to info/debug type:
`Warning : Reading map data from ./data/bin/ folder`
`Warning :  All map data read`
`Warning :  Postprocessing runtime data ..  Hashes filled`

**Comment by broxen** [comment]
These `qWarning() << "message..."` can be converted to `qInfo() << "message..."` with relative ease. This makes a great first-issue and will help clean up the server window output.
