### ISSUE TITLE
Replace the usages of QRegExp with QRegularExpression

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#303]
According to qt docs:

>The QRegularExpression class introduced in Qt 5 is a big improvement upon QRegExp, in terms of APIs offered, supported pattern syntax and speed of execution. The biggest difference is that QRegularExpression simply holds a regular expression, and it's not modified when a match is requested. Instead, a QRegularExpressionMatch object is returned, in order to check the result of a match and extract the captured substring.

This task will probably require reading some of the amazing qt docs, but the coding required should not be very complicated.

**Comment by broxen** [comment]
All instances of QRegExpr were mine, so I went ahead and cleaned them all up. Closing.
