### ISSUE TITLE
Warning : MapInstances/City_00_01/locations.lua is missing

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#308]
Server boot up looks for two Lua files to load and spits out a warning if they aren't found.
```
Warning : MapInstances/City_00_01/locations.lua is missing
```
We should make those qDebug instead of qWarning, and modify the message to let the end user know that defaults will be used instead, or that those files aren't necessary.

**Comment by cameron-justice** [comment]
So it seems that right now there is no formal implementation of the location_visited function inside locations.lua, but there is a formal implementation for the plaque_visited function inside plaques.lua.

This warning message appears when these files do not exist, but an attempt is made to load their contents into the scripting engine within MapInstance.cpp lines 78 and 79. Later in MapInstance.cpp, the location_visited and plaque_visited functions are called if their events are triggered. Both attempt to call their lua function equivalents, and if not possible they throw a warning. MapInstance::on_location_visited inlcludes the output message of the lua function call within its warning message, but MapInstance::on_plaque_visited does not (as far as I can tell, the val within on_plaque_visited is never used at all).

I'm opening a pull request that changes the qWarning to qDebug and edits the message, but it seems there are no defaults, and without the files warnings will be thrown, so this might be a further issue.
