### ISSUE TITLE
New dbtool doesn't add associated account row to segs_game database.

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#314]
New dbtool doesn't add associated account row to segs_game database for new accounts added with `adduser`

### Steps to reproduce behavior/symptoms
Build from latest master. Build completely new database files. Add new account using `adduser` command.

### Results
Client crashes on `assert(!"Unknown event encountered in dispatch.");` and `Debug   : GameEntryError: getCharsFromDb error!`

### Resolution
Manually adding associated row in `segs_game` account table resolves the issue.

**Comment by broxen** [comment]
Per @nemerle, this will be resolved by the server during account login. I'll leave this open until that patch goes through.

**Comment by nemerle** [comment]
Closed by #322
