### ISSUE TITLE
Migrate relevant issues/milestones from redmine.

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#32]
When this and #31 task are done, we can remove redmine from project's front page.

**Comment by ldilley** [comment]
All milestones and open issues tied to them have been migrated from the Redmine site. I am not sure if you want to migrate any closed issues for documentation/historical purposes. Let me know the issue IDs and I can take care of that if so.

**Comment by nemerle** [comment]
No, let the closed ones be. Also - great job, thanks :smile:
