### ISSUE TITLE
Blocked Accounts Crash Map Server

### ISSUE THREAD

**Issue by GitSomeTab** [Segs/Segs#329]
### Expected behavior
When attempting to log in with any "bad" account the server should not crash.
### Actual behavior/symptoms
When attempting to log in with account (user) 1 and (pass) 1 you're provided with a "blocked account" type message. 
The output file lists this: 
```
(3280|10868) User 1 trying to login from 192.168.86.198.
(3280|8744) Connection closed
(3280|1240) Client disconnected without a valid login attempt. Old client ?
```
then the user can log in with an unblocked account. upon loading atlas park it crashed the map server. All of the clients received "Map server disconnected". 
### Steps to reproduce behavior/symptoms

1. Log in successfully with a new or existing account
2. Attempt to log in with 1 / 1
3. Log in successfully with a new or existing account (which is not already logged in)

### SEGS version
0.4.3
### Operating system
Windows 10 Pro
### C++ compiler and version
MinGW 5.3.0 32bit for C++

**Comment by GitSomeTab** [comment]
[1accountcrash.txt](https://github.com/Segs/Segs/files/1913826/1accountcrash.txt)
I forgot my output.log.

**Comment by broxen** [comment]
We can close this now that #334 is closed as well.
