### ISSUE TITLE
Create a database initialization/server management tool

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#33]
This tool should:
Given a database ip and admin login/pass: 
- Create segsdb user
- create segs databases ( according to current sql files)
- create database tables ( also using provided sql files)

Given a server address:
- Set server IP's and ports correctly
- If database info is available, put it into server configuration file.

Things to consider:
- Database schema updates.

**Comment by broxen** [comment]
An update... dbtool covers all of this except, port and IP setting, and Schema Updates.

**Comment by broxen** [comment]
I'm going to close this so we can follow development progress in #285
