### ISSUE TITLE
Server does not appear to run `void MapInstance::start()` at all?

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#335]
### Issue Summary and Steps to Reproduce
Server does not appear to run `void MapInstance::start()` at all? Consequently, none of these functions fire:
```
m_world_update_timer.reset(new SEGSTimer(this,(void *)World_Update_Timer,world_update_interval,false)); // world simulation ticks
m_resend_timer.reset(new SEGSTimer(this,(void *)State_Transmit_Timer,resend_interval,false)); // state broadcast ticks
m_session_store.create_reaping_timer(this,Session_Reaper_Timer,reaping_interval); // session cleaning
```

### Steps to Test
Add `qWarning() << "MapInstance Start";` to the first line to test.
```
void MapInstance::start()
{
    qWarning() << "MapInstance Start";
//...
```

### SEGS build
3bfadac

**Comment by nemerle** [comment]
The map instances are started for the first client that tries to connect to the given instance.
the logic goes like this:
1. in GameHandler::on_map_req `ExpectMapClientRequest` is sent to map server
2. MapServer::on_expect_client does `map_manager().get_template(request_data.m_map_name)` and `tpl->get_instance()`
3. MapTemplate::get_instance spins the instance up

**Comment by broxen** [comment]
hrm.. I can't get my `qWarning() << "MapInstance Start";` code to ever fire.. maybe I'm overlooking something?

**Comment by broxen** [comment]
Whatever this issue was, it's not longer happening. Maybe it was a mirage from late night coding =P
