### ISSUE TITLE
Adjust starting spawn location to Outbreak, since Outbreak is new starting zone.

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#337]
### Issue Summary
New changes to MapInstance in latest build spawns new characters in Outbreak, but current spawn coordinates are set to Atlas Park spawn location. Should be reconfigured for Outbreak map.

As the current spawn location puts you off map, you immediately fall into the void, thus I'm tagging this a bug.

### Proposed Fix(es)
- Reset spawn coordinates to outbreak starting location
- OR make starting map and spawn location configurable in settings.cfg
- OR pull starting spawn locations from map geo data `_playerspawn` (spawners shown in this video: https://www.youtube.com/watch?v=uWyyFQDG9b4 at 0:00:07)

In my opinion, default spawn logic should be:

1. Spawn at locations set in map geo data
2. Unless overridden in ~settings.cfg~ map specific lua files: `MapInstances/City_00_01/settings.lua`

### Segs Build
3bfadac

**Comment by nemerle** [comment]
Yup, this is the correct approach, although those spawn locations should be not in settings.cfg, but map specific lua files :) `MapInstances/City_00_01/settings.lua`

**Comment by broxen** [comment]
#375 only addresses this temporarily.

It looks like SceneGraph will be the future place for this? So perhaps a long term solution will rely on further work there?

**Comment by broxen** [comment]
Resolved by Nems npc and scenegraph merged PR
