### ISSUE TITLE
Raise default jump height slightly

### ISSUE THREAD

**Issue by ldilley** [Segs/Segs#341]
The default jump height value seems too low compared to the original game. This can be altered manually with `/setjumpheight <N>` on a per character session basis, but should be set to a standard default globally.

**Comment by broxen** [comment]
We can probably pull this data directly from attrib_serializers.cpp

**Comment by eos428** [comment]
In Entity.h, m_jump_height is initialized as 1.0f. Modifying this value should alter the default jump height value.

**Comment by ldilley** [comment]
Somewhere in the range of 2.0 - 2.5 seems appropriate going by look and feel. I do remember being able to clear the Atlas Park fence without the hurdle talent from fitness.
