### ISSUE TITLE
dbtool should pull config from settings.cfg file

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#361]
### Proposed Behavior
Currently dbtool assumes we're using sqlite, and has the paths for each database hardcoded. We should pull these values from the settings.cfg, and leverage the Settings class from the SEGS parent project.

Tasks to complete this improvement:
- [ ] Leverage Settings class from SEGS parent project.
- [ ] Pull file names and relative paths from settings.cfg, for example: `CharacterDatabase\db_name   = segs_game`
- [ ] Pull currently selected Database driver from settings.cfg

**Comment by dracc** [comment]
I've started working on a fix.
Settings class is used.
File names (or, well, db_name) is pulled from settings.
Database driver is pulled from settings, and if not QSQLITE, host, port, username and password too.

I'll file a PR soon.

**Comment by broxen** [comment]
Closed by #263
