### ISSUE TITLE
Minimap State needs to store array and serialize to database

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#371]
Opening your map you'll see the "fog of war" or shadow over the map tiles. Moving around uncovers or reveals these map tiles. We need to store the array of tiles per map, and serialize them to the database in some form. Possibly under some kind of `PlayerProgress` struct that will include contact lists, clues, badges and souvenirs in the future.

`MapInstance::on_minimap_state(...)` in MapInstance is a place to start. That event has the following variables:
- `uint32_t tile_idx;` - the index of the tile being uncovered

Steps to complete this feature request:
- [ ] Get current map_idx for use in minimap_state
- [ ] Store tile idx in nested array grouped by map_idx
- [ ] Store array in PlayerData (maybe new struct called PlayerProgress? Is it necessary?)
- [ ] Serialize minimap_state_array to database for cross-session persistence
- [ ] Determine which opcode is used to receive map state upon map transfer or login (aka, how does the client know what parts of the map are revealed?)
- [ ] Serialize array from database back to array stored in PlayerData
- [ ] Send updated array to client upon log in, or map transfer based upon map_idx

Feel free to discuss or add additional features in the comments below. I'll add relevant info here.

**Comment by broxen** [comment]
I believe Banks(mlarney) started on this. I don't know the current status.

**Comment by broxen** [comment]
Our Packet 22 might look something like this in serializeTo()
```
    bs.sendPackedBits(1, 1);
    bs.sendBit(1, is_opaque);
    bs.sendPackedBits(1, num_cells);
    if(num_cells)
        bs.sendPackedBitsArray(num_cells, cells_arr);
```
where
```
    bool          is_opaque = false; // is_opaque only in mission maps where the fog is black
    uint32_t    num_cells;             // number of cells being updated (fog removed) 
    std::vector<bool> cells_arr;    // array of "is_visible" flags. Could be expressed as 32x32 array instead
```

**Comment by Frozyn** [comment]
I'll take on this issue. I have the first 3 steps complete so far, in the middle of the 4th step. Unfortunately, it doesn't seem like we can make use of std::bitset due to issues with cereal, so I plan on storing the data in the following way:

`"Progress": {
    "VisibleMapTiles": // or "MapTiles"
        {
                "12": [
                    false,
                    true,
                    false,
                    ...
                ]
        }
}`

Each map having 1024 possible values, indices whose values are true will relate to revealed map tile ids.

**Comment by broxen** [comment]
Seems like a good way to go.
