### ISSUE TITLE
Database: Normalization?

### ISSUE THREAD

**Issue by dracc** [Segs/Segs#382]
### Expected behavior
The chardb->accounts table (and the rest of the databases) ought to be in BCNF.
### Actual behavior/symptoms
It is not. id is not the same as account_id, but one id can only point to one account_id (or vice versa), or we have data breaches coming up.

### Suggested solution
Remove the column 'id' from chardb->accounts as it is seldom (never?) used.
There might be more fields breaking BCNF, but this is the only one I've come in contact with so far.

**Comment by broxen** [comment]
This relates to #381
