### ISSUE TITLE
New SEGSAdmin app cannot execute dbtool or authserver on Linux

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#391]
### Steps to reproduce
- Open SEGSAdmin
- Click on *CreateDatabases* button ... fails to open dbtool
- Click on *Add User Account* button ... fails to open dbtool
- Click on *Start Auth Server* button ... fails to open authserver

### Proposed solution
Not sure. Perhaps it's a linux filepath issue? Or permissions issue? Will need to test further.

### SEGS version and Build Info
Segs commit 17c664b
Qt 5.9.4 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.1 20180130 (Red Hat 7.3.1-2)) on "xcb"
OS: Fedora 27 (Workstation Edition) [linux version 4.16.5-200.fc27.x86_64]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

**Comment by broxen** [comment]
Tagging @miles200 as he's been working on this.

**Comment by miles200** [comment]
Thanks @broxen , I'll take a look this evening, I tested the linux side to this on a Ubuntu build, will grab a copy of Fedora and see what I can find

**Comment by miles200** [comment]
@broxen This should now be fixed in #396 , I gave it a quick whirl on Fedora and seemed okay, let me know? 😄
