### ISSUE TITLE
Create and maintain "develop" branch

### ISSUE THREAD

**Issue by ldilley** [Segs/Segs#399]
With the impending release of 0.5, this issue is a reminder to split a `develop` branch from `master` per previous discussion. Use the repository architecture discussed in [this article](http://nvie.com/posts/a-successful-git-branching-model/) as a guide. Basically, `master` should no longer contain new untested code from PR merges. The `develop` branch will be used for unvetted code. In the near future, any clones of the `master` branch should _ideally_ be expected to compile/link successfully and run with some degree of stability.

**Comment by broxen** [comment]
This makes sense.

**Comment by nemerle** [comment]
Done.
