### ISSUE TITLE
SEGS Admin future features. Ban, Delete, Edit Accounts and more!

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#413]
## Summary
Now that #408 is merged, let's track some future features for the SEGS Admin tool (very low priority) that may require additional infrastructure:

Builds off #404 (closed) and #33 

## Proposed Features
- [x] Clean up UI (see proposed layout below)
- [x] Add player fade-in to settings.cfg creation and (proposed) settings dialog
- [x] Merge Start and Stop Server buttons into a single dual-state button/toggle and Relabel Start/Stop button to "Start Server" or "Stop Server" Dependent upon state.
- [x] Put Settings options into their own class and Dialog (subclass of QDialog) with a save button.
- [x] Add monochromatic symbolic icons to buttons to provide visual clarity and GUI-goodness to UX
- [x] Provide means for updating server releases
- [x] Maybe a simple MOTD editor to edit scripts/motd.smlx

### Features to consider
- Use https://github.com/alex-spataru/QSimpleUpdater framework to serve all our update needs

### Abandoned or Moved Features
- Moved: ~~Provide button to launch game client, perhaps with options for fullscreen/windowed~~ this belongs in SLAV #40 
- Moved: ~Update database schemas after changes (new functionality via dbtool)~ - follow this in Add ability to update databases through dbtool #447

#### *Moved RPC related features to #436*
- Moved: ~Show server stats (version, active connections, uptime, etc)~
- Moved: ~Ban player accounts (new functionality) #33~
- Moved: ~Delete Accounts and associated characters #33~
- Moved: ~Reset player passwords (how to handle this?) #33~
- Moved: ~Rename characters (TheIncredibleHulk needs a new name but is offline) #33~
- Moved: ~Ban based upon IP (for the jerk hackers) #33~

## UI Mockups
![segsadmin](https://user-images.githubusercontent.com/10159505/40417893-b8f8d65e-5e35-11e8-87c0-9eea91c1ef0f.png)

**Comment by broxen** [comment]
For some of these database edits (bans, name edits, reset passwords, etc). How to handle while the server is running?

**Comment by nemerle** [comment]
This is the work for the jsonrpc, methinks

**Comment by broxen** [comment]
Cleaned this up and separated out the RPC related tasks

**Comment by miles200** [comment]
@broxen Everything on this issue is now implemented in SEGSAdmin. Did you want to keep open for future stuff or should we close this one off and create a new one if anything else comes up?

**Comment by broxen** [comment]
Let's close this when your PR merges

**Comment by broxen** [comment]
This was completed in #645
