### ISSUE TITLE
SEGSAdmin produces setGeometry warning on startup

### ISSUE THREAD

**Issue by JamesDW1** [Segs/Segs#414]
### Expected behavior
SEGSAdmin runs without warning

### Actual behavior/symptoms
Running SEGSAdmin produces this warning on startup:
`setGeometry: Unable to set geometry 764x849+8+31 on QWidgetWindow/'SEGSAdminToolWindow'. Resulting geometry:  764x822+8+31 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 596x822, maximum size: 764x16777215).`

### Steps to reproduce behavior/symptoms
Run SEGSAdmin and the warning should display in console. SEGSAdmin still runs normally (afaik) despite the warning.

### SEGS version
Latest master
### Operating system
Windows 10

**Comment by miles200** [comment]
@JamesDW1 Hey James, what screen resolution are you using please? I can only replicate this with a low resolution of around 1024 x 768. It seems SEGSAdmin is struggling to fit to the size constraints due to a low resolution perhaps?

**Comment by miles200** [comment]
@nemerle @broxen hey, @JamesDW1 reported yesterday that the resize I did didn't make much of a difference, any suggestions on how to proceed for users with low resolutions? Few ideas:

a) Start maximized for low resolutions?
b) Re-design UI so it can be vertically smaller, so should fit on lower resolutions better?
