### ISSUE TITLE
SQL_ERROR upon using SEGSAdmin to create an account with an existing username

### ISSUE THREAD

**Issue by JamesDW1** [Segs/Segs#432]
### Steps to reproduce behavior/symptoms
1. Run SEGSAdmin
2. In "Add New User" create an account and enter an already existing account's username (entries for password and access level shouldn't matter) 
3. Should produce: SQL_ERROR: QSqlError("19", "Unable to fetch row", "UNIQUE constraint failed: accounts.username") 
### SEGS version
Latest master
### Operating system
Windows 10

Maybe SEGSAdmin should prompt the user that an account with the username already exists and to select another?

**Comment by miles200** [comment]
Thanks James. 
@broxen @nemerle What are your thoughts? I know there was some discussion in the discord, and Nem you said this is more for JsonRPC stuff in the future. 

I know @dracc said he may look into the error messages that dbtool throws? 

Should we keep this issue open or close it?

Thanks,
Miles

**Comment by dracc** [comment]
I've started on a little something for this, yes.

**Comment by broxen** [comment]
Let's keep this open for now. It seems like many users will run into this. We may be able to provide a temporary solution until something more concrete is developed

**Comment by miles200** [comment]
Thoughts on a 'temporary' solution:

Create a QStringList with some kind of mapping between an error 'ID' output from dbtool and output the user friendly error that ID is mapped to within SEGSAdmin (longer solution as both dbtool and SEGSAdmin dev required)

Or...

Tweak error messages somehow within dbtool (quicker solution as no SEGSAdmin dev required)

**Comment by dracc** [comment]
@miles200 I could make sure the exit value of dbtool varies with whatever error is received. Then you only do a compare with ints (faster than strings) and output an error message depending on what int was returned from dbtool. :slightly_smiling_face:

**Comment by miles200** [comment]
Sorry @dracc just another thought... I haven't looked at the dbtool code in detail but is it possible to compile a list of possible errors? We can then map ID's to them and possibly document somewhere for reference and ensure we're aligned on both our ends 😄

**Comment by dracc** [comment]
@miles200 Well, there are a few lists available. PostgreSQL [here](https://www.postgresql.org/docs/9.4/static/errcodes-appendix.html). Not all are really relevant to catch though, as most would be bigger problems than ones we can easily dodge/take care of in our tools.

**Comment by miles200** [comment]
@nemerle thanks Nem. So go with the 2nd option then and just output nicer looking DB errors which SEGSAdmin will capture in it's console output?

**Comment by nemerle** [comment]
I think that would be the best path, since later on we will get proper rpc communication.
