### ISSUE TITLE
Unable to create users while service is running

### ISSUE THREAD

**Issue by Otlichno** [Segs/Segs#435]
I am running current master branch build and when I go to add users it tells me the table is locked. This will be an issue when attempting to run production (Public) environments.

Repro steps:
Start authserver
run dbtool adduser -l username -p password

Response:
Table is locked failed to add user (Paraphrasing)

**Comment by dracc** [comment]
This is intriguing. When/Where/Why do we lock the AuthDB.Accounts table?

**Comment by miles200** [comment]
@dracc Is it an SQLITE issue where the file is in use by authserver?

**Comment by dracc** [comment]
@miles200 It would seem so, yes.
I have not tested with PostgreSQL though, but I doubt it differs.

**Comment by broxen** [comment]
While SQLite will not allow this, other db engines will.

That said, a move to RPC for SEGSAdmin and/or a new web-ui for account creation will resolve this issue. I'm flagging as a bug, and adding to 0.6.0 milestone.

**Comment by broxen** [comment]
This can now be resolved using the RPC framework in place.

**Comment by dracc** [comment]
Why was this issue closed? I can't find anything in the commit log indicating that the functionality to create users in a SQLite db while the server is running is in place - thus it is still an issue even if you and I are not currently affected.

**Comment by Otlichno** [comment]
Broxen's comment https://github.com/Segs/Segs/issues/435#issuecomment-434901667 says RPC is now in place

**Comment by broxen** [comment]
The framework is in place, but the hooks for adding/editing/banning accounts don't exist yet. We'll need someone to tackle these before this is resolved

**Comment by miles200** [comment]
I'll pick this up

**Comment by miles200** [comment]
I've implemented this locally
