### ISSUE TITLE
MySQL Create is creating skin_color as signed int(11)

### ISSUE THREAD

**Issue by Otlichno** [Segs/Segs#439]
When using MySQL Server and creating the tables with DBTool, the skin_color column in the costumes table is getting created as a signed int(11), this causes issues when users try to create characters. 

Expected results:
dbtool to create the column as an unsigned int(11)

**Comment by broxen** [comment]
This is a great first issue.

A contributor looking to resolve this will modify the MySQL script in `/Projects/CoX/Data/mysql` and expand the data field size for skin_color.

As we don't have a lot of MySQL users at this point, and the setup is somewhat manual, I don't feel we need an upgrade path added to dbtool at this time. Kicking that can down the road further 😛

**Comment by broxen** [comment]
Whoops. Just realized @dracc is fixing this in #440
