### ISSUE TITLE
Remove user `Documents` location from README docs as it doesn't have permissions

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#442]
README docs contain advice to install SEGS to the user's `Documents` folder but some users are experiencing permissions issues with this location. We should change the docs to recommend installing SEGS to the user's `c:\` drive ONLY.

**Edit: below was removed because I had it wrong**
~~README docs contain advice to install SEGS to `c:\SEGS` but some users may not have the proper permissions to setup/run the server from this location. We should remove the docs and recommend installing SEGS to the user's `Documents` folder ONLY.~~

Great first issue, have at it boys and girls!

**Comment by miles200** [comment]
@broxen Actually, it was the other way around 😄 It **worked** in c:\segs but not in documents
