### ISSUE TITLE
Add ability to update databases through dbtool

### ISSUE THREAD

**Issue by miles200** [Segs/Segs#447]
We should add the ability to update / upgrade the segs databases through dbtool. Now that users are running public servers, we want to avoid users having to create -f and overwriting the existing databases. 

@dracc @broxen Have some ideas on how this can be achieved.

**Comment by broxen** [comment]
A rough roadmap to achieving this:
- [ ] Implement `-upgrade` flag in dbtool
- [ ] Check hardcoded version value against versions table of each database
- [ ] Further, check versions against serialized data fields in characters table
- [ ] In SEGS AuthServer: If version is lower than latest, recommend upgrade using dbtool and `-upgrade` flag
- [ ] In SEGSAdmin: provide upgrade database schema button.
- [ ] Provide update scripts or hard coded update paths for each iterative database schema change.
- [ ] Run update scripts in order until schema matches latest version, providing feedback and error reporting in case of failure.
- [ ] Important!!! Apply database schema updates to database COPY and verify success before overwriting original database. And/or maybe also save a copy of last database as backup. This ensures data retention in case of failure or corruption during schema updates.

**Comment by dracc** [comment]
I've put a few thoughts through this, and seeing as the authserver already perform checks regarding database versions, wouldn't it make sense to put the upgrade functionality inside authserver instead?

That way it will be more seamless for the users and we wont have to rewrite code which already more or less exists.

**Comment by nemerle** [comment]
Well we're trying to recreate the good old `rake db:migrate`.
I don't think we should incorporate this into the main executable, 'dbtool' is 'the' place for this.

**Comment by broxen** [comment]
Per conversation with @nemerle on Discord:

> the db itself should be easy, and the cereal serialization is versioned already, just need to handle changes gracefully, allowing clean-ish loads in old versions:
```cpp
template<class Archive>
void load(Archive &ar, SomeType &val, int version)
{
    if(version==current_version)
        do_current_stuff;
    else
        migrate_from_old_version(ar,val,version)
}
```
> now, we can store 'old' versions of the structures, and write step-by-step migrations `migrate( SomeType_v1 &src, SomeType_v2 &target)`, or rewrite the migrate_from_old_version each time, to match new version's fields

**Comment by broxen** [comment]
Marking this Release Blocker for v7, as we desperately need this functionality.
