### ISSUE TITLE
Change to SEGSAdmin to elevate to Administrator on startup

### ISSUE THREAD

**Issue by miles200** [Segs/Segs#448]
Several users have reported issues when running piggtool where their segs directory is in a C:\Users or Program Files directory. Piggtool encounters the following error:

```
Checking CoX client is correct version
Correct client version found
Copying Files...
File Copy Complete
Extracting Pigg Files...
Failed to read "C:/Program"
QFSFileEngine::open: No file name specified
failed to open source file ""
```

There may be a way to elevate to Administrator access on SEGSAdmin startup. [URL for reference](http://www.antonioborondo.com/2014/11/25/how-to-grant-administrator-privileges-to-windows-applications-with-cmake/)

Needs testing to determine whether SEGSAdmin or piggtool needs the administrator access...

**Comment by broxen** [comment]
piggtool will need the access.

I think that asking users to install to their C:\ is perhaps a simpler resolution for the underlying issue this attempts to address.

That said, I'm not _against_ this proposal, just not sure what the response might be to UAC requirements from one of our CLI tools.

**Comment by miles200** [comment]
Thanks @broxen  I'm happy with that and happy to close this issue. Do we need to document in readme or was that already done as part of the issue you raised?

**Comment by broxen** [comment]
I went ahead and updated the readme in #457. Feel free to close. Thanks miles, you rock!

**Comment by miles200** [comment]
Closing, cheers @broxen
