### ISSUE TITLE
Update/Re-Write CoX-Auth to give it an address book

### ISSUE THREAD

**Issue by mobbyg** [Segs/Segs#449]
With all the new servers going up for test, it’s a pain to have to open CoX-Auth and change the IP or FQDN every time. 

Plus in the future, it’ll be more a pain when they are fully playable. If we have access to the source for it, we should add a simple address book. Maybe let users add like 10 servers. 

If we don’t have the code, maybe someone would be willing to take a crack at it?

**Comment by miles200** [comment]
Interesting, I wonder how we would change this without the source code... Does anyone know if you can point CoX.exe to a specific IP using a -target parameter or something?

**Comment by broxen** [comment]
The CoX client saves the IP in the system registry. It should be as simple as changing that.

**Comment by miles200** [comment]
Perhaps then a custom application (SEGSAddressBook or something)... Which allows users to add servers and then 'apply' a server which updates the registry setting... Probably something which will do in the interim until we have our custom launcher / SLAV working?

**Comment by miles200** [comment]
Should we leave this to SLAV then?

**Comment by miles200** [comment]
@nemerle @broxen Any further thoughts on this? Should we close this and add to the SLAV roadmap?

**Comment by broxen** [comment]
Yes. This seems best for SLAV.

**Comment by broxen** [comment]
Closing this in favor of #676 since SLAV is the new focus.
