### ISSUE TITLE
Server is looking for case-sensitive CHUNKS bin.

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#469]
Server is looking for case-sensitive CHUNKS bin. It probably has no issue on Windows since windows ignores case in filenames.

```
Critical: Node "swr_trialroom_main_1461&" 
can't find member "object_library/Villain_Lairs/sewers/elements/CHUNKS/swr_chunks_01"
```

**Comment by broxen** [comment]
`/data/object_library/Villain_Lairs/sewers/elements/CHUNKS/Chunks.geo` is the true filepath

**Comment by dracc** [comment]
Making file opening a case-insensitive process seems hard.
What about making `piggtool` look for "`CHUNKS.bin`" and renaming it?

**Comment by nemerle** [comment]
Maybe we should consider adding a post-processing pass to the piggtool, then it will go through all the unpacked client files, and apply any and all fixes we've found ?

**Comment by dracc** [comment]
That sounds like a good plan @nemerle.
Is there a list of known fixes?

**Comment by nemerle** [comment]
Well, the file name case is one thing, there is a bunch of typo-bugs in sequencers, but we might want to leave that be ( until we have fully working SLAV, which can patch client-side files ? )
