### ISSUE TITLE
Server-Client character synchronization failure!

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#474]
### Steps to Reproduce
1. Log in to account with existing characters
2. Delete Existing Character. Do not log out, or log into another character.
3. Create a new character in the same slot where you deleted one previously.
4. Receive Assertion and server crash
```
ACE_ASSERT: file /Segs/Projects/CoX/Servers/GameServer/GameHandler.cpp, line 406 assertion failed for 'selected_slot->m_name == ev->m_char_name || !"Server-Client character synchronization failure!"'.Aborting...
```

**Comment by dracc** [comment]
It probably doesn't matter, but what database driver did you use?

**Comment by broxen** [comment]
Sqlite
