### ISSUE TITLE
Create a 'global' SEGSEvent registry

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#478]
It must be possible to serialize SEGSEvents from/to memory to enable interesting functionality that is to come.  [Deterministic bug replication/unit testing](https://github.com/Segs/Segs/wiki/EventProcessor-state-replication,-bugs-and-You) for one. 
Now, when we have a blob of binary data, finding a proper serialization function requires a 'lookup' by some 'key' value. So, every SEGSEvent type has to register a creation/serialization function. (IMHO best approach would be to continue in our use of cereal, by providing both JSON and BIN archive overrides )

Now, this will likely require some tricky bits of coding, since a full SEGSEvent registry will be needed by `component_runner`, and thus all SEGSEvents, even those residing in static libraries, need to be registered. One solution:
* add cmake macro to collect an SEGSEvent ( creating a list of all SEGSEvents in the process )
* based on fully populated list of SEGSEvents, use cmake to generate a cpp file with a function that will register each event type
* create a static lib from generated cpp file, and link it to all executables that require a populated eent registry, and call the main registration function on app startup.

**Comment by broxen** [comment]
This is complete?

**Comment by nemerle** [comment]
Mostly, the event registry is global, but filling it requires calling specific functions. But we can do it 'later' :)
