### ISSUE TITLE
Fill up Defined Map Datas vector in DataHelpers

### ISSUE THREAD

**Issue by eos428** [Segs/Segs#483]
Related to #475.

At the moment, this is our g_defined_map_datas vector in DataHelpers.cpp, which stores all the Map information:

> static const std::vector<MapData> g_defined_map_datas =
> {
>     {0, "City_00_01", "maps/city_zones/city_00_01/city_00_01.txt", "Outbreak"},
>     {1, "City_01_01", "maps/city_zones/city_01_01/city_01_01.txt", "Atlas Park"},
>     {23, "City_23_01", "maps/city_zones/city_23_01/city_23_01.txt", "Galaxy City"}
> };

Here's an explanation of all the parameters in this vector, in order from left to right:
1. m_map_idx. The map... index. Currently unused and we could modify the code to use this, but that's not for this PR.
2. m_map_name. This is what the server checks against a character's EntityData's CurrentMap in order to load up the map.
3. m_map_path. The path the server looks for in order to load up the maps (from maps.bin AFAIK). The convention is pretty easy to follow, so I don't feel the need to explain too much.
4. m_display_name. The name of the map displayed to players.

What we should do, is to fill up this vector with information of all the other areas. Basically whatever City_02_01 is, City_03_01, etc etc. The convention is pretty easy to follow, so I think this would be a good first issue.

**Comment by dracc** [comment]
Do we know why Galaxy City got index number 23? According to my extracted files, it's actually `City_01_03`

```sh
$ ls data/geobin/maps/City_Zones/City_01_03
 city_01_03.bin  'Galaxy City is in this dir.bin'
```

**Comment by eos428** [comment]
I think it was some placeholder code put back then that puts Galaxy City on 23 lol so I just followed it

**Comment by nemerle** [comment]
The id's are not actually used anywhere by the client, it just had those values hardcoded as map-ids.
As for the proper mappings, they can be read from unpacked texts/English/menuMessages.ms
