### ISSUE TITLE
Add Double XP/XP Multiplier to SEGSAdmin

### ISSUE THREAD

**Issue by mobbyg** [Segs/Segs#497]
Those of us that played a lot remember getting the email notices and in game notices about Double XP weekends and the the like. This would be a nice setting to have in SEGSAdmin that allows the server admin to do this easily. Here’s my idea: 

* A tick box to activate the feature. 
* When active, start and end date fields become active to set the length of time. 
* A multiplier box with a default of 2.

Thoughts?

**Comment by miles200** [comment]
Sounds good to me, I'll hold off adding to SEGSAdmin for now until we have some support for it in game

**Comment by broxen** [comment]
This actually seems relatively easy to do so I'm marking `good first issue`
- Add to settings_template.cfg
- Add to SEGSAdmin (from settings.cfg)
- Add `grantXP(ent, amt)` method to CharacterHelpers and apply XP Modifier there pulling from settings.cfg

**Comment by Frozyn** [comment]
I'll take on this issue. I plan on adding a new Modifiers page to SEGSAdmin to contain these fields.
