### ISSUE TITLE
Pull per class values for BaseAttribs and MaxAttribs from classes.bin

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#502]
Per-class values for BaseAttribs (Starting attribute values) and MaxAttribs exist in classes.bin

We're already pulling some of this info for use in `m_max_attribs`, but we should be utilizing all of those values where appropriate (for example: starting HP and End, and starting maxHP and maxEnd)

**To Complete:**
- Start with `m_max_attribs` and work your way down the rabbit hole. =D
- Create method for resetting those values based upon level (so when we level up a character we can `getMaxAttribs(ent.m_char);` and set those values to their new max)

One could use bintool to extract a json file of classes.bin for reference.

**Comment by broxen** [comment]
As part of this, we can set these in `finalizeLevel()` so that they are automatically adjusted upon `/levelup`

**Comment by cyanpill** [comment]
I've started on this, and I have a function that sets the max HP based on class and level
`    m_max_attribs.m_HitPoints = data.m_player_classes[entclass].m_AttribMaxTable[0].m_HitPoints[m_char_data.m_combat_level];
`
However, Max end is always 100, and I'm not sure what starting hp should even be. Or is supposed to be MaxHp and MaxMaxHp?

**Comment by broxen** [comment]
I believe it should be MaxHP, MaxEnd. (https://paragonwiki.com/wiki/Hit_Points) I assume they are in the classes.bin, though to be honest it's been a few months since I looked.

Although End never changes, I would still pull the value from the bins in finalizeLevel() as NPCs may have different End depending upon level.

**Comment by cyanpill** [comment]
I hadn't thought about NPCs, so I'll keep poking at it. Fun fact, the HPmax data in classes.bin is about 0.3% lower than the values on the wiki. I thought I was checking a level lower, but no it's the data.

**Comment by broxen** [comment]
Could be our client version? Might have been adjusted later

**Comment by broxen** [comment]
Eventually, we'll probably want to expose all of this data to some sort of JSON or cfg file, where server admins can override the defaults. In that way we can "recreate" I24 data for damage/hp etc
