### ISSUE TITLE
/Fly comand not working and stuck and fly gives a weird push to the left 

### ISSUE THREAD

**Issue by BunnyLivesMatter** [Segs/Segs#504]
When i go into segs server/client and try to fly. Comand /fly i cant move the animations work and sound to but 
i just stay at one point also when i type /fly and then /stuck it starts pushing me to the left/and backwards .
if i leave the /fly and type /stuck it jumps me to a difrent position so that works withouth using fly.
i also tried /hascontrolid and /fullupdate it had no effect.

Video Youtube link:  https://www.youtube.com/watch?v=sv9TSInVcow
one more thing in the video you dont see that am flying/not working  only the /stuck and /fly being yoused.

Segs Version 0.5.0

Segs Server View info -

Debug   : Sending Server MOTD to das

[log.slashcommand]Debug   : "Toggling fly"

[log.slashcommand]Debug   : "stuck" : "Resetting location to default spawn (-89,-1.4782e-5,151)"

[log.slashcommand]Debug   : "stuck" : "Resetting location to default spawn (-89,-1.4782e-5,151)"

[log.slashcommand]Debug   : "Toggling fly"

Operating system -
intel core i5-7300HQ 2.50Ghz 7th gen
Nvidia Gefore Gtx 1050
windows 10

**Comment by broxen** [comment]
This is a byproduct of the way we're circumventing Server Authority for movement

Follow progress in #94
