### ISSUE TITLE
Update relevant guides for SEGSAdmin SSL DLL requirement

### ISSUE THREAD

**Issue by ldilley** [Segs/Segs#509]
With the merger of PR #508, `SEGSAdmin.exe` now makes use of crypto functions defined in the following dynamic link libraries provided by OpenSSL:
* libeay32.dll
* ssleay32.dll

These libraries must be available from the `SEGSAdmin.exe` path at runtime. They can be installed per https://wiki.openssl.org/index.php/Binaries from https://slproweb.com/products/Win32OpenSSL.html. Please select a 1.0.x version considering the SSLeay moniker was renamed in 1.1.x. Both DLLs can simply be copied to the `SEGSAdmin.exe` path after the OpenSSL 1.0.x installer completes.

Any relevant build and install guides should be updated to reflect the above. Lastly, when producing any SEGSAdmin binary releases targeting the Windows platform, it is permissible (licensing requirements are already fulfilled) and advised to include these DLLs in the distribution. This would save end users some work.

**Comment by miles200** [comment]
I will pick this up if not done before 0.6.0 but will leave for now in case a non-programmer or someone wants to pick up as first issue
