### ISSUE TITLE
Update SEGSAdmin version number to 0.6.0 in line with release 

### ISSUE THREAD

**Issue by miles200** [Segs/Segs#510]
This needs to be done prior to 0.6.0 release so SEGSAdmin doesn’t alert a new version for downloads after release

**Comment by broxen** [comment]
Just curious if there's a way to pull this from Version.h in the future.

**Comment by nemerle** [comment]
Include and use Version.h ?
This might require rendering the version string in the splash screen, but Qt should make it quite possible.

**Comment by broxen** [comment]
We're showing the version string on the splash screen anyway, so it sounds like a win win

**Comment by miles200** [comment]
Oops didn’t realise we had version.h yes this sounds very sensible, I’ll update
