### ISSUE TITLE
Trading and Trade Windows

### ISSUE THREAD

**Issue by deciton666** [Segs/Segs#521]
Sub-task for the "[Meta] Future Enhancements (and Opcodes to implement) #519" issue.

This task is used to track the implementation of the trading system and its commands.

**Comment by broxen** [comment]
To complete this task, you'll need the following information:
- You'll need to create a `/trade` slash command (the client sends this to the server when you right-click and select trade with someone)
- You'll need to implement the following opcodes:

### Send Trade Offer
Send a `uint32_t` for db_id of the trader, and a QString of the trader's name. Check to see if character is already considering a trade, team or SG invite.
**Client-side:**
```
void receiveTradeOffer(DbPacket *pak)
{
    uint32_t db_id = my_pakGetBits(pak, 32);
    QString trader_name = my_pakGetString(pak);

    if ( teamOfferingDbId )
    {
        COH_ASSERT(!"Recieved a TradeOffer while we were already considering one!  Server-side check gone awry?", 0);
    }
    else
    {
        teamOfferingDbId = db_id;
        dialogStd(0, translatingPrintf("OfferTrade", trader_name), 0, 0, sendTradeAccept, sendTradeDecline, 1);
    }
}
```

### Send Trade Init
Send db_id of the trading partner (tradee)
**Client-side:**
```
void recieveTradeInit(DbPacket *pak)
{
    uint32_t db_id = my_pakGetPackedBits(pak, 1);
    trade_init(db_id);   // just show gui window with db_id
}
```

### Send Trade Cancel
Send a QString message about why it was canceled
**Client-side:**
```
void receiveTradeCancel(DbPacket *pak)
{
    QString msg = my_pakGetString(pak);
    trade_cancel(msg);
}
```

### Send Trade Success
Works the same way as Cancel
**Client-side:**
```
void receiveTradeSuccess(DbPacket *pak)
{
    QString msg = my_pakGetString(pak);
    addToChatMsgs(msg, INFO_USER_ERROR, 0);
    closeTradeWindow();   // close trade window
}
```

### Receive Trade Accept
Receive and handle SlashCommand from the server `/trade_accept {tradee_name} {tradee_db_id} {trader_db_id} {trader_name}` -- you can look a team_accept and team_decline for an example.

### Receive Trade Decline
Receive and handle SlashCommand from the server `/trade_decline {tradee_name} {tradee_db_id} {trader_name}` -- you can look a team_accept and team_decline for an example.

### Trade Update
Looks like it just updates all parties after the trade.
**Client-side:**
```
void trade_receiveUpdate(DbPacket *pak)
{
    int i;
    int j;

    my_pakGetPackedBits(pak, 1);
    g_trade.aAccepted = my_pakGetPackedBits(pak, 1);
    g_trade.bAccepted = my_pakGetPackedBits(pak, 1);
    g_trade.aInfluence = my_pakGetPackedBits(pak, 1);
    g_trade.bInfluence = my_pakGetPackedBits(pak, 1);
    g_trade.bNumSpec = my_pakGetPackedBits(pak, 1);
    g_trade.bNumInsp = my_pakGetPackedBits(pak, 1);
    trade_clear(1);
    for ( i = 0; i < g_trade.bNumSpec; ++i )
    {
        g_trade.bSpec[i].m_template = entReceivePower(pak, &g_ppPowerSets);
        g_trade.bSpec[i].iLevel = my_pakGetPackedBits(pak, 5);
        g_trade.bSpec[i].iNumCombines = my_pakGetPackedBits(pak, 2);
    }
    for ( j = 0; j <g_trade.bNumInsp; ++j )
    {
        g_trade.bInsp[j] = entReceivePower(pak, &g_ppPowerSets);
    }
}
```

**Comment by deciton666** [comment]
It is now possible to trade influence between characters, but not inspirations nor enhancements.
I need to find a way to add inspirations and enhancements to a character so that we have something to trade.

Known bugs:
* Trade state is not cleaned up if one of the players logs out while considering the trade offer.

**Comment by broxen** [comment]
My PR #495 will add powers, enhancements and inspirations. I believe it's ready for merge. Let me check with Nem and get back to you.

**Comment by supermandrew** [comment]
Was trading inspirations even possible in CoH?  I remember that they could be gifted through the right-click menu, but I don't remember if they could be traded or not..

**Comment by broxen** [comment]
At some point yes. I distinctly remember dropping resurgence on people

**Comment by broxen** [comment]
@deciton666 just a heads up that #495 merged, so you should be able to test trading inspirations or enhancements

**Comment by deciton666** [comment]
Wonderful. I will restructure the code similar to the FriendshipService as I think that that is a better design. No need to have trading be part of Entity.
