### ISSUE TITLE
Implement Map Transfers

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#527]
## Summary
We need to implement MapTransfers (client calls these MapXfers)

Currently we can load multiple maps (by manually changing player maps in the DB). Plus, we have the `/mapmenu` command, which brings up the mapxfer window (MapXferList), but it's not populated with anything, so does nothing.

To complete this Issue, the following features should be implemented:
### Features to Completion
- [ ] Implement MapTransfers (svr->client pkt 11)
- [ ] Implement MapTransferWait (svr->client pkt 10)
- [ ] Implement `/mapmove {idx}` command so we can actually move =)
- [ ] Instigate MapXfer when zoning through tunnels or hazard doors in the war walls

### Bonus Features
- Populate MapXferList with a list of major zones, and figure out how to make clicking on those zone names fire a MapXfer.
- Door Animation Start (client->svr pkt 52)
- Door Animation Exit (client->svr pkt 53)
- Populate Monorail destination window by marrying `MapInstance::on_enter_door()`, MapXferList, and `MapInstance::on_location_visited` to display MapXferList when you're near the monorail door.
- Fill additional information from maps.bin #475

**Comment by broxen** [comment]
Per an earlier discussion with Nem in #136 
> re: Map change
> The current design/thought is like this:
> - each game server is connected to a map server router
> - map server router manages N map server processes
> - each map server process has methods `initializeMap(name)` and `shutDown(redirectTo)`,  `transferTargetReady(name,target)`, `getTransferToken(for_player)`
> - when Map server starts, it is in 'idle' state, and no players can connect to it
> - when Map server receives `initializeMap(name)` command, it will load the required map data, and notify > the map server router it is ready by `mapServerReady(id,name,...)`
> - when Map server router receives `mapServerReady` it registers the server in the routing map for that name, and notify all other map servers that
> - when a request is made to enter a specific map, the router will search in the routing maps, and if all servers in the map are `busy` (high number of players ), it will try to initialize one of the 'idle' maps to a specific map. When the target map is ready, the map server router will send `transferTargetReady`, when source map server receives `transferTargetReady` it will request a transfer token for each player waiting on the transfer list. when a transfer token is received, player finally gets a `mapTransfer` packet from it's source map server.

**Comment by Magentah** [comment]
I'll take a look at this, although I'm not sure if I'd be able to do animation/door stuff, as I don't have an nvidia gpu at the moment.
