### ISSUE TITLE
Can't create character if DB is MYSQL

### ISSUE THREAD

**Issue by Otlichno** [Segs/Segs#533]
### Expected behavior
Be able to create a character with latest checkout

### Actual behavior/symptoms
Client hangs and crashes after finish character complete and server logs:
Debug   : SQL_ERROR: QSqlError("1406", "QMYSQL3: Unable to execute statement", "Data too long for column 'chardata' at row 1")
### Steps to reproduce behavior/symptoms
Update to latest checkout
Have database engine be MySQL
Create character all the way through
### SEGS version
0.5.0
### Operating system
CentOS
### C++ compiler and version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
### Other relevant information
I also tried recreating the db using dbtool, but did not work

**Comment by broxen** [comment]
Resolved in #535
