### ISSUE TITLE
Properly award new powers and additional inspiration slots on level up

### ISSUE THREAD

**Issue by eos428** [Segs/Segs#545]
We already have /levelup so the actual level up process is at least done.

The things that should be done to solve this issue should be:
- Check if character's exp is enough to level up (should be handled by client already?), but this might be for another issue if needed
- On each level up, check if the character level is enough to award additional inspiration slots
- On each level up, check if the character level reaches the amount required to be granted certain powers

**Comment by broxen** [comment]
So some insight into the client side here:

The client already checks for these things, but on the server side we need to verify (as server has authority). There's also a couple of opcodes thrown back to the server when running `/levelup` (possibly not every time?) so we'll need to handle those as well.

Another thing you may want to add to this: we can adjust max-attribs based upon level. It may rely upon #502 to get per-class by level data.

I'll be more helpful with information after I've had some hands-on over the next couple of days.

**Comment by broxen** [comment]
A note on this: we're not currently handling adding new empty enhancement slots to powers correctly, and the server just forces every power to have 3 empty enhancement slots

**Comment by cyanpill** [comment]
We should add something like "trained level" to keep track while you are training. [According to the wiki it was "security level"](https://paragonwiki.com/wiki/Level)
