### ISSUE TITLE
Apply PowerType, Range, Accuracy, and TargetType when using powers

### ISSUE THREAD

**Issue by eos428** [Segs/Segs#546]
Pending input from broxen, but we should apply these variables that are taken from the associated power template (stored on MapServerData) when using powers.

This is related to #541 since it changes how we take in the power data from MapServerData, and in case I am unavailable to do this one, please don't work on this until that PR is done.

**Comment by broxen** [comment]
Thank you for tackling these issues @eos428!

Using binConverter on powers.bin will give you a nice JSON file that will help identify how to best use the data contained in the powers array.

As practical applications of this, in usePower() we can check power by type to determine whether or not it's an attack or buff, etc. Also we can check target for range, and for target type to see if valid. Then using accuracy determine whether or not we "hit".

This will move us much closer to "real" power usage. As this is waiting on #541, please just let me know how I can help when you start to dive in.

Looking forward to it!!
