### ISSUE TITLE
Store Powers in a container so that they can be Queued and Recharged

### ISSUE THREAD

**Issue by eos428** [Segs/Segs#547]
Again pending input from broxen, but here's how I see the problem:

- When a character tries to activate a power, the power is put into the queue, pending activation
- The power must wait until its assorted activation period is over before being casted
- After the 1st power is casted, the power is put into another queue in which it is being recharged.

My suggestion on how to solve this:
- Create two vectors referencing powers ActivatedPowersQueue and RechargingPowersQueue
- ActivatedPowersQueue will handle the timer of only the 1st power inside it (unless you want to cast multiple powers at the same time), and will remove the 1st power after being casted. Then the 2nd power onwards will be put 1 idx in front and so on.
- RechargingPowersQueue stores all powers that are casted and is pending recharge. In this queue, all powers' recharge timer will be handled at the same time.

If a character tries to cast a power that is already inside one of these vectors, then we cannot cast the assorted power.

**Comment by broxen** [comment]
Again, thank you eoS! I think you have this pretty much nailed, with a few tweaks:

- NPCs and Critters will need these as well, so they should reside in Entity obj.
- There are two vectors in Entity obj now.
  - `std::vector<CharacterPower *> m_queued_powers;`
  - `std::vector<CharacterPower *> m_recharging_powers;`
- We don't necessarily need to use pointers here, just store the power specs (pset_idx, pow_idx) and relevant timer or state.
- Powers with Activation timer of 0 **might** fire simultaneous to other powers. Needs research.
- Some powers do not have recharge timers and can be used again immediately.
- In the game, you could add "ready" (recharged) powers to the activation queue multiple times.

The server sends these queues to the client in EntitiesResponse.cpp:
```
    qCDebug(logPowers) << "NumQueuedPowers:" << e->m_queued_powers.size();
    bs.StorePackedBits(4, e->m_queued_powers.size()); // Count all active powers
    for(const CharacterPower *pow : e->m_queued_powers)
    {
        qCDebug(logPowers) << "  QueuedPower:" << pow->m_name << pow->m_index;
        bs.StoreBits(1, pow->m_active_state_change);
        if(pow->m_active_state_change)
        {
            storePowerSpec(pow->m_power_info.m_pset_idx, pow->m_index, bs);
            bs.StorePackedBits(1, pow->m_activation_state);
        }
    }

    qCDebug(logPowers) << "NumRechargingTimers:" << e->m_recharging_powers.size();
    bs.StorePackedBits(1, e->m_recharging_powers.size());
    for(const CharacterPower *pow : e->m_recharging_powers)
    {
        qCDebug(logPowers) << "  RechargeCountdown:" << pow->m_timer_updated << pow->m_recharge_time;
        bs.StoreBits(1, pow->m_timer_updated);
        if(pow->m_timer_updated)
        {
            storePowerSpec(pow->m_power_info.m_pset_idx, pow->m_index, bs);
            bs.StoreFloat(pow->m_recharge_time);
        }
    }
```
