### ISSUE TITLE
Organize output folder! aka Compile all Unit Tests and Utilities to subdirectories

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#556]
## Summary
To clean up the clutter in the server output directory. This proposes we compile all unit tests and utilities to sub-directories.

### Proposed file structure
- :open_file_folder: *compile output folder*
  - :open_file_folder: data
  - :open_file_folder: default_templates
    - :open_file_folder: default_dbs
    - settings_template.cfg
  - :open_file_folder: logs
  - :open_file_folder: maps
  - :open_file_folder: scripts
  - :open_file_folder: utilities
    - :open_file_folder: mapviewer_data
    - :open_file_folder: unit-tests
      - AuthDBEventRegistry
      - AuthEventRegistry
      - CommonEventRegistry
      - CRUDPEventRegistry
      - event_gen
      - FriendshipEventRegistry
      - FriendshipServiceFunctions
      - GameDBEventRegistry
      - GameEventRegistry
      - ManifestBuilder
      - MapEventRegistry
    - AuthExerciser
    - binConverter
    - dbtool
    - mapviewer
    - piggtool
    - SEGS.exe
    - slav
    - texConverter
  - authserver
  - SEGSAdmin
  - segs.db
  - segs_game.db
  - settings.cfg
  - output.log
  - README.md

**Comment by broxen** [comment]
@nemerle your thoughts?

**Comment by broxen** [comment]
@miles200 this will impact SEGSAdmin as well. Your thoughts?

**Comment by miles200** [comment]
Sorry @broxen only just seen you tagged me here... I'm happy with this, just would need to ensure that SEGSAdmin looks at the alternative path for utilising dbtool / piggtool etc...

**Comment by broxen** [comment]
I've completed this in my dbtool upgrade branch.
