### ISSUE TITLE
Programatically add logging categories to SEGSAdmin

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#564]
## Summary
Currently we have to add new log categories to the settings.cfg manually. Perhaps we can add them programatically by reading from Logging.h, or by reading from the settings_template.cfg

Alternatively, we can continue adding manually with new releases.

**Comment by miles200** [comment]
This is fixed / changed locally. 

Following functions updated to read logging keys from `settings_template.cfg` 

- Read Config File
- UI Elements in Logging Tab (Settings)
- Generate Default Config File
- Save changes to Config file.

Will be in my next PR.
