### ISSUE TITLE
Link Reaping During Zone Transfers Causes Timeout 

### ISSUE THREAD

**Issue by JamesDW1** [Segs/Segs#565]
### Expected behavior
Transferring zones occurs seamlessly 
### Actual behavior/symptoms
Upon attempting to switch zones through any means, a loading screen appears and after a few moments, the player is sent back to the title screen with the prompt, "Lost connection to server" 
### Steps to reproduce behavior/symptoms
1. From inside the game, use any means to transfer zones
2. Player will be greeted by a loading screen, and at this point links are reaped
3. After a few moments the player should be sent back to the title screen
### SEGS version
Lastest commit
### Operating system
Windows 10
### C++ compiler and version
QT Creator

**Comment by broxen** [comment]
If possible, I'd like to squeeze this into v0.6.0

**Comment by nemerle** [comment]
Agreed

**Comment by Magentah** [comment]
@JamesDW1 How long does the loading screen show, I assume without the loading bar moving? I'm unable to replicate the issue and can't find anywhere obvious that would cause reaping, so it may be due to the timeout being too short.

**Comment by Magentah** [comment]
@broxen Can we close this issue as well, as it seems like it was just related to ports?

**Comment by broxen** [comment]
Let's leave open, as the ports have not resolved James issue in #troubleshooting

But I'm going to push out to v7 unless anyone can replicate.
