### ISSUE TITLE
Starting powers/inspirations configured in settings.cfg

### ISSUE THREAD

**Issue by cyanpill** [Segs/Segs#572]
### For Issue #525 
starting **powers** to be configured via settings.cfg
starting **inspirations** to be configured via settings.cfg

### Possible additions:
starting **level** to be configured via settings.cfg
starting **inf** to be configured via settings.cfg

In World of Warcraft emulation, there are "fun servers" where people will start at max level, or at some lower level but with exp gain turned off. This is mostly for PvP, but also sometimes challenges of what can be done at a set level. Starting at a higher level would come with starting money. The defaults would be set to level 1 and 0 inf of course.

### Discounted possibilities
enhancements and salvage and other things that haven't been added. Won't be as useful.

**Comment by cyanpill** [comment]
I have to code for the first two, want to see if adding level and inf is good too :+1: 

Also, I want to note that inspirations weren't spawned on the character, you got them from the tutorial: https://paragonwiki.com/wiki/Sergeant_Hicks But it's something people might want anyways.

**Comment by broxen** [comment]
Awesome!

I think the more customization the better. Give users the tools to create!

**Comment by miles200** [comment]
@cyanpill @broxen 

Hey both, 
What do I need to change in SEGSAdmin for this? Do we need UI controls for selecting starting powers etc... or should I just be changing the settings.cfg generation code to include the new fields? 

Thanks
Miles

**Comment by cyanpill** [comment]
I think it's a little early to choose powers from a list of whatever... just include the new fields.

**Comment by broxen** [comment]
Yeah for now I wouldn't worry about it.

As a low priority item, you could always lookup those powersets by borrowing (or leveraging) the server code in MapData, and then provide a selection tree/list.

Also, I agree about the inspirations, but I think providing server admins the option to spawn w/whatever is a great feature.

**Comment by miles200** [comment]
Thanks both. I'll log an issue to pick up
