### ISSUE TITLE
Empty m_keybind_profiles vector does not fail gracefully.

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#575]
### Summary
Sometimes Keybind profiles do not load and server will assert due to vector out of range, aka Empty m_keybind_profiles vector does not fail gracefully.

Here, in `getCurrentKeybinds()` of keybind_definitions.cpp
```cpp
    qCDebug(logKeybinds) << "Could not get Current Keybinds. Returning first keybind profile.";
    return m_keybind_profiles.at(0).KeybindArr;  // <--- fails here
```

Previously this was not an issue, because we would initialize keybinds from MapServerData. This is no longer possible because NetStructures cannot access `g_GlobalMapServer`

It does not happen consistently, but appears to happen most often when the client has been left open between server sessions. It always fails at the same line.

**Comment by dracc** [comment]
Would the best solution be to hardcode a keybinding in `getCurrentKeybinds()` or to reconnect NetStructures with `g_GlobalMapServer`?

**Comment by broxen** [comment]
I think the aim is to keep NetStructures insulated from MapServer. So we should build and send a default keybind profile if the array comes back empty
