### ISSUE TITLE
Remove Server Name in Settings.cfg aka SEGSAdmin not registering Server Name

### ISSUE THREAD

**Issue by HeraldOfOmega** [Segs/Segs#593]
## Summary
Server Name in settings.cfg is not currently used by the server. Further, the client will not accept custom server names. Currently `server_name` setting is useless.

Server Name's purpose is to eventually provide a customizable and unique identifier to facilitate promotion of private servers in the *Segs Launcher and Verifier* (SLAV).

### Proposal
I'm prepurposing @HeraldOfOmega's original bug report to propose we rename server name to something to make it clear that it's use is internal ONLY, and that it will not change the selectable server name in the Client's server select screen.

This is a simple tasks of refactoring and updating any relevant files + SEGSAdmin. As such I'm marking `good-first-issue` 

### Steps to complete
- [ ] ~~Rename all instances of `server_name` something more clear: perhaps `internal_server_name`~~ remove `server_name` altogether for now.
- [ ] Update Settings.cpp, Settings.h and settings_template.cfg to reflect this change
- [ ] Update SEGSAdmin to reflect this change. ~~Perhaps add a note to further clarify that this is an internally used server identifier, and will not change the client's server selection screen.~~

*edited by broxen on Tues, Sept 25*

### Expected behavior
SEGSAdmin.exe would create a server of the name provided when you click [Generate Config File]

### Actual behavior/symptoms
Server is named "Freedom"

### Steps to reproduce behavior/symptoms
Create a new install of SEGS, run SEGSAdmin.exe

### SEGS version
0.5.0

### Operating system
Windows 7

### C++ compiler and version
unknown

### Other relevant information
Virtue was better than Freedom! :1st_place_medal: 
jk

**Comment by broxen** [comment]
Thank you so much for submitting this Bug Report!

Unfortunately this is a limitation of the client (the server names are hardcoded)

Since fixing this isn't a possibility at this time, I'm marking this wontfix, but perhaps we can revise the documentation and/or SEGSAdmin to make it clear that servername is used internally ONLY.

**Comment by broxen** [comment]
Yeah, that echos my thoughts. In a possible custom-client future, we can actually leverage this in the server selection screen, but for now it's just confusing.

**Comment by broxen** [comment]
OK Updated.

I could be compelled to suggest removing `server_name` altogether if there's no foreseeable use for it internally.

**Comment by miles200** [comment]
Did we decide on renaming versus removing server_name?

**Comment by broxen** [comment]
The only utility for this is for a future SLAV server list. I'd say we just remove it until there's an actual need. It's not complex to add again later.

**Comment by broxen** [comment]
Closed in #658
