### ISSUE TITLE
Base HP is changed after logging out

### ISSUE THREAD

**Issue by HeraldOfOmega** [Segs/Segs#603]
### Expected behavior
Base HP would stay the same after creating your character.

### Actual behavior/symptoms
Made a tanker and Base HP was 115.
Logging out and back in changes Base HP to 50.

### Steps to reproduce behavior/symptoms
Create any character, log out and back in.

### SEGS version
0.5.0 +

### Operating system
Windows 7

### C++ compiler and version
MinGW 53_32

**Comment by cyanpill** [comment]
This was the case for a a few days, but should be fixed as of today's PR. you'll have to get the most recent version from GIT, and recompile.

**Comment by broxen** [comment]
@cyanpill has got it. This is fixed on latest develop as of Oct 2nd. Marking as v0.5.0 and closing.

Thanks for reporting @HeraldOfOmega!
