### ISSUE TITLE
Melee attacks have zero range aka Movement is not synced with Server

### ISSUE THREAD

**Issue by HeraldOfOmega** [Segs/Segs#605]
### Expected behavior
Melee attacks would perform like ranged attacks provided you were close enough.

### Actual behavior/symptoms
All melee powers give the message "out of range" even when as close as possible to a target.

### Steps to reproduce behavior/symptoms
Create a character with a melee power, use melee power on Officer Flint or police drone.

### SEGS version
0.5.x +

### Operating system
Windows 7

### C++ compiler and version
mingw53_32

**Comment by broxen** [comment]
Great catch!

This is actually related to movement #94 . The server and client do not agree on your player's position. Range checks for powers are actually working properly. You can test this by standing next to Officer Flint and typing `/loc` to get your position, then use `/moveto` to move your player to those coordinates. Melee will work properly.

**Comment by broxen** [comment]
Moving to v7

**Comment by broxen** [comment]
Segs/SegsEngine will resolve this. Closing.
