### ISSUE TITLE
Inform users that they don't need all logs enabled at all times

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#607]
## Summary
Discussion in discord demonstrated that some users run their servers with all logs toggled on all the time. While this probably isn't harmful, it does produce hundreds of thousands of lines of log output on any given server, and makes troubleshooting issues difficult.

### Proposal
We should add a message to SEGSAdmin's logs window letting users know that log messages only need to be set to true for debugging specific issues. We can enable logMapEvents and logSlashCommands by default, if we must, but the rest can be false.

**Comment by Stitchified** [comment]
Could always add a message to the Readme too, cover two bases that way.

**Comment by broxen** [comment]
Good idea @Stitchified
