### ISSUE TITLE
cmake fails on libACE.so citing undefined reference to aio_suspend and other aio functions

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#61]
I'm running into an issue compiling the latest from github. Cmake fails in both QTCreator and Visual Studio Code on Linux (Fedora 26)
```
[~]$ uname -a Linux fedora.workgroup 4.12.12-300.fc26.x86_64 #1 SMP Mon Sep 11 17:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Attempted with both ACE lib preinstalled and by compiling. Worked in Sept, but that was several commits ago. Partial output:
```
/home/broxen/CoX/SEGS/build/3rd_party/built/lib/libACE.so: undefined reference to `aio_suspend'
/home/broxen/CoX/SEGS/build/3rd_party/built/lib/libACE.so: undefined reference to `aio_write'
/home/broxen/CoX/SEGS/build/3rd_party/built/lib/libACE.so: undefined reference to `aio_error'
/home/broxen/CoX/SEGS/build/3rd_party/built/lib/libACE.so: undefined reference to `aio_read'
/home/broxen/CoX/SEGS/build/3rd_party/built/lib/libACE.so: undefined reference to `aio_return'
/home/broxen/CoX/SEGS/build/3rd_party/built/lib/libACE.so: undefined reference to `aio_cancel'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Projects/CoX/Utilities/MapViewer/CMakeFiles/mapviewer.dir/build.make:308: ../out/mapviewer] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:835: Projects/CoX/Utilities/MapViewer/CMakeFiles/mapviewer.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
13:38:40: The process "/usr/bin/cmake" exited with code 2.
```

QTCreator compile output attached (txt file)
[consoleoutput-10-16-17.txt](https://github.com/Segs/Segs/files/1389042/consoleoutput-10-16-17.txt)

**Comment by nemerle** [comment]
This looks to me like 'librt' library is not getting linked.
Could You try putting this
```cmake
if(UNIX AND NOT APPLE)
    set_property(TARGET ace_IMP APPEND PROPERTY INTERFACE_LINK_LIBRARIES rt)
endif()
```
at the end of ```Segs/3rd_party/ExternalProject_ACE.cmake``` file ?

**Comment by broxen** [comment]
Tried this, but saw no discernible change.

New output attached (looks the same to me)
[consoleoutput-10-16-17.txt](https://github.com/Segs/Segs/files/1389377/consoleoutput-10-16-17.txt)

**Comment by nemerle** [comment]
I'll install FC26 on a virtual machine and see what's going on

**Comment by nemerle** [comment]
Ok, I cannot reproduce it for basic build steps i've taken:
* installed a fresh FC26 on virtualbox
* updated it to the current versions,
* installed qtcreator using ``` yum install qt-devel qt-doc qt-creator ```
* fixed ```slav``` build, since it was requiring qt 5.8, and FC26 has 5.7

_Now I'm building mapviewer, will update this comment with result_

**Comment by broxen** [comment]
I did similar to you:
- installed QTCreator
- installed SDL2-devel
- downloaded QT5.8 and pointed QTCreator at the newer lib

Worked previously, but maybe I updated something and messed it up.

I'll try to switch to updates-testing and reinstall. I'll post my results here.

**Comment by broxen** [comment]
I finally got this to compile. Thank you for all of your assistance Nemerle.

Ultimately, I had to clone the git again, switch to the updates-testing repo and update QT5, QT Creator, and CMake, but it did the trick.

**Comment by nemerle** [comment]
Great :)
Happy hacking then ;)
