### ISSUE TITLE
Powers can be activated while still recharging

### ISSUE THREAD

**Issue by HeraldOfOmega** [Segs/Segs#613]
### Expected behavior
Powers cannot activate until recharged

### Actual behavior/symptoms
Powers can be activated at any stage of recharge

### Steps to reproduce behavior/symptoms
Create a character with a ranged attack
Spam ranged attacks on Officer Flint.

### SEGS version
0.5.x

### Operating system
Windows 7

### C++ compiler and version
mingw53_32

### Other Notes
Didn't expect this to be possible on the client

**Comment by broxen** [comment]
Will be resolved by #688 and should make it in v7
