### ISSUE TITLE
Unexpected warning in client console

### ISSUE THREAD

**Issue by cyanpill** [Segs/Segs#621]
As mentioned in https://github.com/Segs/Segs/pull/606#issuecomment-427656973  I noticed that my client's console has the following output every time I connect to a new mapserver. Happens on localhost, and on Dracc's public server. Same buffer size every time. Wine 3.0.3
```
Auth:Sending password... ok                                           (0.15)
Auth:Requesting server list... 
ok                                     (0.14)
Connecting to DbServer 79.136.3.230:7002 (UDP) cookie: 620befd6..ok   (0.32)
Connecting to mapserver 79.136.3.230:7004 (UDP) cookie: 620c10c0..Error calling setsockopt, ending socket buffer size is not what we told it! (131072!=262144)
Error calling setsockopt, ending socket buffer size is not what we told it! (131072!=262144)
    (0.43)
GEO: Cant find .geo file object_library/Omni/EncounterSpawns/City_00_01/City_00_01.geo

```

**Comment by broxen** [comment]
Looking on the interwebs, this might relate to wine, but I'm not getting it locally on wine3.14 on Fedora

https://ubuntuforums.org/archive/index.php/t-627634.html

**Comment by cyanpill** [comment]
This warning doesn't interfere with playing, so we might have to just call it a long standing bug with CoX and ignore it. I will try other versions of wine later to see if that changes anything.

**Comment by nemerle** [comment]
Not a bug in CoX, but a 'bug' in wine. Client tries to resize the UDP buffers to 256K, but wine does not like that. This has 0 impact on the gameplay, You need larger buffers when sending/receiving large/frequent packets.
