### ISSUE TITLE
Client crashes sporadically on windows

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#63]
When running CoX on Windows 10, the client will crash randomly. I can't attribute the crash to any specific event(s)

Let me know what kind of log/information you may need.

**Comment by nemerle** [comment]
Well, the boring procedure would be: 
* login, create a char, enter map, don't press anything, wait for a while -> Crash Y/N
* login, create a char, enter map, only move using WASD -> Crash Y/N
* login, create a char, enter map, move using WASD + Mouse -> Crash Y/N

**Comment by broxen** [comment]
Will test on Windows over the weekend.

On Linux, I left the client idling overnight and all day today (18+ hrs) with no crashes. Then, for about 20min, I proceeded to jump around using the mouse, WASD and a combo of both; no crashes. So I'm confident it's an issue with my Windows build.

More info to follow... Thanks nemerle.

**Comment by nemerle** [comment]
Good work broxen, this was a great way of testing server link stability as well :smile:

**Comment by nemerle** [comment]
As for windows stability issues, just to verify, the client crashes after entering game with:
* preexisting character 
* new character ( entering map through character creation )
* both

**Comment by broxen** [comment]
Both.

Upon first logging in with a new character immediately, and then again after logging in, but with a delay the second time as I was able to run around for a bit.

Will try this again after recompiling from Master.

Also, this is all natively on Windows 10, but I'll try to load up a VirtualBox and test on Windows XP or Win7.

**Comment by broxen** [comment]
Today, I can't even get into Atlas Park, as the client keeps crashing during loading.

Also I'm having trouble capturing the export logs. Is there a way to enable client logging? Shouldn't the server output a log of this console information as well? output.log only has the loading info.

![screenshot 24](https://user-images.githubusercontent.com/10159505/31856858-f7542586-b681-11e7-87b9-e025a0a6101e.png)
![screenshot 25](https://user-images.githubusercontent.com/10159505/31856859-f77003dc-b681-11e7-9dc5-cddbfed9e9de.png)
![screenshot 26](https://user-images.githubusercontent.com/10159505/31856860-f7897740-b681-11e7-8d23-80fbddd14da3.png)
![screenshot 27](https://user-images.githubusercontent.com/10159505/31856861-f7a3b8f8-b681-11e7-9b1d-9c534c010e62.png)

**Comment by nemerle** [comment]
well, this looks like an regression ( i.e I broke something )  will look into it.

**Comment by nemerle** [comment]
I think the latest few commits solved the problem with entering the game with pre-created char, please check and let me know ?

**Comment by broxen** [comment]
Latest build. Clean SQLite database. Win 10

1. Logged into new account. Created char. Entered world. Ran around. Logged out.
2. Logged back in, selected pre-existing char. Entered world. Char is invisible. Can't exit client. Can't Alt+F4. Have to CTRL+ALT+DEL.

Console has output:
```
sending message to client 03679cd8
Received cookie confirm a00e3a1 - 0
not all bits were consumed
```
 
3. Restarting authserver and relaunching client resolved the issue with visibility, but I still couldn't exit the client normally and I continued to get a lot of `not all bits were consumed` messages.
4. Created new account, created new character, logged in but character was invisible, able to log out normally.
5. Logged in again on new account, character still invisible, able to log out normally.
6. Logged in again on old account, character still invisible, able to log out normally.

Some Notes:
- Running around didn't seem to crash the client. 
- Logging in didn't seem to crash the client. 
- Logging into a old char didn't crash the client. 
- Clicking on things (plaques, doors) didn't crash the client.
- Logging out didn't crash the server as in #30 so maybe that bug's been squashed.

Screenshots:
![screenshot 38](https://user-images.githubusercontent.com/10159505/31957667-5e184d00-b8a4-11e7-876e-d9639999f824.png)
![screenshot 41](https://user-images.githubusercontent.com/10159505/31957806-c1bbd1c4-b8a4-11e7-9556-0ec126994e34.png)

**Comment by nemerle** [comment]
Hmm, that visibility hiccups are worrying.

As for Win10, have you tired running the client with various compatibility modes ?

**Comment by broxen** [comment]
Yes, still experiencing the visibility issues. Though they are intermittent. Restarting the server seems to help resolve all issues temporarily (for first login, sometimes 2nd).
Client console has nothing of value (only missing City_01_03.geo).

Still getting sporadic behavior on trying to logout. Sometimes it works, sometimes it doesn't. Last time I received an error in the console prior to authserver crashing:
```
...
handle_input: connection reset
handle_input: connection reset
handle_input: connection reset
handle_input: connection reset
Unresponsive link
ACE_ASSERT: file C:/Users/Paul/DOCUME~1/MYPROJ~1/Segs/Projects/CoX/Common/Servers/ClientManager.h, line 96 assertion failed for 'getById(id)!=0'.Aborting...

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by nemerle** [comment]
Please try to verify with the c37c141 as there was a networking layer bug fixed there that could cause client crashes.

**Comment by broxen** [comment]
As of #127 I'm no longer having visibility issues. That said, I'm crashing the server when logging out with one of two characters from the same account. This is as mentioned in the comments on #127 

This doesn't appear to happen with two different accounts, so closing #95 should resolve the issue.

General stability may still need testing, but the specific bug this issue was opened to address appears fixed, so I'm going to close this.
