### ISSUE TITLE
Typos and error in segs_game_mysql_create.sql

### ISSUE THREAD

**Issue by whitegryphon** [Segs/Segs#646]
When running `dbtool -f create` and using a MySQL database there are a couple of typos in Projects/CoX/Data/mysql/segs_game_mysql_create.sql.

**Lines 13-15:** dropping "emails" table needs to be done before dropping "characters" table because of constraints:
```sql
DROP TABLE IF EXISTS `characters`;
DROP TABLE IF EXISTS `accounts`;
DROP TABLE IF EXISTS `emails`;
```
should be
```sql
DROP TABLE IF EXISTS `emails`;
DROP TABLE IF EXISTS `characters`;
DROP TABLE IF EXISTS `accounts`;
```

**Line 77:** string contains a semi-colon in date instead of a colon, which causes an error.
`(8, 'emails', 0, '2018-09-23 08:00;00');`
should be
`(8, 'emails', 0, '2018-09-23 08:00:00');`

**Lines 117-119:** First ADD CONSTRAINT statement on line 118 has a semi-colon at the end of the line instead of a comma:
```sql
ALTER TABLE `emails`
  ADD CONSTRAINT `emails_ibfk_1` FOREIGN KEY (`sender_id`) REFERENCES `characters` (`id`) ON DELETE CASCADE;
  ADD CONSTRAINT `emails_ibfk_2` FOREIGN KEY (`recipient_id`) REFERENCES `characters` (`id`) ON DELETE CASCADE;
```
should be
```sql
ALTER TABLE `emails`
  ADD CONSTRAINT `emails_ibfk_1` FOREIGN KEY (`sender_id`) REFERENCES `characters` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `emails_ibfk_2` FOREIGN KEY (`recipient_id`) REFERENCES `characters` (`id`) ON DELETE CASCADE;
```
### Expected behavior
Creates new databases and tables, or replaces old tables if used with `-f` switch.

### Actual behavior/symptoms
Causes error and fails to create or replace tables correctly.

### Steps to reproduce behavior/symptoms
1. Change `settings.cfg` to use MySQL.
2. Run `dbtool create` (if first time), or `dbtool -f create` to force replacing databases
3. Fails to fully create database and tables.

### SEGS version
0.5.0

### Operating system
Fedora 28

### C++ compiler and version
g++ (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)

**Comment by broxen** [comment]
Great find @whitegryphon!!! 

If you're up for it, please feel free to submit a PR correcting these issues (and any counterparts that may exist in the postgresql and sqlite databases)

**Comment by dracc** [comment]
Looking through the files a second time, there doesn't seem to be any problem with neither pgsql nor sqlite files. Great finds @whitegryphon !
