### ISSUE TITLE
Local chat outputs to Broadcast channel instead, meanwhile Broadcast chat appears to do nothing

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#66]
Using Local chat (either through UI or with slash commands) outputs message to the Broadcast channel, meanwhile the broadcast channel appears to do nothing.

Test:
`/l test local!` output: `[Broadcast] test local!`
`/b test broadcast!` output: _none_

I haven't been able to test Team, Supergroup, or Private Messages yet.

**Comment by nemerle** [comment]
yup this is a known issue, since we didn't have a mapserver scene graph while it was implemented so there was no way to calculate the distance one player could "hear" the local chat's from another.

**Comment by nemerle** [comment]
A few steps towards proper implementation

1.  update ChatMessage::localMessage to use CHAT_Local, see what it does.
1. make MapServer instance accessible in ChatMessage, maybe from Entity ? ( i.e. implement Entity::getCurrentMap() )
1. implement neighborhood query in MapInstance ( MapInstance::getEntitiesInRadius(float R, int type) )
1. send the local chat to entities return in previous step.

**Comment by broxen** [comment]
This issue probably relates to #41

**Comment by broxen** [comment]
CHAT_local works. I'll have to test if there is any range to it.

I tried adding a function for broadcast, but couldn't figure out where to add the slash command `/b` or `/broadcast`

**Comment by nemerle** [comment]
MapInstance::on_console_command handles all console input
broadcast messages are encode as ```b Message text```

**Comment by broxen** [comment]
Latest commits break broadcast chat. Trying to fix with pull #117

**Comment by nemerle** [comment]
As of a849fc2 chat looks like:
![chat test](https://user-images.githubusercontent.com/96597/32393712-ebf8c4ae-c0da-11e7-8157-21c4b11f0a7b.png)

**Comment by broxen** [comment]
This looks good, but we need an additional space between the channel and sender_name.

**Comment by nemerle** [comment]
Should be easy to do:
replace 
```cpp
QString prepared_chat_message = QString("[Local]%1: %2").arg(sender_char_name,msg_content.toString());
```
with
```cpp
QString prepared_chat_message = QString("[Local] %1: %2").arg(sender_char_name,msg_content.toString());
```

**Comment by nemerle** [comment]
This seems to be resolved, closing.
