### ISSUE TITLE
Properly change translucency of entities

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#68]
Currently all entities have translucency hard-coded to 0.5 this needs to be modified.
[Entity::serializeto call is here](https://github.com/Segs/Segs/blob/master/Projects/CoX/Common/NetStructures/Entity.cpp#L496)

**Comment by broxen** [comment]
This seems resolved as of #82 

We might want to speed up the effect, I'll play with the numbers. That said, I think it's safe to close this issue. Unless I've overlooked something?

**Comment by nemerle** [comment]
Nope, as you've noticed the effect is slow, but that was deliberate decision to help during debugging.

We might consider making this configurable though ?

**Comment by broxen** [comment]
Agreed. My opinion is that more options for configuration is almost always desirable.

I realize now that the visibility issues in #63 could be related to this.
