### ISSUE TITLE
Lua bot menu glitch

### ISSUE THREAD

**Issue by jjopilis09** [Segs/Segs#685]
the lua bot seems to have problems with keeping track of what page it's on when accessing all of the options in the menu, such as somtimes when going into player stats and leaving the player stats page it still acts as if it were on the player stats page.

 when clicking temp power somtimes the game opens it up as mapmenu so there seems to be a lot of problems on what option it is actually on compared to what it thinks it's on.

**Comment by jjopilis09** [comment]
![screenshot 34](https://user-images.githubusercontent.com/43968029/48103324-432b9680-e1f4-11e8-8803-618367bc0f7e.png)
I don't know if you can tell or not but in the picture I'm hovering over the temp power option and the mapmenu popped up.

**Comment by broxen** [comment]
I may have partially fixed this in #694
