### ISSUE TITLE
Door randomly transfers me

### ISSUE THREAD

**Issue by Skywalker646** [Segs/Segs#687]
I apologize if this has been mentioned already, but I notice that if i click on a door, say at the hospital in the tutorial, that it teleports me to other zones beneath their map

**Comment by PsiLupan** [comment]
Not really an issue per se. It was sort of a "feature" for testing zone transfers. 

The real issue is that positions in those maps aren't properly set to something reasonable.

**Comment by broxen** [comment]
Closing this as wontfix, since this behavior is intentional currently, and we have another issue open to track spawning
