### ISSUE TITLE
Day Night Cycle is too fast

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#69]
The current day/cycle is too fast, transitioning through a full Cycle every 10min or so. It's so quick you can see the moon moving across the sky in jerky phases.

According to ParagonWiki: 
One real time hour is equivalent to two in-game days, with midnights occurring on the hour and on the half hour.

They have a handy chart as well: https://paragonwiki.com/wiki/Time

And includes information regarding timed events, which means eventually we'll want to expose the game "clock" to the Lua scripting engine for missions and spawns.

**Comment by nemerle** [comment]
Yup, the world day/night speed was set so high since I wanted to be able to tell if it works at all, without waiting a few hours :)
Right now the time of day is stored inside World object, and it's updated in ```World::update```
