### ISSUE TITLE
Character Select Screen doesn't show current Zone info ($15)

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#70]
The Character Select Screen during login doesn't show the character's current zone information. It appears to have a static text statement "Some map name"

![screenshot from 2017-10-21 14-03-16](https://user-images.githubusercontent.com/10159505/31855936-6b9e16bc-b66a-11e7-8356-c0136a6fc034.png)

This is found in CharacterDatabase.cpp on line 146:
https://github.com/Segs/Segs/blob/90cc9e2b4d98687e630a97fcbab2bde813dd4742/Projects/CoX/Servers/AdminServer/CharacterDatabase.cpp#L146

**Comment by nemerle** [comment]
Yup, to solve it we're going to need to:
- [ ] when player enters a map, we should update a map's name and player location in the DB
- [ ] when a Character is retrieved from DB that map name should be read from it.

**Comment by broxen** [comment]
Looking at this. 

Added setMapName to CharacterDatabase.cpp:
```
c->setMapName(STR_OR_EMPTY(m_prepared_char_select.value("current_map").toString()));
```

I'm assuming the current zone can be pulled from the bitstream, but I'm failing to see a pattern there. Tried storing a test string in sendClientData() of EntitiesResponse.cpp but it had no discernible effect. So I'm not really sure what function saves this. Can you point me in the right direction?

**Comment by nemerle** [comment]
Looks ok, and it would work, only problem is the ```current_map``` is a numeric field in the database
So we either need to change it into a map name, or we need to create a map list where we can lookup the name by the current_map index.

**Comment by broxen** [comment]
Ahh I see. I assume these values are in the pigg files somewhere, but we could generate server side anyway? What's better? I suppose if we generate server side it could allow custom maps in the future? We could use a simple LUA script to define map variables? Lighting, atmosphere, etc.. I'm not sure how this is all stored now, so that may not be possible.

Saving these links for reference:

- https://paragonwiki.com/wiki/Category:Maps
- https://paragonwiki.com/wiki/Demo_Editing/Scenic_Maps
- https://paragonwiki.com/wiki/Mission_Architect_Unique_Maps

**Comment by broxen** [comment]
Also, nothing is stored in current_map now. Should it contain data?

**Comment by broxen** [comment]
PR #175 will resolve this.

**Comment by broxen** [comment]
Closing this. Will open a new issue to address serializing map names from bin files.
