### ISSUE TITLE
Provide option to auto-create new accounts at login

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#707]
## Summary
Server admins may want to allow auto-creation of new accounts. This should be optional and enabled through the settings.cfg

It appears as though this can be done somewhere in AuthHandler
```
    AuthLink *lnk = sess_ptr->link();
    assert(lnk!=nullptr);
    if(!msg->m_data.valid()) // no account exists, return proper response
    {
        lnk->putq(s_auth_error_wrong_login_pass.shallow_copy());
        return;
    }
```

**Comment by broxen** [comment]
This has been requested a lot. Would like to get this into v7. Marking as release blocker.

**Comment by miles200** [comment]
@broxen Think we decided to leave this one. Should we close?

**Comment by HeraldOfOmega** [comment]
I would love to have it as an option.

**Comment by broxen** [comment]
With SEGSlauncher and webUI, we may not actually need this.

I'd say we close and see if it pops up again after those tools are in place
