### ISSUE TITLE
Client's connection to DBServer times out during Character Creation

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#71]
Spending too much time on Character Creation results in the client's connection to the dbserver timing out.

I don't have a precise duration for the timeout, but it looks to be around 1.5 minutes, based upon two tests:

**Following:**
Log In  ->  Create New Character  ->  Choose Powers  ->  Choose Costume  ->  Choose Name  ->  Spawn in Atlas Park

**First Test (Log In to Spawn):** 2 minutes 20 seconds
**Result:** Timeout
_Sat Oct 21 14:43:17 PDT 2017
Sat Oct 21 14:45:37 PDT 2017_

**Second Test (Log In to Spawn):** 1 minute precisely
**Result:** Successful Spawn in Atlas Park
_Sat Oct 21 14:46:05 PDT 2017
Sat Oct 21 14:47:05 PDT 2017_

![screenshot from 2017-10-21 14-28-40](https://user-images.githubusercontent.com/10159505/31856146-73ca5422-b66f-11e7-922a-39f1bdfca539.png)

**Comment by nemerle** [comment]
Great find, seems we have to force server to send an IDLE packet ever so often here.

**Comment by broxen** [comment]
This appears to be fixed in latest master branch.
