### ISSUE TITLE
Enhancement Screen visual anamoly

### ISSUE THREAD

**Issue by Abraxus551** [Segs/Segs#713]
![2018-11-25 11_42_37-window](https://user-images.githubusercontent.com/45341151/48984832-c6366300-f0b5-11e8-9dba-88da9d372f75.png)

### Describe the bug
Visual artifact/anomaly embedded in the three column headers

### To Reproduce
Click on "Enhancements" from the top of the powers tray.  Appears regardless of number of times entered, and exited.  Regardless of populating enhancements, and combining them.  Artifacts remain static.

### Expected behavior
Column headers, without artifacts.

### Screenshots or Attachments (if applicable)
Screenshot included.

### SEGS Version, C++ Toolkit
 - SEGS Build ID: 0.6.1
 - C++ Toolkit: Unknown  (Testing on DRACC.SE public server).

**Comment by broxen** [comment]
Thanks for filing this Brax

**Comment by broxen** [comment]
Can anyone else replicate this? I don't see it.

**Comment by JamesDW1** [comment]
I can replicate. I am unaware of the settings Brax uses, but for me it only happens when maximizing the window after starting the game in windowed mode. The dots on either side of the headers appear to be in perfect alignment in every other case. Client issue maybe?

**Comment by nemerle** [comment]
Highly likely that's client side. Not sure if worth adding a patch for it :)

**Comment by broxen** [comment]
Closing `wont-fix`

Thank you all for reporting and testing
