### ISSUE TITLE
Store Script - When purchasing any item, cursor should remain on item until moved

### ISSUE THREAD

**Issue by Abraxus551** [Segs/Segs#723]
### Describe the bug
When using the store function from LUABOT, you are required to repeatedly choose the same item, rather than having the cursor remain on the item, so that it may be purchased repeatedly, if desired.

### To Reproduce
1. Go to the "Store" option in LUABOT
2. Click on any item
3. Click "Buy", and the cursor disappears, rather than remaining on the last purchased item
4. You must then choose the same item again, and click "Buy" if you want to purchase it repeatedly.

### Expected behavior
In the live game, when purchasing anything from the store, once an item is selected, the cursor would remain on that item, until something else is chosen, or you exited the screen, allowing repeated purchases of the same item when desired.

### Screenshots or Attachments (if applicable)
No screen shot adequately demonstrates the issue

### SEGS Version, C++ Toolkit
 - SEGS Build ID: 0.6.1
 - C++ Toolkit: N/A

**Comment by broxen** [comment]
Let's get some more testing on this. I don't recall official server behavior, but the issue described does not sound like something we can correct server-side.

It may simply be an issue with the I1 client.

**Comment by Abraxus551** [comment]
I was not sure if the store (and it's functionality/behavior) was all LUA scripting, or part of the actual client.  One that got "QOL" update down the line to give it the "repeat buy" functionality.  But, I thought I would ask, just in case it is something that can be done sooner, than later.

**Comment by JamesDW1** [comment]
I was able to replicate, but I'm honestly unsure if it's client-related or not. While it might lead to some annoyance with purchasing many of the same thing, it's not too game-breaking either way.

**Comment by broxen** [comment]
I can't see any way in which we could remediate this issue server-side. It's some sort of client issue.

Closing and tagging `wont-fix`
