### ISSUE TITLE
Scripted Mission: Hide-n-Seek

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#726]
## Request
Can we script a game of hide n seek? Basic gameplay would follow:
- Script spawns NPC (the hider) in predefined location (under Atlas for example)
- Talking to NPC would provide dialog to initiate game
- Once game has been started, a countdown from 5 to 1 would begin, with the NPC using the broadcast channel to announce the game beginning.
- at `0` or `start` or whatever, the NPC would randomly teleport to a place on the map.
- Maybe NPC `/b`roadcasts hints periodically? Neighborhood or rough direction (east/west/etc) -- implemented by referencing map beacons, or maybe using location to extrapolate position relative to NPC starting location?
- First player to interact with the NPC receives a point and resets the game.
- Extra cool if we can use the `/kiosks` to track player scores for that day.

### Challenges
Challenges will be spawning in a safe location and tracking score. These might be overcome by referencing movement waypoints for spawn points, and by leveraging the souvenir system for tracking score

**Comment by miles200** [comment]
@ZopharShinta Anything else you need to do for this one? Or did PR #750 implement it?

**Comment by ZopharShinta** [comment]
@miles200 #750 implemented it and #770 had some adjustments on where the points were stored in the DB but everything should be there.
Is something missing/not working?

**Comment by miles200** [comment]
@ZopharShinta No nothing wrong, this bug didn't close with your PR @JamesDW1 spotted it, so just wanted to double check with you before I closed it. Cheers 👍
