### ISSUE TITLE
Install instructions for ubuntu slightly wrong

### ISSUE THREAD

**Issue by Baaleos** [Segs/Segs#727]
---

### Describe the bug
Following the install / setup instructions for ubuntu - it looks like qt and qt5-devel do not exist.
Googling suggests that the packages to install should be

sudo apt-get install qtcreator

sudo apt-get install qt5-default

### To Reproduce
Type this into ubuntu 18
sudo apt-get install build-essential git qt5 qt5-devel

Response:
E: Unable to locate package qt5
E: Unable to locate package qt5-devel

### Expected behavior
Should successfully install qt5 and qt5-devel

**Comment by broxen** [comment]
The docs have recently been revised, but this was overlooked in #718. Let's update the docs with a new PR. Marking this non-programmer and good-first-issue, as it's a great way to dip one's toes into contribution.

**Comment by firefx** [comment]
At the Command Line Interface (CLI), this is correctable by issuing the command:

> sudo add-apt-repository multiverse

**Comment by valcryst** [comment]
> At the Command Line Interface (CLI), this is correctable by issuing the command:
> 
> > sudo add-apt-repository multiverse

It depends on the Ubuntu Version you use.
Ubuntu Server has "multiverse" enabled while Desktop seems to have it disabled.

**Comment by firefx** [comment]
This was not my experience (2 times now, BTW).  Using a fresh install of Ubuntu Server 18.04.1 (only comes in AMD64 now), I had to enable via CLI the multiverse repo both times.  Doing so allowed the QT5 items in the installation instructions (yours if I am correct) to install.  They were not found in the pre-activated repos at installation.  Granted I used the ISO, and bare metal, and I think the instructions indicated they worked on a container without issue.

I also had to set a password for user "segs" so that the command "su segs" would allow me to use that user, and I had to append sudo to a lot of the commands.  I have a revised list of commands to enter that I am getting ready to propose (I suspect to you).

**Comment by broxen** [comment]
Seems like a simple solution to the qt-devel issue would be to simply include those in the apt-get command to ensure that users have them installed?

Is there more to this issue than I understand there to be?

**Comment by valcryst** [comment]
> This was not my experience (2 times now, BTW). Using a fresh install of Ubuntu Server 18.04.1 (only comes in AMD64 now), I had to enable via CLI the multiverse repo both times. Doing so allowed the QT5 items in the installation instructions (yours if I am correct) to install. They were not found in the pre-activated repos at installation. Granted I used the ISO, and bare metal, and I think the instructions indicated they worked on a container without issue.

You are right, on the actual ubuntu 18.04 server "container" it is activated.
Then we should move that CLI into the docs.

> I also had to set a password for user "segs" so that the command "su segs" would allow me to use that user, and I had to append sudo to a lot of the commands. I have a revised list of commands to enter that I am getting ready to propose (I suspect to you).
You should not need "sudo" because almost everything is done as "root" besides the build itself.
Are you sure you used "useradd" and not "adduser" ?

```
root@test:~# useradd -s /bin/bash -r segs
root@test:~# su segs
segs@test:/root$ cd /opt/
segs@test:/opt$ ls -al
total 8
drwxr-xr-x  2 root root 4096 Dec  6 15:58 .
drwxr-xr-x 22 root root 4096 Dec  6 16:02 ..
segs@test:/opt$
```

**Comment by Baaleos** [comment]
I was using a Ubuntu server - hosted in amazon aws - fresh install on version 18.
Its correct that the instructions may be impossible to be correct across all flavors of ubuntu - I guess it would just be nice to know what needs to be done when one runs into a hurdle like this.

**Comment by firefx** [comment]
Used useradd.  I honestly was so glad to find your instructions that I cut and pasted the whole thing into a text file and started dumping it line by line into the CLI.  

I spent 3 days looking for "linux" instructions for the "cross-platform" and was about to pull my hair out.
