### ISSUE TITLE
Ubuntu build fails

### ISSUE THREAD

**Issue by Baaleos** [Segs/Segs#728]
### Describe the bug
I had to do a little bit of hunting to find the relevant dependencies - however after getting cmake to recognize that the dependencies where there, I still got this error at 64% build completion

### To Reproduce
Follow build instructions on a Ubuntu 18 machine provisioned via AWS.

### Expected behavior
Was hoping it would build properly.

[ 64%] Building CXX object Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer                               _interface.dir/MapServerEvents.gen.cpp.o
In file included from /home/ubuntu/Segs/bld/Projects/CoX/Common/Messages/Map/Map                               ServerEvents.gen.cpp:2:0:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/MapXferWait.h: In member func                               tion ‘virtual void SEGSEvents::MapXferWait::serializeto(BitStream&) const’:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/MapXferWait.h:30:9: error: in                               valid use of incomplete type ‘class BitStream’
         bs.StorePackedBits(1, 10);  // opcode
         ^~
In file included from /home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/MapXfer                               Wait.h:9:0,
                 from /home/ubuntu/Segs/bld/Projects/CoX/Common/Messages/Map/Map                               ServerEvents.gen.cpp:2:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: for                               ward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/ubuntu/Segs/bld/Projects/CoX/Common/Messages/Map/Map                               ServerEvents.gen.cpp:2:0:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/MapXferWait.h:31:9: error: in                               valid use of incomplete type ‘class BitStream’
         bs.StoreString(m_map_name);
         ^~
In file included from /home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/MapXfer                               Wait.h:9:0,
                 from /home/ubuntu/Segs/bld/Projects/CoX/Common/Messages/Map/Map                               ServerEvents.gen.cpp:2:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: for                               ward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/GameCom                               mandList.h:28:0,
                 from /home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/Browser                               .h:9,
                 from /home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/MapEven                               ts.h:611,
                 from /home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/TradeWa                               sCancelledMessage.h:9,
                 from /home/ubuntu/Segs/bld/Projects/CoX/Common/Messages/Map/Map                               ServerEvents.gen.cpp:4:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/LevelUp.h: In member function                                ‘virtual void SEGSEvents::LevelUpResponse::serializefrom(BitStream&)’:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/LevelUp.h:51:38: warning: unu                               sed parameter ‘bs’ [-Wunused-parameter]
     void    serializefrom(BitStream &bs) override
                                      ^~
In file included from /home/ubuntu/Segs/bld/Projects/CoX/Common/Messages/Map/Map                               ServerEvents.gen.cpp:98:0:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/ForceLogout.h: In member func                               tion ‘virtual void SEGSEvents::ForceLogout::serializefrom(BitStream&)’:
/home/ubuntu/Segs/Projects/CoX/Common/Messages/Map/ForceLogout.h:30:35: warning:                                unused parameter ‘bs’ [-Wunused-parameter]
     void serializefrom(BitStream &bs) override
                                   ^~
Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer_interface.dir/build.make:1                               32: recipe for target 'Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer_int                               erface.dir/MapServerEvents.gen.cpp.o' failed
make[2]: *** [Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer_interface.di                               r/MapServerEvents.gen.cpp.o] Error 1
CMakeFiles/Makefile2:1363: recipe for target 'Projects/CoX/Common/Messages/Map/C                               MakeFiles/MapServer_interface.dir/all' failed
make[1]: *** [Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer_interface.di                               r/all] Error 2
Makefile:129: recipe for target 'all' failed

**Comment by broxen** [comment]
If you immediately retry the build, does this continue to happen? Perhaps it's just the order of dependencies. What toolchain is being used? QTCreator + GCC?

**Comment by broxen** [comment]
I can't replicate this on Fedora, and it looks very much like a swap memory issue. Recommendation is to try to rebuild again immediately to see if it succeeds on the second pass. 

@Baaleos please reopen if you're still experiencing issues.

**Comment by Fourgot** [comment]
Following the instructions on the [headless Ubuntu 18.04 page](https://github.com/Segs/Segs/blob/develop/docs/SEGS-COMPILE_AND_INSTALL-UBUNTU.md), and provisioning a tiny virtual server using [Linode](https://www.linode.com), I also was unable to get a successful compilation. Unfortunately, I only got to 28% built. Last few messages are below.

The previous suggestions to immediately try building (by running `make`?) yielded no change.

[ 27%] Built target cox_server_common
[ 28%] Automatic MOC for target gameData
[ 28%] Built target gameData_autogen
[ 28%] Building CXX object Projects/CoX/Common/GameData/CMakeFiles/gameData.dir/bodypart_definitions.cpp.o
/usr/src/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp: In member function ‘void BodyPartsStorage::postProcess()’:
/usr/src/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp:98:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < m_parts.size(); ++i )
                     ~~^~~~~~~~~~~~~~~~
/usr/src/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp: In member function ‘BodyPart_Data* BodyPartsStorage::getBodyPartFromName(const QByteArray&)’:
/usr/src/Segs/Projects/CoX/Common/GameData/bodypart_definitions.cpp:120:27: error: ‘class QByteArray’ has no member named ‘compare’
         if ( 0==bp.m_Name.compare(name,Qt::CaseInsensitive) )
                           ^~~~~~~
Projects/CoX/Common/GameData/CMakeFiles/gameData.dir/build.make:830: recipe for target 'Projects/CoX/Common/GameData/CMakeFiles/gameData.dir/bodypart_definitions.cpp.o' failed
make[2]: *** [Projects/CoX/Common/GameData/CMakeFiles/gameData.dir/bodypart_definitions.cpp.o] Error 1
CMakeFiles/Makefile2:783: recipe for target 'Projects/CoX/Common/GameData/CMakeFiles/gameData.dir/all' failed
make[1]: *** [Projects/CoX/Common/GameData/CMakeFiles/gameData.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Fourgot** [comment]
Okay, my error was not associated with the initial bug report. Following the installation guide, I ended up on the development branch.

I'll submit a PR to edit the guide to include:
```
git fetch origin refs/tags/v0.7.0:refs/tags/v0.7.0
git checkout v0.7.0
```

Thanks!

**Comment by dracc** [comment]
@fourgot For future reference, your error stems from using an old version of Qt5. A version check should probably be added in the CMake scripts.

**Comment by CR-DESIGN-Solutions** [comment]
How do I unsubscribe to all this?

**Comment by nemerle** [comment]
@CR-DESIGN-Solutions Most likely You'll want to switch Github's 'watch mode' to less verbose one. The option to do this is in the first button here.
![image](https://user-images.githubusercontent.com/96597/60771276-b9ff9300-a0e5-11e9-930b-a805dbbf374e.png)
