### ISSUE TITLE
Power data?

### ISSUE THREAD

**Issue by Baaleos** [Segs/Segs#732]
This is not so much a feature request - but more a suggestion?

Do you guys have ways to access the data pertaining to the power data etc
Eg: Red Tomax was able to get the information once before - but not sure how he did it.
He then put it on City of Data - which unfortunately is now offline.

I am currently putting together a JSON version of the powerset data scraped from the archived pages remaining online of City of Data - Alas - some pages are lost completely.

Just wondering if this information would be useful when it comes to power implementations? 
Or do you guys already have a way of getting the power specifications from the game itself?

The data - will look something like this

> {
>     "Id": "Controller_Control.Electric_Control",
>     "Name": "Electric Control",
>     "Powers": [
>       {
>         "MoreDetail": {
>           "Level": "1",
>           "Type": "Click",
>           "PvE damage scale": "1.000000",
>           "Accuracy": "1.2",
>           "Modes required": "",
>           "Modes disallowed": "Disable_All",
>           "Range": "80 feet",
>           "Activate period": "",
>           "Interrupt time": "",
>           "Cast time": "1.67 seconds",
>           "Recharge time": "4 seconds",
>           "Endurance cost": "7.8",
>           "Attack types": "Ranged, Energy",
>           "Effect area": "Character",
>           "Radius": "",
>           "Arc": "",
>           "Max targets hit": "",
>           "Entities affected": "Foe",
>           "Entities autohit": "",
>           "Target": "Foe",
>           "Target visibility": "Line of Sight",
>           "Nofity Mobs": "Always"
>         },
>         "Id": "Controller_Control.Electric_Control.Electric_Fence",
>         "Name": "Electric Fence",
>         "NotAvailable": false,
>         "Type": "Ranged, Moderate DoT(Energy), Foe Immobilize, -End, -Fly, -Knockback",
>         "Description": "Surrounds and Immobilizes a single target in an Electric Fence. Deals some damage over time and slowly drains some Endurance. Useful for keeping villains at bay and bringing down fliers. Damage: Minor(DoT), Recharge: Fast"
>       
> 
> },

**Comment by broxen** [comment]
Pinging @crylico as he's been our lead on Powers.

**Comment by crylico** [comment]
@broxen that's @cyanpill, not me ;) I'm on Team stuff, but I haven't touched had a chance to touch it in a little bit...I'll be active again in the next couple of days :D

**Comment by broxen** [comment]
My mistake. My brain is really awful. Yes, of course it's Cyanpill. My apologies everyone.

**Comment by cyanpill** [comment]
Great, if you can work on the json data that will save me some work! I'm just about to get back to work on powers, I started an example json, I'll try to upload that soon. For now read my wiki pages, don't mind me rambling: https://github.com/Segs/Segs/wiki/Implementing-Power-Effects

**Comment by broxen** [comment]
I'll leave this open until a format is decided upon and PR submitted. Thanks Team!

**Comment by Baaleos** [comment]
The script I created to scrape the Data is running- I will post a Link to it tomorrow (GMT)
The script captures the following

Power attributes from the left of the Red Tomax page (more details)

The power effects from the right of the Red Tomax page (separates and groups based on who the effect is targeting, also includes the attributes for the power indicating unresistable, stackable etc)
The numbers captured assume a level 50 is used

The enhancement types accepted by the power from the top right of the page

This will be stored at the moment in a model like this (writing this on iPad so I will show the real thing tomorrow)

Power sets -> collection of power set
Power set -> ID, Name , Powers (collection of power)

Power
-> ID
-> Name
-> Type (Ranged, Moderate dot etc
-> Description
-> MoreDetail (Dictionary<string,string>)
-> PowerEffects (Dictionary<string,List<PowerEffect>>) where the key is the target of the effects ( self, target, location etc
Power Effect is a type like this
     -> Name
     -> Modifiers (string[]) each modifier being the unresistable unstackable flags etc
      
-> Enhancements (String[])


This is running at the moment for Primary, Secondary and Ancillary power sets.
Pool powers and temp powers will need a new scraping script to get the Data out.

**Comment by Baaleos** [comment]
I stayed up to watch the script go:
It was somewhat relaxing

http://magic.asmodei.net/uploads/PrimaryPowerSets.json

Note- ignore the file name
There are some which were missing from the archive but I think I can fill in the blanks tomorrow
This is Data accurate as of issue 24 beta

**Comment by cyanpill** [comment]
here is what I made by hand so far:
https://github.com/segs-community/cox-scripts/blob/master/powers.json

**Comment by Baaleos** [comment]
Hey - I saw in the power implementation page you were interested in getting data from Mids Hero Designer.
If its of interest, I have managed to decode the database files and think I can serialize the power data stored inside to a json.
It will be around 9000 power entries.
I suspect it will be a huge json though.

**Comment by cyanpill** [comment]
That would be very useful! And I expect it to be long, the direct conversion from powers.bin to json is 203,230 lines of text. If you are using data from an issue later than issue 1, there will be powersets that aren't usable yet, so those could be removed to keep the file smaller. And we can skip everything related to npcs, for now.

**Comment by Baaleos** [comment]
With no really feasible way to get that 130+ mb file online 
I rarred it and added it to IPFS

https://ipfs.infura.io/ipfs/QmdjGM7Z5H2zEguFMXmj2XuBYRRUmshyk5BTnVE5FJaEZe
https://gateway.ipfs.io/ipfs/QmdjGM7Z5H2zEguFMXmj2XuBYRRUmshyk5BTnVE5FJaEZe

Gets it down to around 1.5mb
Just rename the file extension to be .rar and then you can extract with Winrar etc.
This is the version which has the enums as strings - for all of Mids Hero Designer Powers.
This is the raw version with I24 content present.

**Comment by broxen** [comment]
Eventually let's separate these out by powerset and stick in one folder under scripts

**Comment by Baaleos** [comment]
I've been having a chat with the admin at Titan Network
Hes provided fresh dumps of the COH power data- I assume these are dumps that were used for City of Data.

https://www.cohtitan.com/forum/index.php?topic=12011.20

He says that their data comes straight from the client, because when the devs started allowing players to see the power numbers, those numbers then became part of the client.
I guess because you guys are starting at Issue 1 - you don't have that luxury.

**Comment by broxen** [comment]
True. Also we'll want to have them as scripts anyway so that the community can modify to their liking.

Some server admins may want pre-ED style powers, and some totally rebalanced powers, etc

**Comment by Baaleos** [comment]
@broxen 
I've got all the powers separated into subfolders based on powersets in my own fork.
Is there a specific branch I should raise a pull requests against?
Just conscious that this is issue 24 beta powers.
Having them all listed as individual power jsons inside subfolders etc will make it easier to manage and update as opposed to a big dump file.

**Comment by broxen** [comment]
Yes, I would create a fork of the segs repo, create a new branch for Powers Json and upload there. Then you can submit a PR to this repo's Develop branch

**Comment by Baaleos** [comment]
Closed the PR as requested
It sounds like the format for powers that the server should support will be the powers.bin format.
Which means that we will need some sort of intermediary software external to SEGS for power customisation by server owners. 
(Eg: Extract from powers.bin and then compile to powers.bin format)
Does anyone know any libraries / tools exist that does this already?

**Comment by cyanpill** [comment]
I've been experimenting with loading powers.json converted from the issue1 .bin, and it works just the same, and as long as you keep the formatting it can be edited by hand. And the AttribMod can be added, which works! but it would be tedious to put in 500+ powers. I think this is our path forward, converting the issue24 powers.bin to a json.
I took a look at the cohtitan thread, and that's the same data as Leadro showed me a while ago. It has the same names for data as the issue1, it just needs to be in the json format. Which I believe Leadro has, he showed me some samples.

**Comment by Baaleos** [comment]
I've opened a pull request to get this merged into master for sigs-community
https://github.com/segs-community/cox-scripts/pull/16

**Comment by broxen** [comment]
Closing this as it is better dealt with by the community than the SEGS team directly.
