### ISSUE TITLE
Lua Pit Stop Race

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#735]
## Feature Summary
Using Lua, create a milestone race with 5-6 contacts or phone boxes that you must click on before proceeding to the next "pit stop". Your time to reach each pitstop would be recorded, and at the end you'd receive a Souvenir based upon your speed (bronze, silver, gold).

Could even spawn the pit stop NPCs at badge locations, or simply use phone call boxes, or maybe a combination of both. I think 4-6 "stops" is probably enough.

Bonus points if you can make the `/kiosk home home` city info terminals show a leader board

**Comment by mobbyg** [comment]
Oooo I like this.  Like the ski run in Pocket D

**Comment by broxen** [comment]
Yeah! Also like the races in DCUO: https://www.youtube.com/watch?v=h71ik48lP9A

**Comment by broxen** [comment]
Closed by #770
