### ISSUE TITLE
Refactor string parsing out of each SlashCommand Handler

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#741]
## Feature Summary
We can improve readability and code clarity in SlashCommands.cpp by refactoring each handler to remove code duplication

One basic way in which this can be achieved is by handling command string parsing _before_ we pass the command to the command handler.

As an example, we often need each string argument from a slashcommand:
```cpp
void cmdHandler_SetCustomTitles(const QString &cmd, MapClientSession &sess)
{
    bool        prefix;
    QString     msg, generic, origin, special;
    QStringList args;
    args = cmd.split(QRegularExpression("\"?( |$)(?=(([^\"]*\"){2})*[^\"]*$)\"?")); // regex wizardry

    if(cmd.toLower() == "settitles")
    {
        setTitles(*sess.m_ent->m_char);
        msg = "Titles reset to nothing";
    }
    else
    {
        prefix  = !args.value(1).isEmpty();
        generic = args.value(2);
        origin  = args.value(3);
        special = args.value(4);
// so on...
```
This string parsing: `QStringList args = cmd.split(QRegularExpression("\"?( |$)(?=(([^\"]*\"){2})*[^\"]*$)\"?")); // regex wizardry` could be moved to `runCommand()` and the resulting QStringList passed to the SlashCommand Handlers to access directly.

Also this would standardize the way we parse strings for SlashCommands and would allow for complicated commands such as `/titles First Second "Long Third One"` to work across the board.

This change alone would reduce the file size by approximately 250 lines of code. I'm open to other ideas on how we can refactor SlashCommands.cpp

**Comment by sfraint** [comment]
I can take this on

**Comment by nemerle** [comment]
Nice, if You need any help, please drop by our discord :)
