### ISSUE TITLE
Add [AdminRPC] section to SEGSAdmin and Settings_template.cfg

### ISSUE THREAD

**Issue by miles200** [Segs/Segs#742]
- Add option to SEGSAdmin to allow users to 'Publish' their server online status to SEGSLauncher (if included in the community json. if yes = add [AdminRPC] section with location_addr
- Add [AdminRPC] and location_addr to settings_template.cfg, commented out with instructions on what it does.

**Comment by broxen** [comment]
This was complted by #745. Great work team!
