### ISSUE TITLE
Server doesn't AFK (or disconnect?) idle clients

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#75]
I accidentally left the client running on my server all night and day, totaling over 18hrs. This shows how rock-solid the server is! However, it probably isn't desired behavior for a live server? Should the server disconnect idle clients?

Regardless, the server should detect when a client goes idle for a period of time, and set the character to [/afk status](https://paragonwiki.com/wiki/Afk_(Slash_Command))

**Comment by nemerle** [comment]
I'd say it should, we need to configure two transition times:
- Idle->AFK time, after which the server will mark player as afk
- AFK-> Disconnect time, after which the player will be kicked from server.

**Comment by mobbyg** [comment]
You may want to offer a config for private servers that are for a small group, to disable disconnect or set that idle time. But a 45 min afk to me is long enough. Big kudos for 18 hrs!

**Comment by nemerle** [comment]
Yup, we should not time out if configuration for Afk->Disconnect is set to zero, thus allowing for infinite AFKness :)

**Comment by JMox** [comment]
Will take a look at this when I start to feel better :)

**Comment by eos428** [comment]
A few things:

- We'd need an opcode to send to the client to put the client into afk status (we already have ToggleAFK I suppose) and then another one to disconnect the client.
- What is exactly being 'idle' and how does the server deduce that a client is being idle atm

Then we go to the coding part:
- Modify MapServerData to store idle->AFK time and AFK-> Disconnect time from settings.cfg
- Instantiate a timer in every MapInstance in which the timer interval is taken from MapServerData (alternatively, directly from settings.cfg) and let either one of World or SyncService handle the entities (I prefer the latter since it handles/will handle only player entities)
- Modify a character's chardata (this seems the best since AFK is already here) to store 2 timer values in maybe float. I am thinking about m_time_to_afk and m_time_to_disconnect (Preferably something that we can not save to the database)

**Comment by broxen** [comment]
There's not really an opcode to toggle afkness, but if you toggleAFK, the player will go afk on next update (effectively immediate)

For timer durations, we can reference this patch:
https://paragonwiki.com/wiki/Patch_Notes/2004-11-16

**Comment by eos428** [comment]
Not needing an opcode to AFK players is great :)

Read up on the wiki, and here are the changes I'd propose:
- Add m_is_on_task_force on chardata
- Check against g_defined_map_datas based on the map the character is in at the moment to see if the character is on a 'mission map' (I think this applies to both hazard and trial maps)
- Log at least one input from the player. If there is no input - depending on the status (m_afk == true/false) we increase m_time_to_afk or m_time_to_disconnect by deltaTime. If there is an input, set m_afk to false and both timers are set back to 0.

**Comment by broxen** [comment]
Sounds like a great plan!

**Comment by eos428** [comment]
Good :) 

The major question mark then would be - how should we log an input from the player? Is it has_input_commit_guess in Entity.h?

**Comment by broxen** [comment]
That might work, but it may be more effective to simply save the state of the bits received in serializefrom(), and use that as a catch-all `m_input_received`

```
void InputState::serializefrom(BitStream &bs)
{
    m_data.m_send_deltas=false;

    if(bs.GetBits(1))                     // <-- maybe use this instead?
        extended_input(bs);
```

**Comment by broxen** [comment]
Also because `has_input_commit_guess` is mislabeled, it really should be something like `m_has_keyrelease`

Below that variable, we receive additional control_bits from the server for when you're holding down a key. If we use `has_input_commit_guess` we run into a possible scenario where something running for a long distance without changing direction, is considered AFK. Unlikely, but possible.

**Comment by eos428** [comment]
Checking if the entity has any input from bs.GetBits(1) seems great... Then we should modify InputStateStorage so that it has both m_input_received and m_has_key_release.

And yes, we should look out for even fringe scenarios, now matter how unlikely they might be.

**Comment by Mattwo** [comment]
I think that auto-afk should be non-optional but auto-kick should be optional.

**Comment by broxen** [comment]
I'm all for providing as much customization as possible, while providing defaults that feel as close to "Authentic" as possible.

**Comment by supermandrew** [comment]
I agree with @broxen here.  Maybe just a simple config file that has some options like time-to-kick or something sounds great.
