### ISSUE TITLE
Refactor SlashCommands for code hygiene

### ISSUE THREAD

**Issue by eos428** [Segs/Segs#756]
Much like we talked about how MapInstance should be split, SlashCommands should also be refactored and split.

What to do:
- [X] Put the cmd.split regex thing into a single functions that will be used by most of these CMD functions
- [x] Split it up to different files. I forgot what's the convention again, but I'd like SlashCommands_Email, SlashCommands_Power and etc. Feel free to suggest better naming conventions though.
- [ ] Put functions aside from splitting up the ``cmd`` string and place them into DataHelpers and such, or the other way around - which is to remove the functions from DataHelpers and put everything inside the SlashCommands functions

**Comment by broxen** [comment]
Thank you for filing this! 

Assigning to you and marking for v7. Feel free to un-assign yourself if you'd like to open it up to other contributors.

**Comment by broxen** [comment]
Tagging #741 as they relate directly.

**Comment by broxen** [comment]
As a part of this, it might be prudent to rewrite most of those commands to accept a target.

`setHP` `setEnd` `setTitles` etc would be useful for ServerOps to have for manipulating other entities (not just players) and so they really should accept a target. Commands without targets would assume `target = self`

**Comment by eos428** [comment]
I forgot a bit about C++, but can you default a function param to null? If yes, then I wouldn't need to write overloads of the same functions.

Also, how do I get the targets of the commands? By parsing the cmd string or is the target stored in entity data?

**Comment by broxen** [comment]
You can default function arguments.

For the target, I would take it from the command string, `/cmd $target args...` and `/cmd args...`

The entity stores it's target as an object, but for this case I think we'd want to take a name and look up target by name, or replace `$target` with the name of the players current target like we do for tells currently.

Thinking of it that way, I don't think you need to overload anything

**Comment by cyanpill** [comment]
While we are changing slash commands, a feature mentioned on the wiki, you could add underscores at any place in commands. https://paragonwiki.com/wiki/Slash_Commands

**Comment by broxen** [comment]
Interesting. Seems they just stripped them out.

**Comment by broxen** [comment]
Regarding item three `remove the functions from DataHelpers and put everything inside the SlashCommands functions` originally the helper methods in DataHelpers were used in several places. This may have changed with recent restructuring.

Just something we should keep an eye out for, we may not be able to remove DataHelpers completely.

**Comment by eos428** [comment]
I am in favor of moving the functions from SlashCommands to the helpers. The helper functions are used by MapInstance stuff (see the refactor PR) and more, so it makes sense not to disturb the ones already referred to by multiple files.

I'll be continuing this one if no one else takes the mantle :)
