### ISSUE TITLE
Implement /stuck command

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#76]
It might make sense to implement the [/stuck command](https://paragonwiki.com/wiki/Stuck_(Slash_Command)) as the mapserver and collision detection come together.

Official Server behavior was to move you a very small distance to a unobstructed location.

**Comment by nemerle** [comment]
Implementing a simple 'reset position to original' would not be hard, the other way ( move player to closest non-colliding location will require #81 )

**Comment by broxen** [comment]
PR #175 implements a rudimentary version of this that resets the player to Ms. Liberty's position in Atlas Park.

**Comment by broxen** [comment]
I'm going to close this for now. We can reopen once #81 is complete, with the aim of mirroring Cryptic's implementation.
