### ISSUE TITLE
Excessive line feeds in server output

### ISSUE THREAD

**Issue by HeraldOfOmega** [Segs/Segs#761]
### Describe the bug:
Excessive line feeds in server output.

### To Reproduce:
Start SEGSAdmin, start server, observe logins and actions.

### Expected behavior:
Line feeds that make sense, if any.

### SEGS Version:
 - SEGS Build ID: 0.6.1

**Comment by broxen** [comment]
Can you be more specific? Is this line returns? Can you post a screenshot?

**Comment by HeraldOfOmega** [comment]
Running under Windows 7
![serverpic](https://user-images.githubusercontent.com/43530827/52459137-3b8fcc80-2b18-11e9-89ba-c9367cb2791d.png)

**Comment by broxen** [comment]
I'll defer to @Miles, but I think this is a known unsolvable bug.

I think we're all open to suggestions.

**Comment by HeraldOfOmega** [comment]
Is it Qt-specific?

**Comment by broxen** [comment]
My understanding is yes.

**Comment by miles200** [comment]
Just to clarify, the issue is with the excessive white space between lines?

**Comment by broxen** [comment]
I believe so. If that's the case, some internet sleuthing seems to indicate that carriage returns are being treated as newlines and `str.replace("\r", "")` may resolve the issue. 

From here: https://forum.qt.io/topic/85162/qtextedit-and-carriage-return-r-character/3

**Comment by miles200** [comment]
Thanks @broxen , I went with changing `appendPlainText()` to `insertPlainText()` 

From the docs, appendPlainText():
Appends a new paragraph with text to the end of the text edit.

insertPlainText():
Convenience slot that inserts text at the current cursor position.

![segsadmin_bug](https://user-images.githubusercontent.com/35471210/52504600-d8b63800-2be0-11e9-84af-e96dda8d03ef.PNG)

I'll push a PR this evening

**Comment by broxen** [comment]
Fantastic
