### ISSUE TITLE
AdminRPC Test Client

### ISSUE THREAD

**Issue by miles200** [Segs/Segs#772]
## Feature Summary
As we now have an AdminRPC framework in place and I'm assuming more methods will added over time, would an AdminRPC test client be helpful to anyone? Especially the webUI team? 

### Proposed Implementation
Simple application which takes server IP, AdminRPC method name and input parameters, calls service and returns result. 

Can be used to see what data is being returned, test an RPC method, without having to build it into something like SEGSAdmin

Open for discussion, may not be helpful for anyone :)

**Comment by broxen** [comment]
Tagging @Segs/weavers

**Comment by miles200** [comment]
https://cl.ly/0299d72891a7/Screen%20Recording%202019-02-10%20at%2010.18.20.16%20PM.mp4
