### ISSUE TITLE
'Levels to Unlock Costumes' field blank in SEGSAdmin

### ISSUE THREAD

**Issue by JamesDW1** [Segs/Segs#774]
### Describe the bug
Upon opening Settings for SEGSAdmin, the 'Levels to Unlock Costumes' field is blank
 
### To Reproduce
1. Go to Settings and Logging
2. Click on Starting Character
3. Levels to Unlock should be blank

### Expected behavior
Levels to Unlock should be populated by default '19, 29, 39, 49'

### Actual Behavior
User will have to click Reset Defaults in order for the default levels to be applied and proceed to re-apply any information they had previously saved (i.e. IP Address, Logging options, etc). While it's not a game-breaking issue, it could certainly be a hassle.

### Screenshots or Attachments (if applicable)
Upon reproduction:
![before](https://user-images.githubusercontent.com/37761861/52540538-2604e780-2d50-11e9-883d-583fc50a2b1c.png)
After resetting defaults:
![after](https://user-images.githubusercontent.com/37761861/52540541-30bf7c80-2d50-11e9-96a6-467a99880859.png)

**Comment by JamesDW1** [comment]
Appears this was an issue with my settings.cfg. If no one else is able to replicate this, it can probably be closed.

**Comment by miles200** [comment]
Unable to replicate, James has confirmed the value was missing from settings.cfg. Closing
