### ISSUE TITLE
Add settings_template.cfg version entry

### ISSUE THREAD

**Issue by miles200** [Segs/Segs#775]
I'll flesh this out tomorrow as on mobile but logging so I dont forget. 

Add a version number to settings_template.cfg. Increment on each change to settings_template.cfg 

Add SEGSAdmin check compare template version to current settings.cfg version, if not latest prompt user to regenerate file. 

Will stop users encountering issues as we add to / change the settings.cfg file in the future

**Comment by broxen** [comment]
This seems like a great idea. Thanks for adding this feature request!

**Comment by Cynicide** [comment]
I saw this issue was on the 0.7 release list and I was thinking of taking this issue on, but I'm worried it might be a little beyond my skills as I only have a very basic knowledge of C++ and have never worked with signals or QT before. But I guess you don't learn anything without moving out of your comfort zone.

I've managed to get the version number via `VersionInfo::getAuthVersionNumber()` and I've created a signal that fires during `if(config_file.exists())`  that checks the version in the file against the version in code. All tested and working. 

The last part is handling an incorrect version. Ideally I'd like a dialog box that asks the user whether they'd like to default their config file or keep going as is. I've attempted to steal some code from the `AboutDialog` to create a new UI but it's taking me a while to get through the QT stuff, I feel that creating new ui/cpp/h files is a waste for something as small as this. Is there something already in the code that I could appropriate that would just let pop up a dialog box and let me fire a signal if the user hits OK?

**Comment by miles200** [comment]
Hey @Cynicide 

No worries! You're right best way to learn is to get stuck in. 

Take a look inside SEGSAdmin at SettingsDialog theres a simple QMessageBox in there which I think is what you're after. 

Just ping me on discord if you need me to go over anything plus we have the review process on github so dont be worried about pushing up a PR once done we can help you through any issues

**Comment by broxen** [comment]
I think the intention is actually to have a version number specific to the config file and compare that against a constant that we keep in the server. in this way it would be different from the servers version number because the config file may change in between major updates to the server.

An example would be where we look at the database version numbers that we check against those DB version constants at startup. 

Maybe I'm misunderstanding the issue though. @miles can you advise?

**Comment by miles200** [comment]
Yes sorry I missed that. 

I was actually thinking of something like this: 

- Add a version number to settings_template.cfg , which will carry over to the generated settings.cfg file when file is generated. 
- If we then release a new version of settings_template.cfg we increment the version number. 
- SEGSAdmin then compares currently generated settings.cfg version number == settings_template.cfg version number... if a mismatch we prompt to re-generate.

**Comment by Cynicide** [comment]
Sure, I understand. Is version.h the correct place for the config version to live in code?

**Comment by broxen** [comment]
Yeah that seems like the best place to me. In fact we should probably move the database version numbers over to version.h as well.

**Comment by broxen** [comment]
If you're up for it, simply move the two `REQUIRED_DB_VERSION` constexprs to version.h and rename them `REQUIRED_AUTH_DB_VERSION` and `REQUIRED_GAME_DB_VERSION`. Settings cfg version would follow suit.

**Comment by miles200** [comment]
I wasn't thinking of putting it in version.h at all, but may be a good idea. 

To be clear are we planning on comparing settings.cfg version to version.h version?

**Comment by Cynicide** [comment]
After reading broxen's comments that was my intention. A constant in version.h called `ConfigVersion` which is compared to a version string in settings file. At this stage I've created a new section in the config template called `[Metadata]` to hold information about the config file, its only entry is `config_version`.

**Comment by miles200** [comment]
Sounds good. I have a pending item to change the structure of SEGSAdmin SettingsDialog to fully generate from settings_template.cfg (most of it is hard coded currently)

So, in the meantime, we'll need to also add some code to SEGSAdmin to generate these new config values on it's generate config file method.

**Comment by Cynicide** [comment]
Yes, I noticed. I added my value to the template and scratched my head when it didn't show up in a newly generated config file when I saw the code though it made sense.

The code to add/read the version to the config file is in, added to`generate_default_config_file` and `read_config_file`. I've tested it and it works, I'm just going to implement some basic error checking (no version number field/empty version number field) before moving on to the hard stuff, which is the message box.

**Comment by miles200** [comment]
Great work @Cynicide thanks 👍

**Comment by broxen** [comment]
I like it in Version.h, because I can reference it from dbtool as well? Settings.h would work, but I think there's some logic to having all the versions centralized?

**Comment by Cynicide** [comment]
Wondering if someone can have a look at this. I'm doing some tests after moving the DB Versions into version.h So this:

```
int64_t db_version = getDatabaseVersion(*m_db);
    if(db_version != REQUIRED_DB_VERSION) 
    {
        // we should just stop the server, it isn't going to work anyway
        qFatal("Wrong database version (%d) Game database requires version: %d", db_version, REQUIRED_DB_VERSION);
        db2->setConnectOptions();
        return false;
    }
```

Has become this:
```
    int64_t db_version = getDatabaseVersion(*m_db);
    int64_t required_db_version = VersionInfo::getRequiredGameDBVersion();

    if(db_version != required_db_version)
    {
        // we should just stop the server, it isn't going to work anyway
        qFatal("Wrong database version (%d) Game database requires version: %d", db_version, required_db_version);
        db2->setConnectOptions();
        return false;
    }
```

However this introduces two issues. Firstly, I can't define the DB versions int64_t in version.h I get `int64_t does not name a type` during compile time. I can define it as an int and everything works fine, but I'm wary of introducing type errors. 

Secondly, the qFatal() formatting doesn't work, I get this logged in SegsAdmin if I set an incorrect DB version: `[19:34:25] Fatal: Wrong database version (8) Game database requires version: 0`. The requird version should read 9, I suspect the formatter is messing it up. The code works, the comparison detects mismatched DB versions, but I'd really like to have a logging working and I'd rather not introduce type errors tinkering with something I don't fully understand. I get this warning during compile time:

```
D:\Dev\Segs\Projects\CoX\Servers\GameDatabase\GameDBSyncContext.cpp:148: warning: format '%d' expects argument of type 'int', but argument 3 has type 'int64_t {aka long long int}' [-Wformat=]
         qFatal("Wrong database version (%d) Game database requires version: %d", db_version, required_db_version);
```
                                                                                                                 
I'm not sure if this logging was working previously, but now seems like a good time to fix it. To get rid of that warning I've tried `"%" PRId64` as the formatter but it hasn't worked. The second variable in the log still reads 0.

**Comment by miles200** [comment]
> I like it in Version.h, because I can reference it from dbtool as well? Settings.h would work, but I think there's some logic to having all the versions centralized?

@broxen ye fair enough, version.h will be fine 👍
