### ISSUE TITLE
Cleanup unused parameter errors

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#780]
## Summary
We have a lot of unused parameter warnings during compile. The majority of these are unused BitStream arguments in serialize methods. We should comment them out `void    serializefrom(BitStream &/*bs*/) override`

This is a `great first issue` for those of you looking to contribute in a meaningful way, but who are afraid of diving into a larger issue.

Feel free to respond here, and submit a PR with your changes.

### Example
```cpp
In file included from /SEGS/Segs/Projects/CoX/Common/Messages/Map/GameCommandList.h:28,
                 from /SEGS/Segs/Projects/CoX/Common/Messages/Map/Browser.h:9,
                 from /SEGS/Segs/Projects/CoX/Servers/MapServer/ScriptingEngine.cpp:19:
/SEGS/Segs/Projects/CoX/Common/Messages/Map/LevelUp.h: In member function ‘virtual void SEGSEvents::LevelUpResponse::serializefrom(BitStream&)’:
/SEGS/Segs/Projects/CoX/Common/Messages/Map/LevelUp.h:51:38: warning: unused parameter ‘bs’ [-Wunused-parameter]
     void    serializefrom(BitStream &bs) override
                           ~~~~~~~~~~~^~
```

**Relates To #352**

**Comment by CXX2A** [comment]
There are some other unused parameters as well. Should we take care of them too?
