### ISSUE TITLE
Failed to locate class index for ""

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#785]
## Summary
Several users are reporting `[22:12:23] Warning : Failed to locate class index for ""` messages in the server console.

`[23:43:22] Warning : Failed to locate class index for ""` originates in `getEntityClassIndex()` where it's called from `initializeNewNpcEntity()`

My guess is that we're not setting the class_name needed by that method prior to calling `initializeNewNpcEntity()`. It's not clear if this is happening in the Lua scripts or in our server-side npc generators.

**Comment by YellowAdder** [comment]
I believe this is related to the spawning of persistent NPCs and suspect it's related to a handful of store NPCs in particular. I could be wrong on both counts but will likely test the theory soon.

**Comment by YellowAdder** [comment]
The problem child for this bug are spawning any of the Icon employee models:

Model_IconEmployeeA
Model_IconEmployeeB
Model_IconEmployeeC
Model_IconEmployeeD
Model_IconEmployeeE
Model_IconEmployeeF
Model_IconEmployeeG
Model_IconEmployeeH
Model_IconEmployeeI

Note that all of them DO spawn in a model but produce the "Failed to locate class index for """ error in the process. This can be reproduced by using the /addNpc <model> slash command.

**Comment by HeraldOfOmega** [comment]
Nice detective work, YellowAdder.

**Comment by YellowAdder** [comment]
I also noticed that origin store NPCs weren't spawning, and once I set them up to be able, those models also produced the error when created. I believe Freedom Corp models are fine, so their store versions may help distinguish why the others are producing the error. Someone more familiar with the getEntityClassIndex() stuff or setting up store NPCs may know?

**Comment by broxen** [comment]
What do these models have for Class in the bins?

**Comment by YellowAdder** [comment]
Would you be surprised to hear that they don't have one?

`"Name": "Model_IconEmployeeA",
            "DisplayName": "",
            "Rank": 0,
            "Class": "",
            "Level": 0,
            "XP": 0,
            "Powers": [],
            "Costumes": [ ...`

**Comment by broxen** [comment]
Yeah I can't read the issue tittle that I wrote 🤣

Sounds like we just need to handle that scenario in `getEntityClassIndex()` and provide some generic class. Or maybe there is a class in classes.bin or villian_classes.bin for shop vendors

Seems like a `good first issue` so I'll mark it as such.

**Comment by YellowAdder** [comment]
Well it's not the Freedom Corp store (or regular FC) models, so I'm not sure which one in Atlas is the cause at the moment. When I have more time I'll go through them to figure it out and update here.

**Comment by broxen** [comment]
Could be Ms. Liberty even. You could modify `getEntityClassIndex()` to return the entity idx of the entity in question. But at that point you might as well just pick a generic class idx for the fall-through case and resolve the underlying issue 😋

**Comment by YellowAdder** [comment]
Looking at `getEntityClassIndex()`, it appears that in cases where an invalid or empty ("") class is provided, the response is to give the warning we're concerned about and then return 0, which also happens to be the same value as "Minion".  So, it's actually picking a generic class idx already. 

How do we want to resolve this? Should I remove the qWarning() message and leave a comment in the code to remind that this is a default value for failed lookups? Do we want to default to something other than minion so these cases stand out when encountered in other contexts? (For example, `Class_Minion_Practice`?) To my knowledge, there is no "store" or other applicable critter type for the ones that cause this warning.

**Comment by dracc** [comment]
Should probably default to returning -1? 🤔

**Comment by broxen** [comment]
Thank you for digging into this. I say we change the qWarning to a categorized debug message `qCDebug(logNpcSpawn)` and set them to some discoverable type for lookup. `Class_Minion_Practice` seems fine I suppose.

My one question is does that title `minion` show on the target window when you select them? Because currently it does for Victims and shouldn't (victims aren't a minion for example)

**Comment by broxen** [comment]
Can it return a signed integer?

**Comment by cyanpill** [comment]
The hostage/victims are set m_is_hero=true currently, so it gives the combatant display which includes rank. They should be hero=false and villain=false, and then they would be like any other npc, just displaying the name.

If they are supposed to be a combatant, their rank would be hero or pet or something like that.

**Comment by broxen** [comment]
Ah that explains it. Will file an issue.

**Comment by YellowAdder** [comment]
The return value is signed, and I tested with returning "-1" which didn't appear to have any issues, at least for now. That's arguably a better response to give when no valid type is located. The existing issue with this should go away when the civilian spawning is handled better anyhow.

Here are the types in case we'd prefer something other than -1:

```
[14:15:23] Class Name:  "Class_Minion_Grunt"  IDX:  0
[14:15:23] Class Name:  "Class_Minion_Small"  IDX:  1
[14:15:23] Class Name:  "Class_Lt_Grunt"  IDX:  2
[14:15:23] Class Name:  "Class_Lt_Sniper"  IDX:  3
[14:15:23] Class Name:  "Class_Boss_Grunt"  IDX:  4
[14:15:23] Class Name:  "Class_Boss_Monster"  IDX:  5
[14:15:23] Class Name:  "Class_Boss_Archvillain"  IDX:  6
[14:15:23] Class Name:  "Class_Minion_Practice"  IDX:  7
[14:15:23] Class Name:  "Class_Minion_Pets"  IDX:  8
[14:15:23] Class Name:  "Class_Boss_Guard"  IDX:  9
[14:15:23] Class Name:  "Class_Minion_Swarm"  IDX:  10
[14:15:23] Class Name:  "Class_Boss_Mito"  IDX:  11
[14:15:23] Class Name:  "Class_Boss_Hamidon"  IDX:  12
[14:15:23] Class Name:  "Class_Boss_Guargantuan"  IDX:  13
```

Regarding #851, that can (and should) be solved when the AddEnemy/AddVictim type calls are unified server side, I expect.

**Comment by broxen** [comment]
I think -1 is the way to go
