### ISSUE TITLE
Random vertical teleportation

### ISSUE THREAD

**Issue by HeraldOfOmega** [Segs/Segs#789]
### Describe the bug
After a random period of inactivity, your character will teleport below the map, sometimes even above the map, with your horizontal coordinates remaining the same.

### To Reproduce
Login to a character, move around, then give focus to another program.
After a random period of time (AFK timer?) your character will change it's vertical position.
Last timer was 26 minutes of not having focus.
Moving again afterward, gravity will affect your character as normal.

### Expected behavior
Normalcy

![teleport1](https://user-images.githubusercontent.com/43530827/53315066-554e4500-3876-11e9-8f67-95089d97970f.png)
![teleport2](https://user-images.githubusercontent.com/43530827/53315074-5e3f1680-3876-11e9-9c6a-39921f9090da.png)
![teleport3](https://user-images.githubusercontent.com/43530827/53315084-672fe800-3876-11e9-9a39-54908d5687e9.png)

!

### SEGS Version, C++ Toolkit
 - SEGS Build ID: Feb 17, 2019
 - C++ Toolkit: Qt

**Comment by broxen** [comment]
Is it only height affected, or x/y/z?

**Comment by HeraldOfOmega** [comment]
Looks like the horizontal coords change a little too. I'm pretty near to where I was horizontally.

**Comment by ZopharShinta** [comment]
This looks like the same bug I found. @broxen mentioned it was probably tied to movement.
After X time of inactivity the server updates the client's position?

**Comment by HeraldOfOmega** [comment]
Time varies a lot, sometimes happening whilst interacting with the Luabot.

**Comment by ZopharShinta** [comment]
It would be interesting to see if it happens after a /moveto command.
I believe that updates the clients position on the server too. Should let us know if its tied to movement.

**Comment by HeraldOfOmega** [comment]
Did a /moveto and waited an hour, no teleporting.

**Comment by HeraldOfOmega** [comment]
Did a /stuck and waited an hour, no teleporting.

**Comment by miles200** [comment]
Anything in logs when this occurs?

**Comment by miles200** [comment]
Can't replicate this on linux, will try again tomorrow

**Comment by YellowAdder** [comment]
I've encountered similar random teleportations after moving around a map quite a bit, numerous times in fact. I'm usually active and not idle when this occurs. In my case, the teleports result in being placed a substantial distance away at or very close to maximum height, never below the map.

This makes me suspect it's the result of the ongoing interpolation issue, and the teleport occurs when the vertical height would extend beyond the limit defined by a map. It then "snaps" the character back within the map's boundaries, which of course appears to the user as a dramatic teleport, at least in my case. 

I think in the scenario of an idle character that there is some small but continuous vertical drift initiated by even a slight initial movement forward or backward, and it just takes a while for the server to consider a boundary of some sort to be reached, such as a tree or building or invisible wall. This would also explain why using /moveto or /stuck does not see the teleport occur, so long as no movement is created after using the command. 

Just a guess, anyhow.

**Comment by nemerle** [comment]
Since we're moving to fully custom client now, this problem will have to re-appear there :smile: 
Closing this for now
