### ISSUE TITLE
Increase number of character slots per account and allow configuration in settings.cfg

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#79]
Currently the server allows for only two character slots per account.

I couldn't find where this is regulated in the source, but we should expand this to 12.

**Comment by nemerle** [comment]
This is pretty simple task to increase this ```CharacterDatabase::CreateLinkedAccount``` has the required magic. A slightly more challenging will be making this a configuration variable.

**Comment by broxen** [comment]
Tested this with 12 slots but the GUI of the target client version doesn't handle a long list gracefully. Found the unused macro MAX_CHARACTER_SLOTS in Character.h, which is set at 8 and using that for now.

Recommend leaving this issue open as a max slots variable can be pulled from the settings.cfg
