### ISSUE TITLE
Make world simulation rate configurable

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#791]
## Summary
This one is straight out of the source in Entity.cpp. We'll need to test to see if there are any implications to changing this value, and if there are any bounds to the value that may crash the client (`0 < Ticks <= 100` for example)

```cpp
//TODO: this file needs to know the MapInstance's WorldSimulation rate - Maybe extract it as a configuration object ?
#define WORLD_UPDATE_TICKS_PER_SECOND 30
```

To complete this task, you'll need to add `world_update_ticks_per_sec` to settings_template.cfg and pull that value for use throughout the source (probably in MapInstance.cpp)

**Comment by brwhale** [comment]
I'll test this out!

First issue, get!
