### ISSUE TITLE
Implement collision detection in map server

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#81]
We need to:
- [x] move scene and model loaders to a common library accessible from mapserver and mapviewer both
- [ ] select a scene graph format for mapserver ( maybe use existing engine in headless mode ? )
- [ ] implement scene graph conversion to mapserver format
- [ ] add map loading/conversion in MapInstance class
- [ ] implement Entity-> collision cylinder conversion
- [ ] finally implement the actual collision detection :)

**Comment by broxen** [comment]
Segs/SegsEngine will resolve this. Closing.
