### ISSUE TITLE
What does ClientState `CREATE_TEAM_CONTAINER` do?

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#820]
## Summary
Client appears to have a few extra `ClientStates` that we aren't utilizing. It's unclear what their purpose is as the client doesn't seem to ever actually check against them.

Specifically these two Team related states:
```cpp
 "CREATE_TEAM_CONTAINER",
 "CREATE_TEAM_CONTAINER_WAIT_MAPSVRR_RESPONSE",
```

Found in:
```cpp
static const char *ClientState_Names[6] = {
 "SIMPLE",
 "CREATE_TEAM_CONTAINER",
 "CREATE_TEAM_CONTAINER_WAIT_MAPSVRR_RESPONSE",
 "DEAD",
 "RESURRECT",
 "AWAITING_GURNEY_XFER",
};
```

It could relate to SuperGroups instead of teams? Or even simply means that you have a Yes/No dialog open for joining a Team or becoming a Sidekick.

**Comment by nemerle** [comment]
Since we're moving to fully custom client now, it will mean whatever we want it to :smile:
