### ISSUE TITLE
Multiple PostgreSQL issues

### ISSUE THREAD

**Issue by ldilley** [Segs/Segs#827]
### Describe the bug
There are a multitude of PostgreSQL issues including the following:
* Syntax errors in the SQL scripts:
  * Backticks or single quotes used where double quotes should be:
    ```
    CRITICAL! One of the queries failed to execute.
     Error detail: ERROR:  syntax error at or near "'emails'"
    LINE 3: CREATE TABLE 'emails'(
    ```
    ```
    (42601) QPSQL: Unable to create query ((null):0, (null))
    ```
  * Invalid inserts (`42703` is a PGSQL undefined column error code):
    ```
    QL_ERROR: QSqlError("42703", "QPSQL: Unable to prepare statement", "ERROR:  column \"salt\" of relation \"accounts\" does not exist\nLINE 1: ...INSERT INTO accounts (username,passw,access_level,salt) VALU...\n
    ```
    ```
    -- INSERT INTO accounts VALUES(1,'segsadmin',1,'2017-11-11 17:41:19','7365677331323300000000000000'::bytea);
    ```
* Problems in the code:
  * dbtool:
    ```
    WARNING! Unable to free statement: connection pointer is NULL
    ```
  * Auth/Game DB components (`42601` is a PGSQL invalid syntax error code):
    ```
    [23:51:55] Debug   : Starting up Game DBSync service for server 1
    [23:51:55] Debug   : Starting game(1) db service ... done in 0.009 s
    [23:51:55] Loading AuthDbSync settings...
    [23:51:55] Loading GameDbSync settings...
    [23:51:55] Debug   : Starting game(1) server ... done in 0 s
    [23:51:55] Debug   : QSqlError("42601", "QPSQL: Unable to create query", "ERROR:  syntax error at end of input\nLINE 1: EXECUTE \n                ^\n(42601)")
    [23:51:55] Fatal: Wrong database version (-1) Auth database requires version: 1
    ```
Official PostgreSQL error codes are documented here: https://www.postgresql.org/docs/11/errcodes-appendix.html. There are likely more errors lurking beyond startup. This is obviously caused by neglect in maintaining the PostgreSQL schemas. For example, the `salt` column was never added to `segs_postgres_create.sql` back when our password hashing technique was implemented.

### To Reproduce
1. Build Qt PostgreSQL driver (QPSQL/7) support and ensure libpq lib is in path
2. Set `QPSQL` or `QPSQL7` as the database driver in `settings.cfg`
3. Run `dbtool create` (results in the first two SQL syntax errors reported)
4. After correcting the SQL script syntax, `dbtool adduser ...` results in the following message:
```
WARNING! Unable to free statement: connection pointer is NULL
```
5. Running `segs_server` results in the last Auth DB error reported.

### Expected behavior
`dbtool` and `segs_server` should talk to a PostgreSQL server without complaint.

### Screenshots or Attachments (if applicable)
N/A

### SEGS Version, C++ Toolkit
 - SEGS Build ID: d2d1feb (or even current latest develop: 5d10360)
 - C++ Toolkit: Any/irrelevant
 - Qt version (for driver): 5.12.2
 - PostgreSQL version: 11.2 (same version for libpq.[dll|so])

**Comment by ldilley** [comment]
I'll submit what I have for the PostgreSQL schema fixes in a PR by tomorrow evening. I attempted to get the functionality to match the equivalent MySQL scripts. We'll have to look at the C++ side (`[Auth|Game]DBSyncContext`) afterward.

**Comment by broxen** [comment]
Closing this as it appears ldilley resolved the issue back in April.
