### ISSUE TITLE
After AutoAFK, cannot use chat or interact with the world

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#835]
## Summary
After AutoAFK has activated, the player can no longer interact with the world, or chat in the chat window.

@YellowAdder experienced this on the test server earlier today, and I did again this evening.

Might be a duplicate of #834

**Comment by EmileFrost** [comment]
Experienced this on Red server this evening. No AutoAFK showing above my character's head but could not interact. My chat was not being shown but other players' chat was visible.

**Comment by broxen** [comment]
Fix incoming for this.
