### ISSUE TITLE
`getRelayRaceResult` in `DataHelpers.cpp` could possibly return garbage

### ISSUE THREAD

**Issue by erpmario** [Segs/Segs#837]
This doesn't really fit into any issue category, but it's something I thought I should bring up. In the `getRelayRaceResult` function in `DataHelpers.cpp`, it is possible for the function to return an uninitialized garbage value. The `result` variable is only set to a valid `RelayRaceResult` if `r`'s `m_segment`  member matches the passed value. This is not guaranteed to happen, and so if the for-loop concludes without finding a match, the function will happily return `result`'s garbage value.

To alleviate this, we could remove the middleman `result` variable altogether and simply return whichever `r` matches the passed `segment` value. If the loop goes to completion without a match, return some sort of known error status. Maybe have a state variable within `RelayRaceResult` that tells you if it's valid or not. We don't currently return a pointer to a `RelayRaceResult`, so `nullptr` would not work, but we might alternatively consider refactoring the function to return a pointer.

**Comment by erpmario** [comment]
Don't mind me, just facepalming because I forgot how default stack-based allocation works! Looks like the only thing that's garbage is me. :smile:

**Comment by broxen** [comment]
Referenced code:
https://github.com/Segs/Segs/blob/5d10360f4a6e86a3ad4d9295fb149faadcaf32da/Projects/CoX/Servers/MapServer/DataHelpers.cpp#L1988

**Comment by broxen** [comment]
The values in `RelayRaceResult` should be defined as `undefined` which most compilers would treat as 0 for these types.
https://github.com/Segs/Segs/blob/2e9092b6e7c367db671b2e53c9a1c664058b4be8/Projects/CoX/Common/GameData/PlayerStatistics.h#L23..L33

**Comment by erpmario** [comment]
Yeah, like I commented up above, I forgot that nonprimitives will call the default constructor when declared like `RelayRaceResult result;`. So it won't be garbage, just whatever the default constructor sets everything to.

**Comment by broxen** [comment]
Closing this as wont-fix per this discussion
