### ISSUE TITLE
Fly doesn't seem to work after recent powers PR

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#838]
## Summary
For some reason, it seems as though Fly and Hover don't work with the latest Powers PR. Clicking on either does not toggle flying, but instead spams the chat window with `You are healed for 0!` messages every tick

![Screenshot from 2019-04-03 22-00-05](https://user-images.githubusercontent.com/10159505/55530685-e8d81a00-565b-11e9-9846-8cfc94480f38.png)

**Comment by broxen** [comment]
Looks to be an issue with this section?
https://github.com/Segs/Segs/blob/268f5e9d1a9d095230ec49eed29c9df5fd6f5613/Projects/CoX/Common/GameData/EntityHelpers.cpp#L258

**Comment by cyanpill** [comment]
Is powers.json in data/bin/ ? I removed the hardcoding of powers, which includes the travel powers you put in. /fly should always work :smile

**Comment by broxen** [comment]
Oops. No I put powers.json in `/data/`

Will move and test again

**Comment by broxen** [comment]
That resolved the issue. You rock cyan!

I'll recommend they create a README in the power.json folder on the segs community repo to explain where installation should go.
