### ISSUE TITLE
SEGSAdmin doesn't set log_generic to appropriate values

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#846]
### Summary
SEGSAdmin generates a new cfg if one does not exist, but it doesn't correctly set the value for `log_generic` from the template file.

We should set `log_generic         = *.debug=true\nqt.*.debug=false` so that debug output is properly shown in the console window. Building with Release should disable this output anyway.

It's useful to allow it to be configured, but setting to false by default seems like unexpected behavior and may make troubleshooting with a user unfamiliar with the code base more difficult.

**Comment by broxen** [comment]
Proposing we either A) show a special input field for log_generic only, or B) simply hide it from SEGSAdmin altogether.

**Comment by miles200** [comment]
I'd hide log_generic from SEGSAdmin, and add the appropriate value to the generate log file code within SettingsDialog.cpp
