### ISSUE TITLE
Failed to retrieve script func: player_connected

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#849]
## Summary
Upon new player login, the server is trying to load a Lua function and fails. `Critical: Failed to retrieve script func: player_connected`

Doesn't appear to cause any instability, but we should correct the issue.

**Comment by YellowAdder** [comment]
This error means that entities.lua is failing to load for the map in question, presumably Outbreak in this case. There's probably some info in the server console that will give more insight as to the source of the failure, especially if it came from an scripting error.
