### ISSUE TITLE
Rewrite CONTRIBUTING.md to make it clear we are NOT using Leaked Code

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#876]
## Summary
Given recent events regarding leaked source code, it's important for SEGS to make it clear that we are running a CLEAN ROOM environment and NOT utilizing any source code in our endeavors.

Our Contributing doc should reflect this:
https://github.com/Segs/Segs/blob/develop/docs/CONTRIBUTING.md

**Comment by cat4hurricane** [comment]
I'll pick up this issue!
