### ISSUE TITLE
Use QSettings in the codebase

### ISSUE THREAD

**Issue by nemerle** [Segs/Segs#89]
using QSettings in the codebase should make retrieving various config variables much easier:

- [ ]  Use [QSettings::setPath](http://doc.qt.io/qt-5/qsettings.html#setPath) to set ini path globally 
- [ ] Use [QSettings::setDefaultFormat](http://doc.qt.io/qt-5/qsettings.html#setDefaultFormat) to set default format to ini files.
- [ ] Check if using QSettings constructor with a single "SEGS" argument whenever we need to access configuration will read/produce the same INI files as it does now, if it doesn't update the default ini files.

**Comment by nemerle** [comment]
After some experiments:
Using defaulted QSettings causes the ini file to be located under:
ConfiguredOrganisationName/ApplicationName.ini
so in case when we do:
```cpp
QSettings::setPath(QSettings::UserScope,".")
QSettings::setDefaultFormat(QSettings::IniFormat);
QApplication::setOrganizationName("SEGS Project");
QApplication::setApplicationName("authserver");
```
QSetting will access "SEGS Project/authserver.cfg".
I'm not 100% sure this is a change we want :pensive:

**Comment by broxen** [comment]
Seems like that would be confusing to the end user.

We could use `void QSettings::setPath(Format format, Scope scope, const QString &path)` to override the paths and set our own format?

I think it's designed this way because the application directory often isn't writable by the runtime user without some variation of UAC. QSettings then tries to solve the problem in a cross-platform compatible manner.

I guess this probably won't be an issue though, as someone running their own server can be expected to be savvy enough to figure it out?

**Comment by broxen** [comment]
Sorry I meant `QSettings settings( iniFileName, QSettings::IniFormat );`

I should give myself time to wake up before posting 😋

**Comment by nemerle** [comment]
Yup, but the whole idea of this ticket was the ability to use default QSettings constructor anywhere to access application settings and at the same time have a constant directory where the config file resided.

**Comment by ldilley** [comment]
Create a wrapper class with all the things™.

**Comment by broxen** [comment]
Ahh I misunderstood. Agree with Idilley, wrapping with our own function sounds like it would do the trick, but that may be over my head, so I'll take a step back to watch and learn.

**Comment by broxen** [comment]
For those following. I'm working on this in https://github.com/broxen/Segs/tree/qsettings

I need to test the new `/settingsdump` slash command to see if everything is working, and then I'll go about utilizing this implementation wherever settings are used in the rest of the source.
