### ISSUE TITLE
Error bodypart_definition.cpp

### ISSUE THREAD

**Issue by crazyduck33** [Segs/Segs#899]
Compile always fails with following Message 

J:\spiele\COH\Segs\Projects\CoX\Common\GameData\bodypart_definitions.cpp:120: error: 'class QByteArray' has no member named 'compare'
         if ( 0==bp.m_Name.compare(name,Qt::CaseInsensitive) )
                           ^
mingw32-make.exe[2]: *** [Projects/CoX/Common/GameData/CMakeFiles/gameData.dir/bodypart_definitions.cpp.obj] Error 1

**Comment by broxen** [comment]
Thank you for reporting this!

This is because QByteArray::compare() was introduced in QT 5.12, try updating QT and you should be able to compile without issue.

**Comment by broxen** [comment]
Closing this as updating QT fixes the issue.
