### ISSUE TITLE
Unable to abort disconnect

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#93]
### Expected behavior
When quitting or logging out, a countdown begins allowing a user to abort the disconnect by pressing any key.

### Actual behavior/symptoms
Disconnect is not aborted, client disconnects.

### Steps to reproduce behavior/symptoms
Start server, log in, select character, log out > try to abort log out by pressing any key.

### SEGS version
clone of latest git

### Operating system
Test on Windows 10 (also in compat mode for XP-SP3 and Win7)

### C++ compiler and version
g++ 5.3.0 (mingw530_32)

**Comment by nemerle** [comment]
This will likely require find out which packet the client sends when it aborts disconnect

**Comment by nemerle** [comment]
Do'h it's the same on that starts the disconnect process:
MapEvents.h:ClientQuit ```reason``` field actually means ```abort_disconnect```
