### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by zidingz** [Segs/Segs#941]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by nemerle** [comment]
As the SEGS project has not exited from the alpha stage of development, all security concerns should be reported using standard Github issues.

When we have a publicly available beta/release version, security policy will be updated to provide a valid contact point to report such issues.

**Comment by JamieSlome** [comment]
@nemerle - thanks for your response and apologies for not getting back to you on this.

You can find the report directly here:

https://huntr.dev/bounties/3bce38cd-235e-4f29-b3cc-d13684800311/

It is publicly visible, so you will be able to see the contents of the report 👍
