### ISSUE TITLE
SEGS-Admin Font Colors not correct for Darkmodes

### ISSUE THREAD

**Issue by mobbyg** [Segs/Segs#944]
### Describe the bug
Running SEGS-Admin on iMac in Darkmode, the text in the fields for Server IP and ports, etc.. are all white, and the field brackgrounds are white as well. 

### To Reproduce
1. Open SEGS-Admin on iMac in dark mode
2. Navigate to the Server Settings window
3. All text is white in a white fields. 

### Expected behavior
Text should be a darker color to be seen. 

### Screenshots or Attachments (if applicable)
<img width="1056" alt="Screen Shot 2022-04-05 at 3 01 20 PM" src="https://user-images.githubusercontent.com/5174814/161830118-84e1257e-62f3-4273-b3d3-d7213a500805.png">

### SEGS Version, C++ Toolkit
 - SEGS Build ID:
 - C++ Toolkit:

**Comment by mobbyg** [comment]
This appears to be an issue with Qt on MacOS and the inheritance of dark mode settings. Changing the palette and colors in Qt Designer doesn't seem to correct any issues, and then also causes issues with the Windows UI if you try and make changes. Next step could be style sheets to fix the issue.

**Comment by miles200** [comment]
Fixed by #964
