### ISSUE TITLE
Should not be able to log into the same Account twice simultaneously.

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#95]
### Summary
Logging in with the same Account and same character results in the CoX client crashing and if tried repeatedly, the server crashing.

![screenshot from 2018-01-23 17-04-19](https://user-images.githubusercontent.com/10159505/35309143-b49e2c32-005f-11e8-93f7-4e4a7d0b173a.png)

Looks like the server needs to handle this code `0x7f5ffc019700` gracefully.

```
(3274|140050713548544) Connection closed
 Telling map server to expect a client with character Sarim,1
Sending msg to client 0x7f5ffc01c080
(3274|140050713548544) Connection closed
 Telling map server to expect a client with character Sarim,1
Sending msg to client 0x7f5ffc019700
(3274|140050713548544) Connection closed
 Telling map server to expect a client with character Sarim,1
Sending msg to client 0x7f5ffc019700
^CSegmentation fault (core dumped)
```

### SEGS version
clone of latest git

### Operating system
Fedora 26

### C++ compiler and version
gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)

**Comment by broxen** [comment]
Really, we shouldn't be able to log into the same account simultaneously at all. I'm changing this issue's title to reflect that, as it will then resolve the issue with crashing.

Looks like it's handled in `AuthHandler.cpp` but needs to be fleshed out.
https://github.com/Segs/Segs/blob/9625d5878d3d6bdff0bb94e5258dba5dd86cff60/Projects/CoX/Servers/AuthServer/AuthHandler.cpp#L135-L140

I thought maybe we could just return early, but I'm just misunderstanding the logic:
```
auth_error(lnk,err);
```

As a side note:
AUTH_ALREADY_LOGGEDIN is defined twice, here:
https://github.com/Segs/Segs/blob/9625d5878d3d6bdff0bb94e5258dba5dd86cff60/Projects/CoX/Servers/AuthServer/AuthHandler.h#L45
and here:
https://github.com/Segs/Segs/blob/9625d5878d3d6bdff0bb94e5258dba5dd86cff60/Projects/CoX/Servers/AuthServer/AuthServer.h#L48

**Comment by nemerle** [comment]
the main verification logic is done in ```bool AuthClient::isLoggedIn()``` but this code only checks if the client is connected to a GameServer. 
Correct version would also retrieve current map for the given client, and verify the connection there as well, since we have only one map instance, we can simply replicate the ClientConnectionQuery/ClientConnectionResponse logic from GameHandler

**Comment by broxen** [comment]
Need to test to see if this is resolved in latest master

**Comment by broxen** [comment]
Per James in discord, this has been tested on Windows and will correctly block multiple logins.

I can confirm on Linux as well.
